# Generated by Django 2.2.8 on 2020-01-22 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='seats_remaining',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
