# Generated by Django 2.2.8 on 2020-01-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200123_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='checked_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
