# Generated by Django 4.0.8 on 2023-09-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_session_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.DeleteModel(
            name='CreatorFestSession',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
