# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0002_auto_20160222_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ally',
            name='ally_category',
        ),
        migrations.AddField(
            model_name='ally',
            name='adaptive_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='customized_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='online_course',
            field=models.BooleanField(default=False),
        ),
    ]
