# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0002_auto_20160217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='ally',
            field=models.ForeignKey(help_text='Manage allies through snippets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allies_ally', to='allies.Ally'),
        ),
    ]
