# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0003_auto_20160217_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allies',
            name='ally',
        ),
        migrations.RemoveField(
            model_name='allies',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='ally',
            name='link_text',
            field=models.CharField(default='', help_text='Call to Action Text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='link_url',
            field=models.URLField(blank=True, help_text='Call to Action Link'),
        ),
        migrations.DeleteModel(
            name='Allies',
        ),
    ]
