# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('snippets', '0001_initial'),
        ('allies', '0004_auto_20160224_1124'),
        ('allies', '0004_auto_20160224_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='AllySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ally',
            name='id',
        ),
        migrations.AddField(
            model_name='ally',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allysubject',
            name='ally',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ally_subjects', to='allies.Ally'),
        ),
        migrations.AddField(
            model_name='allysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Subject'),
        ),
    ]
