# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0006_ally_is_ap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ally',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='link_url',
        ),
    ]
