# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0008_auto_20160407_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='logo_bw',
            field=models.ForeignKey(blank=True, help_text='Image should be 340px wide, grayscale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_bw', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='ally',
            name='logo_color',
            field=models.ForeignKey(blank=True, help_text='Image should be 460px wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_color', to='wagtailimages.Image'),
        ),
    ]
