# Generated by Django 5.1.1 on 2024-09-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allies", "0011_auto_20180301_1107"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ally",
            name="adaptive_courseware",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="customization_tools",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="do_not_display",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="heading",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="is_ap",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="logo_bw",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="logo_color",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="long_description",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="online_homework",
        ),
        migrations.RemoveField(
            model_name="ally",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="allysubject",
            name="ally",
        ),
        migrations.RemoveField(
            model_name="allysubject",
            name="subject",
        ),
    ]
