# Generated by Django 2.2.8 on 2020-02-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0011_auto_20180301_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allysubject',
            name='ally',
        ),
        migrations.RemoveField(
            model_name='allysubject',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Ally',
        ),
        migrations.DeleteModel(
            name='AllySubject',
        ),
    ]
