codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: false
    patch: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false
ignore:
  - "*tests.py"
  - 'manage.py'
  - '*/migrations/*'
  - '*/settings/*'
  - '*settings.py'
  - '*wsgi.py'
  - '*/__init__.py'
  - '*/urls.py'
  - 'versions/*'  # this is internal only, and not mission critical
  - 'wagtailimportexport/*'  # this doesn't work, candidate for removal / offloading / rewriting