# Generated by Django 2.0.2 on 2018-05-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('news', '0002_auto_20180515_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmention',
            name='source',
        ),
        migrations.AddField(
            model_name='newsmention',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='newsmention',
            name='source_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
    ]
