# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('news', '0003_auto_20160517_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='press_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
