# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160523_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
