# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20160617_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='heading',
        ),
    ]
