# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_newsarticle_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='heading',
            field=models.CharField(default='', help_text='Heading displayed on website', max_length=250),
            preserve_default=False,
        ),
    ]
