# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20161018_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Image should be 1200 x 600', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
