# Generated by Django 2.0.2 on 2018-05-09 15:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_auto_20180509_1010'),
        ('news', '0019_experts_expertspr_pressindex_pressrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSourcesPR',
            fields=[
                ('newssources_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsSources')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('experts_pr', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sources_pr', to='news.PressRelease')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('news.newssources', models.Model),
        ),
        migrations.AddField(
            model_name='newssources',
            name='news_source',
            field=models.ForeignKey(help_text='Manage news sources through snippets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_sources', to='snippets.NewsSource'),
        ),
    ]
