# Generated by Django 2.0.2 on 2018-05-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20180515_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionStatement',
        ),
        migrations.RemoveField(
            model_name='missionstatements',
            name='mission_statements',
        ),
        migrations.DeleteModel(
            name='MissionStatements',
        ),
    ]
