# Generated by Django 2.0.2 on 2018-05-15 21:19

from django.db import migrations
import news.models
import snippets.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_remove_newsmention_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmentions',
            name='news_mentions',
        ),
        migrations.RemoveField(
            model_name='newsmentions',
            name='newsmention_ptr',
        ),
        migrations.AddField(
            model_name='pressindex',
            name='news_mentions',
            field=wagtail.core.fields.StreamField((('source', news.models.NewsSourceChooserBlock(snippets.models.NewsSource)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('headline', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewsMention',
        ),
        migrations.DeleteModel(
            name='NewsMentions',
        ),
    ]
