# Generated by Django 2.0.2 on 2018-05-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20180517_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmention',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsmentions',
            name='news_mentions',
        ),
        migrations.RemoveField(
            model_name='newsmentions',
            name='newsmention_ptr',
        ),
        migrations.DeleteModel(
            name='NewsMention',
        ),
        migrations.DeleteModel(
            name='NewsMentions',
        ),
    ]
