# Generated by Django 2.0.2 on 2018-05-15 21:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import news.models
import snippets.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20180515_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', wagtail.core.fields.StreamField((('source', news.models.NewsSourceChooserBlock(snippets.models.NewsSource)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('headline', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))), blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newssources',
            name='news_source',
        ),
        migrations.RemoveField(
            model_name='newssourcespr',
            name='experts_pr',
        ),
        migrations.RemoveField(
            model_name='newssourcespr',
            name='newssources_ptr',
        ),
        migrations.RemoveField(
            model_name='pressindex',
            name='news_mentions',
        ),
        migrations.CreateModel(
            name='NewsMentions',
            fields=[
                ('newsmention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsMention')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('news_mentions', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='news.PressIndex')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('news.newsmention', models.Model),
        ),
        migrations.DeleteModel(
            name='NewsSources',
        ),
        migrations.DeleteModel(
            name='NewsSourcesPR',
        ),
    ]
