# Generated by Django 2.0.2 on 2018-05-17 19:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_newssource'),
        ('news', '0025_auto_20180517_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsMentions',
            fields=[
                ('newsmention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsMention')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('news_mentions', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='news.PressIndex')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('news.newsmention', models.Model),
        ),
        migrations.AddField(
            model_name='newsmention',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippets.NewsSource'),
        ),
    ]
