# Generated by Django 2.0.2 on 2018-05-15 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20180515_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsmention',
            name='mention',
        ),
        migrations.AddField(
            model_name='newsmention',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmention',
            name='headline',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmention',
            name='url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmention',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.NewsSource'),
        ),
    ]
