# Generated by Django 2.0.2 on 2018-05-17 19:43

from django.db import migrations
import news.models
import snippets.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20180517_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmention',
            name='source',
        ),
        migrations.RemoveField(
            model_name='newsmentions',
            name='news_mentions',
        ),
        migrations.RemoveField(
            model_name='newsmentions',
            name='newsmention_ptr',
        ),
        migrations.AddField(
            model_name='pressindex',
            name='mentions',
            field=wagtail.core.fields.StreamField((('source', news.models.NewsMentionChooserBlock(snippets.models.NewsSource)), ('url', wagtail.core.blocks.URLBlock()), ('headline', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock())), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewsMention',
        ),
        migrations.DeleteModel(
            name='NewsMentions',
        ),
    ]
