# Generated by Django 2.0.2 on 2018-05-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20180515_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressindex',
            name='news_mentions',
        ),
    ]
