# Generated by Django 2.0.2 on 2018-07-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('news', '0034_remove_newsarticle_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Image should be 1200 x 600', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
