# Generated by Django 3.2.9 on 2022-04-12 13:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0020_blogcontenttype'),
        ('news', '0035_auto_20210226_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsarticle_content_type', to='snippets.blogcontenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('contenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.contenttype')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('blog_category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_type', to='news.newsarticle')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('news.contenttype', models.Model),
        ),
    ]
