# Generated by Django 3.2.9 on 2022-04-20 18:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_blogtype_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='collections',
            field=wagtail.fields.StreamField([('collection', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('collection', wagtail.snippets.blocks.SnippetChooserBlock(label='Blog Collection', required=True, target_model='BlogCollection')), ('featured', wagtail.blocks.BooleanBlock(label='Featured')), ('popular', wagtail.blocks.BooleanBlock(label='Popular'))])))], null=True),
        ),
    ]
