# Generated by Django 4.0.4 on 2022-05-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_alter_newsarticle_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
