# Generated by Django 4.0.4 on 2022-05-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_alter_newsarticletag_tag'),
        ('news', '0041_auto_20220517_1353'),
    ]

    operations = [
    ]
