# Generated by Django 3.2.5 on 2022-05-20 16:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_auto_20220520_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='featured_video',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
