# Generated by Django 3.2.5 on 2022-05-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_merge_20220519_1249'),
        ('news', '0044_auto_20220520_1158'),
    ]

    operations = [
    ]
