# Generated by Django 4.0.8 on 2023-06-05 13:00

from django.db import migrations
import news.models
import snippets.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0048_pressindex_faqs_pressindex_infographic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressindex',
            name='about',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressindex',
            name='mentions',
            field=wagtail.fields.StreamField([('mention', wagtail.blocks.StructBlock([('source', news.models.NewsMentionChooserBlock(snippets.models.NewsSource)), ('url', wagtail.blocks.URLBlock()), ('headline', wagtail.blocks.CharBlock()), ('date', wagtail.blocks.DateBlock()), ('featured_in', wagtail.blocks.BooleanBlock(default=False, help_text='Check if displayed in Featured In section', required=False))], icon='document'))], null=True, use_json_field=True),
        ),
    ]
