# Generated by Django 5.0.7 on 2024-08-19 19:29

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0050_newsindex_display_footer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressindex",
            name="faqs",
            field=wagtail.fields.StreamField(
                [
                    (
                        "faq",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "question",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The visible text of the question (does not collapse).", required=True
                                    ),
                                ),
                                (
                                    "slug",
                                    wagtail.blocks.CharBlock(
                                        help_text="Not visible to user, must be unique in this FAQ.", required=True
                                    ),
                                ),
                                (
                                    "answer",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The answer to the question, is hidden until the question is expanded.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        help_text="Not sure this does anything.", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
