# Generated by Django 5.2.15 on 2026-07-10 00:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0053_alter_newsarticle_body_alter_pressindex_faqs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressindex",
            name="faqs",
            field=wagtail.fields.StreamField(
                [("faq", 84)],
                blank=True,
                block_lookup={
                    0: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    2: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describes the table; rendered as a <caption> for accessibility.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("text", "Text"), ("number", "Number"), ("date", "Date")],
                            "help_text": "How readers sort this column. Default text.",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("header", 5), ("type", 6)]], {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {"default": [], "label": "Columns"}),
                    9: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "Rich-text cell content. Ignored when a Call To Action is set.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    13: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    14: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 12), ("internal", 13), ("document", 14), ("anchor", 15)]],
                        {"required": True},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    18: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 17), ("custom_color", 18)]],
                        {
                            "block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("aria_label", 11), ("target", 16), ("config", 19)]],
                        {"label": "Link", "required": False},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    22: ("wagtail.blocks.StructBlock", [[("content", 9), ("cta", 21)]], {}),
                    23: ("wagtail.blocks.ListBlock", (22,), {"default": []}),
                    24: ("wagtail.blocks.StructBlock", [[("cells", 23)]], {}),
                    25: ("wagtail.blocks.ListBlock", (24,), {"default": [], "label": "Rows"}),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.Subject",),
                        {"help_text": "Only books in this subject. Leave empty for all subjects.", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("live", "Live"),
                                ("coming_soon", "Coming Soon"),
                                ("new_edition_available", "New Edition Forthcoming"),
                                ("deprecated", "Deprecated"),
                            ],
                            "help_text": "Only books in this state. Leave empty for all listed books.",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title A–Z"),
                                ("-publish_date", "Newest first"),
                                ("publish_date", "Oldest first"),
                            ],
                            "help_text": "Row order. Default Title A–Z.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 100.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title"),
                                ("title_link", "Title (linked to book page)"),
                                ("subjects", "Subjects"),
                                ("publish_date", "Publish date"),
                                ("book_state", "State"),
                                ("cover", "Cover image"),
                                ("is_ap", "AP"),
                                ("read_online", "Read online (link)"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Column header shown to readers. Defaults to the field label.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Overrides how the value is shown and sorted. Default per field.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 30), ("header", 31), ("type", 32)]],
                        {"label": "Column"},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"label": "Columns", "min_num": 1}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 26), ("book_state", 27), ("order", 28), ("limit", 29), ("columns", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Only articles with this subject, e.g. Science. Matches the article's subjects list.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Only articles with this tag (exact tag name).", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("-date", "Newest first"),
                                ("date", "Oldest first"),
                                ("heading", "Heading A–Z"),
                            ],
                            "help_text": "Row order. Default newest first.",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 20.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("heading", "Heading"),
                                ("heading_link", "Heading (linked to article)"),
                                ("subheading", "Subheading"),
                                ("author", "Author"),
                                ("date", "Post date"),
                                ("image", "Article image"),
                            ]
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 40), ("header", 31), ("type", 32)]],
                        {"label": "Column"},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"label": "Columns", "min_num": 1}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 36), ("tag", 37), ("order", 38), ("limit", 39), ("columns", 42)]],
                        {},
                    ),
                    44: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["books.Book"]}),
                    45: (
                        "wagtail.blocks.ListBlock",
                        (44,),
                        {
                            "help_text": "The book(s) whose resources fill the table. A resource shared across several books is listed once, with all its book names.",
                            "label": "Books",
                            "min_num": 1,
                        },
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("instructor", "Instructor resources"), ("student", "Student resources")]},
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("all", "All"), ("k12", "K12 only")],
                            "help_text": 'K12 only limits rows to resources flagged "Display on K12".',
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("book", "Book(s)"),
                                ("heading", "Resource"),
                                ("description", "Description"),
                                ("link", "Link"),
                                ("coming_soon", "Coming soon"),
                                ("k12", "K12"),
                                ("unlocked", "Unlocked"),
                            ]
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 48), ("header", 31), ("type", 32)]],
                        {"label": "Column"},
                    ),
                    50: ("wagtail.blocks.ListBlock", (49,), {"label": "Columns", "min_num": 1}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("books", 45), ("resource_type", 46), ("audience", 47), ("columns", 50)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("he", "Higher Ed subjects"), ("k12", "K12 subjects")]},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "K12 only: limit to a category, e.g. Math.", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("name", "Subject"),
                                ("category", "Category"),
                                ("color", "Color"),
                                ("icon", "Icon"),
                                ("link", "Link (K12 subject pages)"),
                            ]
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 54), ("header", 31), ("type", 32)]],
                        {"label": "Column"},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"label": "Columns", "min_num": 1}),
                    57: ("wagtail.blocks.StructBlock", [[("variant", 52), ("k12_category", 53), ("columns", 56)]], {}),
                    58: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be a relative path starting with /apps/cms/api/."},
                            "help_text": "Relative CMS API path including query string, e.g. /apps/cms/api/v2/pages/?type=books.Book&fields=title,cover_url&book_state=live. Must start with /apps/cms/api/. No absolute URLs — they break across environments.",
                            "label": "Endpoint path",
                            "regex": "^/apps/cms/api/\\S*$",
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "items",
                            "help_text": 'JSON key holding the list of rows. Default "items" (the Wagtail API shape); clear it if the response is a bare list.',
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Dotted path into each item, e.g. title or meta.slug.", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Column header. Defaults to the field path.", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Cell type. Default text.",
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 60), ("header", 61), ("type", 62)]],
                        {"label": "Column"},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"label": "Columns", "min_num": 1}),
                    65: ("wagtail.blocks.StructBlock", [[("path", 58), ("items_key", 59), ("columns", 64)]], {}),
                    66: (
                        "wagtail.blocks.StreamBlock",
                        [[("books", 35), ("news", 43), ("book_resources", 51), ("subjects", 57), ("endpoint", 65)]],
                        {
                            "help_text": "Fill the table from CMS content instead of manual rows. When set, manual Columns and Rows are ignored.",
                            "label": "Data source",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Shade alternating rows. Default shade unless Row Colors is set.",
                        },
                    ),
                    68: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ffffff,#f2f2f2."},
                            "help_text": "Comma-separated hex colors cycled across body rows, e.g. #ffffff,#f2f2f2. Overrides the default zebra shade.",
                            "label": "Row Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("off", "Off"), ("on", "On")], "help_text": "Tighter cell padding."},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Let readers sort by clicking column headers.",
                        },
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Show a text box that filters rows by their content.",
                        },
                    ),
                    72: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "1-based column number the table is sorted by on load.", "min_value": 1},
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("asc", "Ascending"), ("desc", "Descending")],
                            "help_text": "Direction for the default sort. Default ascending.",
                        },
                    ),
                    74: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": 'Show at most this many rows, with a "Show more" control for the rest.',
                            "min_value": 1,
                        },
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown when the table has no rows (e.g. a dynamic source returns nothing).",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "^[a-zA-Z0-9_-]+$",
                        },
                    ),
                    77: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("striped", 67),
                                ("row_colors", 68),
                                ("condensed", 69),
                                ("sortable", 70),
                                ("filterable", 71),
                                ("default_sort_column", 72),
                                ("default_sort_direction", 73),
                                ("row_limit", 74),
                                ("empty_message", 75),
                                ("id", 76),
                            ]
                        ],
                        {
                            "block_counts": {
                                "condensed": {"max_num": 1},
                                "default_sort_column": {"max_num": 1},
                                "default_sort_direction": {"max_num": 1},
                                "empty_message": {"max_num": 1},
                                "filterable": {"max_num": 1},
                                "id": {"max_num": 1},
                                "row_colors": {"max_num": 1},
                                "row_limit": {"max_num": 1},
                                "sortable": {"max_num": 1},
                                "striped": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 4), ("columns", 8), ("rows", 25), ("data_source", 66), ("config", 77)]],
                        {},
                    ),
                    79: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": True}),
                    80: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    81: ("wagtail.blocks.StructBlock", [[("image", 79), ("alt_text", 80)]], {"label": "Image"}),
                    82: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    83: (
                        "wagtail.blocks.StreamBlock",
                        [[("table", 78), ("image", 81), ("text", 82)]],
                        {
                            "collapsed": True,
                            "help_text": "Optional table, image, or extra text shown as part of the answer.",
                            "label": "Additional content",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("slug", 1), ("answer", 2), ("document", 3), ("content", 83)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
