# Generated by Django 3.0.4 on 2020-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial_squashed_0100_videofacultyresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyresources',
            name='link_text',
            field=models.CharField(help_text='Call to Action Text', max_length=255),
        ),
    ]
