# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160204_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='license_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='license_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='license_version',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cnx_id',
            field=models.CharField(help_text='ID@VERSION', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
