# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160204_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='display_at_top',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
