# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160222_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstudentresources',
            name='book_student_resource',
        ),
        migrations.RemoveField(
            model_name='bookstudentresources',
            name='studentresources_ptr',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='resource',
        ),
        migrations.DeleteModel(
            name='BookStudentResources',
        ),
        migrations.DeleteModel(
            name='StudentResources',
        ),
    ]
