# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160204_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributingauthors',
            name='authors_ptr',
        ),
        migrations.RemoveField(
            model_name='contributingauthors',
            name='resource',
        ),
        migrations.AddField(
            model_name='authors',
            name='book',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contributing_authors', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='display_at_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authors',
            name='senior_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='cnx_id',
            field=models.CharField(help_text='This is used to pull relevant information from CNX.', max_length=255),
        ),
        migrations.DeleteModel(
            name='ContributingAuthors',
        ),
    ]
