# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('books', '0006_auto_20160225_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='high_resolution_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='book',
            name='ibook_link',
            field=models.URLField(blank=True, help_text='Link to iBook'),
        ),
        migrations.AddField(
            model_name='book',
            name='low_resolution_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='book',
            name='webview_link',
            field=models.URLField(blank=True, help_text='Link to CNX Webview book'),
        ),
    ]
