# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20160208_1206'),
        ('books', '0002_auto_20160210_1605'),
    ]

    operations = [
    ]
