# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20160229_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='concept_coach_link',
            field=models.URLField(blank=True, help_text='Link to Concept Coach'),
        ),
    ]
