# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('books', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='link_page',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Description shown on Book Detail page.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Description shown on Subject page.'),
        ),
        migrations.AlterField(
            model_name='studentresources',
            name='resource_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.LinkFields'),
        ),
        migrations.DeleteModel(
            name='ResourceLink',
        ),
    ]
