# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_concept_coach_link'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyResource',
        ),
        migrations.DeleteModel(
            name='StudentResource',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.Subject'),
        ),
        migrations.AlterField(
            model_name='facultyresources',
            name='resource',
            field=models.ForeignKey(help_text='Manage resources through snippets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.FacultyResource'),
        ),
        migrations.AlterField(
            model_name='studentresources',
            name='resource',
            field=models.ForeignKey(help_text='Manage resources through snippets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.StudentResource'),
        ),
    ]
