# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookquotes_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='allies',
            name='ally_category',
            field=models.CharField(choices=[('OH', 'Online Homework'), ('AC', 'Adaptive Courseware'), ('CT', 'Customized Tools')], default='OH', max_length=2),
            preserve_default=False,
        ),
    ]
