# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20160210_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.RenameField(
            model_name='bookfacultyresources',
            old_name='resource',
            new_name='book_facutly_resource',
        ),
        migrations.RenameField(
            model_name='bookstudentresources',
            old_name='resource',
            new_name='book_student_resource',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='heading',
        ),
        migrations.AddField(
            model_name='facultyresources',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Resource'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Resource'),
        ),
    ]
