# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20160307_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_blurb',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Link to Amazon'),
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='book',
            name='bookshare_link',
            field=models.URLField(blank=True, help_text='Link to Bookshare resources'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookstore_blurb',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bookstore_link',
            field=models.URLField(blank=True, help_text='Link to Bookstore'),
        ),
    ]
