# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        #('allies', '0004_auto_20160217_1647'),
        ('books', '0009_auto_20160210_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAlly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_link_url', models.URLField(blank=True, help_text='Call to Action Link')),
                ('book_link_text', models.CharField(help_text='Call to Action Text', max_length=255)),
                ('ally', models.ForeignKey(help_text='Manage allies through snippets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allies_ally', to='allies.Ally')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='allies',
            name='logo',
        ),
        migrations.RenameField(
            model_name='bookallies',
            old_name='ally',
            new_name='book_ally',
        ),
        migrations.RenameField(
            model_name='bookfacultyresources',
            old_name='resource',
            new_name='book_faculty_resource',
        ),
        migrations.RenameField(
            model_name='bookstudentresources',
            old_name='resource',
            new_name='book_student_resource',
        ),
        migrations.RemoveField(
            model_name='bookallies',
            name='allies_ptr',
        ),
        migrations.RemoveField(
            model_name='bookquotes',
            name='ally',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentresources',
            name='heading',
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='quote',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_quotes', to='books.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.Subject'),
        ),
        migrations.DeleteModel(
            name='Allies',
        ),
        migrations.AddField(
            model_name='bookallies',
            name='bookally_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.BookAlly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyresources',
            name='resource',
            field=models.ForeignKey(help_text='Manage resources through snippets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.Resource'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='resource',
            field=models.ForeignKey(help_text='Manage resources through snippets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.Resource'),
        ),
    ]
