# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('books', '0011_book_table_of_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='student_handbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
