# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_student_handbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False),
        ),
    ]
