# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20160316_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='errata_link',
            field=models.URLField(blank=True, help_text='Link to openstaxcollege.org errata'),
        ),
    ]
