# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_errata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='errata_corrections_link',
            field=models.URLField(blank=True, help_text='Link errata corrections'),
        ),
        migrations.AlterField(
            model_name='book',
            name='errata_link',
            field=models.URLField(blank=True, help_text='Link to view openstaxcollege.org errata'),
        ),
    ]
