# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20160328_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='license_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
