# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20160407_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ibook_link_volume_2',
            field=models.URLField(blank=True, help_text='Link to secondary iBook'),
        ),
    ]
