# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 02:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20160419_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
