# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20160421_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='student_handbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
