# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=wagtail.wagtailcore.fields.StreamField((('author', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('university', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('country', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('senior_author', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('display_at_top', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))),), blank=True, null=True),
        ),
    ]
