# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20160815_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
