# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20160901_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
