# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20161025_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='salesforce_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='salesforce_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
