# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20161026_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='bookstore_coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
