# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_book_tutor_marketing_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_10',
            new_name='print_isbn_10',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn_13',
            new_name='print_isbn_13',
        ),
        migrations.AddField(
            model_name='book',
            name='digital_isbn_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='digital_isbn_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ibook_isbn_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ibook_isbn_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
