# Generated by Django 2.0.2 on 2018-04-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('books', '0039_auto_20180301_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ally_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ally_header',
            field=models.CharField(default='Want more?', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='community_resources_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='community_resources_feature_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='comp_copy_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Deep Green', 'Deep Green'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Light Gray', 'Light Gray'), ('Medium Blue', 'Medium Blue'), ('Orange', 'Orange'), ('Red', 'Red'), ('Yellow', 'Yellow')], default='Blue', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='errata_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='free_stuff_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='free_stuff_heading',
            field=models.CharField(default='Free stuff. No catch.', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='reverse_gradient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='book',
            name='webinar_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='webinar_heading',
            field=models.CharField(blank=True, default='Find a webinar', max_length=255),
        ),
    ]
