# Generated by Django 2.0.2 on 2018-04-05 19:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_auto_20180405_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSharedContents',
            fields=[
                ('booksharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.BookSharedContent')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('books.booksharedcontent', models.Model),
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_ally',
            new_name='ally_content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='comp_copy',
            new_name='comp_copy_content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_errata',
            new_name='errata_content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='webinar',
            new_name='webinar_content',
        ),
        migrations.AddField(
            model_name='booksharedcontents',
            name='book_shared_content',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shared_content', to='books.Book'),
        ),
    ]
