# Generated by Django 2.0.2 on 2018-04-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_auto_20180406_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcommunityresources',
            name='book_community_resource',
        ),
        migrations.RemoveField(
            model_name='bookcommunityresources',
            name='communityresource_ptr',
        ),
        migrations.DeleteModel(
            name='BookCommunityResources',
        ),
    ]
