# Generated by Django 2.0.2 on 2018-04-06 15:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0050_auto_20180406_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCommunityResources',
            fields=[
                ('communityresources_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.CommunityResources')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('book_community_resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_community_resources', to='books.Book')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('books.communityresources', models.Model),
        ),
    ]
