# Generated by Django 2.0.2 on 2018-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0056_auto_20180711_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='deprecated',
        ),
        migrations.AddField(
            model_name='book',
            name='book_state',
            field=models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='live', max_length=255),
        ),
    ]
