# Generated by Django 2.0.2 on 2018-08-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20180801_1719'),
        ('books', '0058_remove_book_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.Subject'),
        ),
    ]
