# Generated by Django 2.0.9 on 2018-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0060_auto_20180920_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chegg_link',
            field=models.URLField(blank=True, help_text='Link to Chegg e-reader', null=True),
        ),
    ]
