# Generated by Django 2.0.9 on 2019-02-20 14:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('books', '0062_book_chegg_link_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubjects',
            fields=[
                ('subjectbooks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.SubjectBooks')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('book_subject', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_subjects', to='books.Book')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('books.subjectbooks', models.Model),
        ),
        migrations.AddField(
            model_name='subjectbooks',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_subject', to='snippets.Subject'),
        ),
    ]
