# Generated by Django 2.0.13 on 2019-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0063_auto_20190220_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
    ]
