# Generated by Django 2.0.13 on 2019-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0064_remove_book_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover_text_color',
            field=models.CharField(choices=[('yellow', 'yellow'), ('light_blue', 'light_blue'), ('dark_blue', 'dark_blue'), ('green', 'green'), ('white', 'white'), ('grey', 'grey'), ('red', 'red'), ('white_red', 'white_red'), ('white_blue', 'white_blue'), ('green_white', 'green_white'), ('yellow_white', 'yellow_white'), ('grey_white', 'grey_white'), ('white_grey', 'white_grey'), ('white_orange', 'white_orange')], default='yellow', max_length=255),
        ),
    ]
