# Generated by Django 2.0.13 on 2019-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0065_book_book_cover_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_text_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('light_blue', 'Light Blue'), ('dark_blue', 'Dark Blue'), ('green', 'Green'), ('white', 'White'), ('grey', 'Grey'), ('red', 'Red'), ('white_red', 'White/Red'), ('white_blue', 'White/Blue'), ('green_white', 'Green/White'), ('yellow_white', 'Yellow/White'), ('grey_white', 'Grey/White'), ('white_grey', 'White/Grey'), ('white_orange', 'White/Orange')], default='yellow', help_text='Use by the Unified team - this will not change the text color on the book cover.', max_length=255),
        ),
    ]
