# Generated by Django 2.0.13 on 2019-07-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0066_auto_20190515_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresources',
            name='link_document',
            field=models.ForeignKey(blank=True, help_text='Or select a document for viewers to download.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='studentresources',
            name='link_external',
            field=models.URLField(blank=True, help_text='Provide an external URL starting with http://.', verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='studentresources',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Or select an existing page to attach.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
