# Generated by Django 2.0.13 on 2019-07-10 18:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0067_auto_20190710_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the university/institution.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='display_at_top',
            field=models.BooleanField(default=False, help_text='Whether display the author on top.'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(help_text='Full name of the author.', max_length=255),
        ),
        migrations.AlterField(
            model_name='authors',
            name='senior_author',
            field=models.BooleanField(default=False, help_text='Whether the author is a senior author. (Senior authors are shown before non-senior authors.)'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='university',
            field=models.CharField(blank=True, help_text='Name of the university/institution the author is associated with.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Full name of the author.', required=True)), ('university', wagtail.core.blocks.CharBlock(help_text='Name of the university/institution the author is associated with.', required=False)), ('country', wagtail.core.blocks.CharBlock(help_text='Country of the university/institution.', required=False)), ('senior_author', wagtail.core.blocks.BooleanBlock(help_text='Whether the author is a senior author. (Senior authors are shown before non-senior authors.)', required=False)), ('display_at_top', wagtail.core.blocks.BooleanBlock(help_text='Whether display the author on top.', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresources',
            name='link_external',
            field=models.URLField(blank=True, help_text='Provide an external URL starting with http:// (or fill out either one of the following two).', verbose_name='External link'),
        ),
    ]
