# Generated by Django 2.0.13 on 2019-07-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0069_auto_20190710_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_state',
            field=models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='live', help_text='The state of the book.', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='The book cover to be shown on the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('deep-green', 'Deep Green'), ('gold', 'Gold'), ('gray', 'Gray'), ('green', 'Green'), ('light-blue', 'Light Blue'), ('light-gray', 'Light Gray'), ('medium-blue', 'Medium Blue'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='blue', help_text='The color of the cover.', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='digital_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for digital version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='digital_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for digital version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ibook_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for iBook version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ibook_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for iBook version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ibook_volume_2_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for iBook v2 version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ibook_volume_2_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for iBook v2 version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_ap',
            field=models.BooleanField(default=False, help_text='Whether this book is an AP (Advanced Placement) book.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for print version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for print version.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, help_text='Date the book is published on.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_image',
            field=models.ForeignKey(blank=True, help_text='The svg for title image to be shown on the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
