# Generated by Django 2.0.13 on 2019-07-10 20:04

import books.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import snippets.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0070_auto_20190710_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_coming_soon',
            field=models.BooleanField(default=False, help_text='Whether this book is coming to Amazon bookstore.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookstore_coming_soon',
            field=models.BooleanField(default=False, help_text='Whether this book is coming to bookstore soon.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookstore_content',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, help_text='Bookstore content.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='chegg_link_text',
            field=models.CharField(blank=True, help_text='Text for Chegg link.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_blurb',
            field=models.TextField(blank=True, help_text='Blurb.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_cta',
            field=models.CharField(blank=True, help_text='Call the action text.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_feature_link',
            field=models.ForeignKey(blank=True, help_text='Document of the community resource feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_feature_text',
            field=models.TextField(blank=True, help_text='Text of the community resource feature.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_heading',
            field=models.CharField(blank=True, help_text='Snipped to show texts for community resources.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_logo',
            field=models.ForeignKey(blank=True, help_text='Logo for community resources.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='community_resource_url',
            field=models.URLField(blank=True, help_text='URL of the external source.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comp_copy_available',
            field=models.BooleanField(default=True, help_text='Whether free compy available for teachers.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comp_copy_content',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, help_text='Content of the free copy.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='errata_content',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, help_text='Errata content.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='free_stuff_instructor',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, help_text='Snippet to show texts for free instructor resources.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='free_stuff_student',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, help_text='Snipped to show texts for free student resources.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='high_resolution_pdf',
            field=models.ForeignKey(blank=True, help_text='High quality PDF document of the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_name',
            field=models.CharField(blank=True, editable=False, help_text='Name of the license.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_url',
            field=models.CharField(blank=True, editable=False, help_text='External URL of the license.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_version',
            field=models.CharField(blank=True, editable=False, help_text='Version of the license.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='low_resolution_pdf',
            field=models.ForeignKey(blank=True, help_text='Low quality PDF document of the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='promote_image',
            field=models.ForeignKey(blank=True, help_text='Promote image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='TOC.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tutor_marketing_book',
            field=models.BooleanField(default=False, help_text='Whether this is a Tutor marketing book.'),
        ),
    ]
