# Generated by Django 2.0.13 on 2019-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0072_book_webview_rex_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_updated_pdf',
            field=models.DateTimeField(blank=True, help_text='Last time PDF is updated. This field is NOT managed by CMS.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_updated_web',
            field=models.DateTimeField(blank=True, help_text='Last time webview is updated. This field is automatically managed by CMS.', null=True),
        ),
    ]
