# Generated by Django 2.0.13 on 2019-07-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0072_book_webview_rex_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_price_softcover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='book',
            name='print_softcover_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for print version (softcover).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='print_softcover_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for print version (softcover).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10 for print version (hardcover).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13 for print version (hardcover).', max_length=255, null=True),
        ),
    ]
