# Generated by Django 2.0.13 on 2019-08-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0073_auto_20190730_1153'),
        ('books', '0073_auto_20190730_1437'),
    ]

    operations = [
    ]
