# Generated by Django 2.0.13 on 2019-08-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0075_book_study_edge_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='study_edge_link',
            field=models.URLField(blank=True, help_text='Link to Study Edge app. This will cause the link to appear on the book details page.', null=True),
        ),
    ]
