# Generated by Django 2.0.13 on 2019-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0076_auto_20190805_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='study_edge_link',
        ),
        migrations.AddField(
            model_name='book',
            name='enable_study_edge',
            field=models.BooleanField(default=False, help_text='This will cause the link to the Study Edge app appear on the book details page.'),
        ),
    ]
