# Generated by Django 2.0.13 on 2019-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0077_auto_20190806_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rex_callout_blurb',
            field=models.CharField(blank=True, help_text='Additional text for the REX callout.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rex_callout_title',
            field=models.CharField(blank=True, default='Recommended', help_text='Title of the REX callout', max_length=255, null=True),
        ),
    ]
