# Generated by Django 2.2.5 on 2019-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0078_auto_20190916_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresources',
            name='coming_soon_text',
            field=models.CharField(blank=True, help_text='If there is text in this field a coming soon banner will be added with this description.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='coming_soon_text',
            field=models.CharField(blank=True, help_text='If there is text in this field a coming soon banner will be added with this description.', max_length=255, null=True),
        ),
    ]
