# Generated by Django 2.2.5 on 2019-09-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0078_auto_20190916_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='table_of_contents',
        ),
    ]
