# Generated by Django 2.2.8 on 2020-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0083_auto_20191113_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookally',
            name='ally',
        ),
        migrations.AlterField(
            model_name='book',
            name='last_updated_pdf',
            field=models.DateTimeField(blank=True, help_text='Last time PDF was revised.', null=True, verbose_name='PDF Content Revision Date'),
        ),
        migrations.DeleteModel(
            name='BookAllies',
        ),
        migrations.DeleteModel(
            name='BookAlly',
        ),
    ]
