# Generated by Django 2.2.8 on 2020-02-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0084_auto_20200210_1041'),
        ('books', '0084_auto_20200203_1638'),
    ]

    operations = [
    ]
