# Generated by Django 2.2.8 on 2020-02-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0085_merge_20200210_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='amazon_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='amazon_price_softcover',
        ),
        migrations.AlterField(
            model_name='book',
            name='partner_list_label',
            field=models.CharField(blank=True, help_text='Controls the heading text on the book detail page for partners. This will update ALL books to use this value!', max_length=255, null=True),
        ),
    ]
