# Generated by Django 2.2.8 on 2020-02-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0084_auto_20200213_1156'),
        ('books', '0086_auto_20200211_0906'),
    ]

    operations = [
    ]