# Generated by Django 2.2.8 on 2020-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0086_auto_20200211_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='partner_page_link_text',
            field=models.CharField(blank=True, help_text='Link to partners page on top right of list.', max_length=255, null=True),
        ),
    ]
