# Generated by Django 2.2.10 on 2020-03-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0087_book_partner_page_link_text'),
        ('books', '0087_merge_20200213_1202'),
    ]

    operations = [
    ]