# Generated by Django 3.0.4 on 2020-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0090_auto_20200310_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured_resources_header',
            field=models.CharField(blank=True, help_text='Featured resource header on instructor resources tab.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultyresources',
            name='featured',
            field=models.BooleanField(default=False, help_text='Add to featured bar on resource page'),
        ),
    ]
