# Generated by Django 3.0.4 on 2020-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0095_book_use_alt_errata_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='use_alt_errata_schedule',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_state',
            field=models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon'), ('new_edition_available', 'New Edition Available (Show new edition correction schedule)'), ('deprecated', 'Deprecated (Disallow errata submissions and show deprecated schedule)'), ('retired', 'Retired (Remove from website)')], default='live', help_text='The state of the book.', max_length=255),
        ),
    ]
