# Generated by Django 3.0.4 on 2020-07-10 14:36

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0098_auto_20200710_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFacultyResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_heading', models.CharField(max_length=255)),
                ('resource_description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='resource_videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='facultyresources',
            name='video_url',
        ),
    ]
