# Generated by Django 3.0.4 on 2020-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200720_1527'),
        ('books', '0102_auto_20200716_1605'),
    ]

    operations = [
    ]
