# Generated by Django 3.0.4 on 2020-07-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0102_auto_20200716_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyresources',
            name='link_text',
            field=models.CharField(help_text='Call to Action Text', max_length=255),
        ),
    ]
