# Generated by Django 3.0.4 on 2020-07-22 21:13

import books.models
from django.db import migrations
import snippets.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0103_auto_20200722_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='give_today',
            field=wagtail.core.fields.StreamField([('content', books.models.SharedContentChooserBlock(snippets.models.SharedContent))], blank=True, help_text='Give link text and url.', null=True),
        ),
    ]
