# Generated by Django 3.0.4 on 2020-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0107_auto_20200813_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresources',
            name='print_link',
            field=models.URLField(blank=True, help_text='Link for Buy Print link on resource', null=True),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='print_link',
            field=models.URLField(blank=True, help_text='Link for Buy Print link on resource', null=True),
        ),
    ]
