# Generated by Django 3.0.4 on 2020-09-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0108_auto_20200910_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='give_today',
        ),
    ]
