# Generated by Django 3.0.4 on 2020-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0108_auto_20200910_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('number_of_students', models.IntegerField()),
                ('why', models.TextField()),
                ('modules', models.TextField()),
            ],
        ),
    ]
