# Generated by Django 3.0.4 on 2020-09-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0110_customizationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizationForm',
        ),
    ]
