# Generated by Django 3.0.4 on 2020-09-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0109_remove_book_give_today'),
        ('books', '0112_delete_customizationrequest'),
    ]

    operations = [
    ]
