# Generated by Django 3.0.4 on 2020-09-30 16:54

import books.models
from django.db import migrations
import snippets.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0113_merge_20200930_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='customization_form_content',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
    ]
