# Generated by Django 3.0.4 on 2020-09-30 17:05

import books.models
from django.db import migrations
import snippets.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0114_book_customization_form_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='customization_form_content',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
    ]
