# Generated by Django 3.0.4 on 2020-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0116_auto_20200930_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_coming_soon',
            field=models.BooleanField(default=False, verbose_name='Individual Print Coming Soon'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, verbose_name='Individual Print Link'),
        ),
    ]
