# Generated by Django 3.0.4 on 2020-10-14 17:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0117_auto_20201002_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookindex',
            name='dev_standard_4_description',
            field=wagtail.core.fields.RichTextField(default='With philanthropic support, our books have been used in <span id="adoption_number"></span> classrooms, savings students <span id="savings"></span> dollars this School year.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookindex',
            name='dev_standard_4_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
