# Generated by Django 3.0.4 on 2020-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0118_auto_20201014_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookindex',
            name='dev_standard_4_description',
            field=models.TextField(),
        ),
    ]
