# Generated by Django 3.0.4 on 2020-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0119_auto_20201014_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookindex',
            name='dev_standard_4_description',
            field=models.TextField(help_text='Keep <span> in place to populate with Salesforce data. id=adoption_number for classrooms and id=savings for savings number.'),
        ),
    ]
