# Generated by Django 3.0.4 on 2020-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0122_auto_20201021_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='support_statement',
            field=models.TextField(blank=True, default="With philanthropic support, this book is used in <span id='adoption_number'></span> classrooms, saving students <span id='savings'></span> dollars this school year. <a href='/impact'>Learn more about our impact</a> and how you can help.", null=True),
        ),
    ]
