# Generated by Django 3.0.4 on 2020-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0123_book_support_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='support_statement',
            field=models.TextField(blank=True, default="With philanthropic support, this book is used in <span id='adoption_number'></span> classrooms, saving students <span id='savings'></span> dollars this school year. <a href='/impact'>Learn more about our impact</a> and how you can help.", help_text='Updating this statement updates it for all book pages.', null=True),
        ),
    ]
