# Generated by Django 3.0.4 on 2020-11-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0124_auto_20201021_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='table_of_contents',
        ),
    ]
