# Generated by Django 3.2.4 on 2021-07-22 20:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0130_remove_book_errata_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translations',
            field=wagtail.core.fields.StreamField([('translation', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('locale', wagtail.core.blocks.CharBlock()), ('slug', wagtail.core.blocks.CharBlock())])))], blank=True, null=True),
        ),
    ]
