# Generated by Django 3.2.9 on 2022-02-02 19:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_subject_icon'),
        ('books', '0132_bookindex_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_subjectcategory', to='snippets.subjectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('bookcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.bookcategory')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('book_category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='books.book')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('books.bookcategory', models.Model),
        ),
    ]
