# Generated by Django 3.2.5 on 2022-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0135_alter_book_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='salesforce_book_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesforce Book Id (if blank, adoptions are not tracked)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='salesforce_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='salesforce_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
