# Generated by Django 4.0.8 on 2023-01-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0138_alter_book_authors_alter_book_bookstore_content_and_more'),
        ('books', '0139_auto_20230112_1426'),
    ]

    operations = [
    ]
