# Generated by Django 4.0.8 on 2023-02-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('books', '0140_merge_20230118_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='k12_subject',
        ),
        migrations.AddField(
            model_name='facultyresources',
            name='resource_icon',
            field=models.ForeignKey(blank=True, help_text='Icon for K12 resources listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='k12',
            field=models.BooleanField(default=False, help_text='Add to K12 student resources.'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='resource_icon',
            field=models.ForeignKey(blank=True, help_text='Icon for K12 resources listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
