# Generated by Django 4.0.8 on 2023-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0140_merge_20230118_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='k12_subject',
        ),
        migrations.AddField(
            model_name='studentresources',
            name='k12',
            field=models.BooleanField(default=False, help_text='Add to K12 student resources.'),
        ),
    ]
