# Generated by Django 4.0.8 on 2023-03-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0142_remove_book_digital_isbn_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresources',
            name='k12',
        ),
        migrations.AddField(
            model_name='facultyresources',
            name='display_on_k12',
            field=models.BooleanField(default=False, help_text='Display resource on K12 subject pages'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='display_on_k12',
            field=models.BooleanField(default=False, help_text='Display resource on K12 subject pages'),
        ),
    ]
