# Generated by Django 4.1.7 on 2023-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0149_alter_book_book_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_iframe',
            field=models.TextField(blank=True, help_text='Amazon iframe code block', null=True),
        ),
    ]
