# Generated by Django 4.2.8 on 2024-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0152_alter_book_promote_snippet_delete_promotesnippets"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="polish_site_link",
            field=models.URLField(
                blank=True,
                help_text="Stores target URL to the Polish site so that REX Polish page headers lead back to each individual book on the Polish site",
                null=True,
            ),
        ),
    ]
