# Generated by Django 5.0.2 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0153_book_polish_site_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="salesforce_abbreviation",
            field=models.CharField(
                blank=True,
                help_text="This should match the Books Name from Salesforce.",
                max_length=255,
                null=True,
                verbose_name="Subject Book Name",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="salesforce_name",
            field=models.CharField(
                blank=True,
                help_text="This is the name shown on interest/adoption forms and used in Partner filtering. The website only shows unique values from here, so it is possible to combine books for forms",
                max_length=255,
                null=True,
                verbose_name="Name displayed on website forms",
            ),
        ),
    ]
