# Generated by Django 5.0.2 on 2024-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0154_alter_book_salesforce_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover_text_color",
            field=models.CharField(
                choices=[
                    ("yellow", "Yellow"),
                    ("light_blue", "Light Blue"),
                    ("dark_blue", "Dark Blue"),
                    ("midnight", "Midnight"),
                    ("green", "Green"),
                    ("white", "White"),
                    ("grey", "Grey"),
                    ("red", "Red"),
                    ("white_red", "White/Red"),
                    ("white_blue", "White/Blue"),
                    ("green_white", "Green/White"),
                    ("yellow_white", "Yellow/White"),
                    ("grey_white", "Grey/White"),
                    ("white_grey", "White/Grey"),
                    ("white_orange", "White/Orange"),
                ],
                default="yellow",
                help_text="Use by the Unified team - this will not change the text color on the book cover.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("midnight", "Midnight"),
                    ("deep-green", "Deep Green"),
                    ("gold", "Gold"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("light-blue", "Light Blue"),
                    ("light-gray", "Light Gray"),
                    ("medium-blue", "Medium Blue"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                ],
                default="blue",
                help_text="The color of the cover.",
                max_length=255,
            ),
        ),
    ]
