# Generated by Django 5.0.6 on 2024-06-26 16:58

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("books", "0155_alter_book_book_cover_text_color_and_more"),
        ("snippets", "0036_contentwarning"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content_warning",
            field=models.ForeignKey(
                blank=True,
                help_text="Message shown in the content warning modal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_warnings_content_warning",
                to="snippets.contentwarning",
            ),
        ),
    ]
