# Generated by Django 5.0.12 on 2025-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0157_alter_book_print_isbn_13_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("midnight", "Midnight"),
                    ("deep-green", "Deep Green"),
                    ("gold", "Gold"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("light-blue", "Light Blue"),
                    ("light-gray", "Light Gray"),
                    ("medium-blue", "Medium Blue"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("raise-green", "Raise Green"),
                ],
                default="blue",
                help_text="The color of the cover.",
                max_length=255,
            ),
        ),
    ]
