# Generated by Django 5.1.13 on 2025-10-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0159_book_assignable_isbn_13"),
        ("snippets", "0044_requireloginmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="require_login_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Message shown to logged-out users requiring them to log in. If set, logged-out users cannot dismiss content warning and must log in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_require_login_message",
                to="snippets.requireloginmessage",
            ),
        ),
    ]
