# Generated by Django 4.2.8 on 2026-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0160_book_require_login_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="audiobook_link",
            field=models.URLField(blank=True, verbose_name="Audiobook Link"),
        ),
    ]
