# Generated by Django 5.1.15 on 2026-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0161_book_audiobook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresources',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this resource from the live book page'),
        ),
        migrations.AddField(
            model_name='studentresources',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this resource from the live book page'),
        ),
    ]
