# Generated by Django 5.2.12 on 2026-06-09 22:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0163_bookrelatedpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="videos",
            field=wagtail.fields.StreamField(
                [("video", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("embed", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                },
                null=True,
            ),
        ),
    ]
