# Generated by Django 5.2.12 on 2026-06-29 14:56

from django.db import migrations, models


def backfill_book_uuid(apps, schema_editor):
    # cnx_id is the currently-populated side; make book_uuid canonical by
    # backfilling it from cnx_id wherever book_uuid is empty.
    Book = apps.get_model("books", "Book")
    for book in Book.objects.exclude(cnx_id__isnull=True).exclude(cnx_id=""):
        if not book.book_uuid:
            book.book_uuid = book.cnx_id
            book.save(update_fields=["book_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0164_alter_book_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_uuid",
            field=models.CharField(
                blank=True,
                help_text="collection.xml UUID for the book. Canonical book identifier.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cnx_id",
            field=models.CharField(
                blank=True,
                help_text="Legacy alias of book_uuid, kept for API back-compat. Auto-synced from book_uuid; do not edit.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_book_uuid, migrations.RunPython.noop),
    ]
