# Generated by Django 5.2.12 on 2026-06-29 16:27

import django.db.models.deletion
import snippets.models
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0168_remove_book_chegg_link_remove_book_chegg_link_text_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCallout",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "rex_callout_title",
                    models.CharField(
                        blank=True,
                        default="Recommended",
                        help_text="Title of the REX callout (shared across all books).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rex_callout_blurb",
                    models.CharField(
                        blank=True,
                        help_text="Additional text for the REX callout (shared across all books).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "webinar_content",
                    wagtail.fields.StreamField(
                        [("content", 0), ("link", 1), ("link_text", 2)],
                        blank=True,
                        block_lookup={
                            0: ("books.models.SharedContentChooserBlock", (snippets.models.SharedContent,), {}),
                            1: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                        },
                        null=True,
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book callout",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
