# Generated by Django 5.2.12 on 2026-06-29 16:31

from django.db import migrations


def seed_book_callout(apps, schema_editor):
    # Seed one BookCallout per locale from existing (identical) per-book values,
    # taking the first book per locale, before the per-book columns are dropped.
    Book = apps.get_model("books", "Book")
    BookCallout = apps.get_model("books", "BookCallout")
    seen_locales = set()
    for book in Book.objects.all().order_by("id").iterator():
        if book.locale_id in seen_locales:
            continue
        if not BookCallout.objects.filter(locale_id=book.locale_id).exists():
            BookCallout.objects.create(
                locale_id=book.locale_id,
                rex_callout_title=book.rex_callout_title or "Recommended",
                rex_callout_blurb=book.rex_callout_blurb,
                webinar_content=book.webinar_content,
            )
        seen_locales.add(book.locale_id)


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0169_bookcallout"),
    ]

    operations = [
        migrations.RunPython(seed_book_callout, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="book",
            name="rex_callout_blurb",
        ),
        migrations.RemoveField(
            model_name="book",
            name="rex_callout_title",
        ),
        migrations.RemoveField(
            model_name="book",
            name="webinar_content",
        ),
    ]
