# Generated by Django 5.2.12 on 2026-06-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0170_remove_book_rex_callout_blurb_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The title image (banner) shown on the website. SVG supported.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Title image (banner)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The book cover shown on the website.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Cover image",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                help_text='Legacy Document cover (being migrated to "Cover image").',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_image",
            field=models.ForeignKey(
                blank=True,
                help_text='Legacy Document title image (being migrated to "Banner image").',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
