# Generated by Django 6.0.6 on 2026-08-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0173_alter_book_salesforce_abbreviation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orientationfacultyresource",
            name="creator_fest_resource",
        ),
    ]
