# Generated by Django 6.0.6 on 2026-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0174_remove_orientationfacultyresource_creator_fest_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="remediation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed (remediated)"),
                    ("in_progress", "In Progress (being remediated)"),
                    ("deprecated", "Deprecated (temporarily removed)"),
                    ("removed", "Removed (will not return)"),
                    ("na", "N/A (already accessible)"),
                ],
                default="",
                help_text="Accessibility remediation status of this book's Web PDF, published on the Accessibility Hub. Leave blank to keep it off the hub.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facultyresources",
            name="remediation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed (remediated)"),
                    ("in_progress", "In Progress (being remediated)"),
                    ("deprecated", "Deprecated (temporarily removed)"),
                    ("removed", "Removed (will not return)"),
                    ("na", "N/A (already accessible)"),
                ],
                default="",
                help_text="Accessibility remediation status for this book's copy of the resource, published on the Accessibility Hub. Leave blank to keep it off the hub.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentresources",
            name="remediation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed (remediated)"),
                    ("in_progress", "In Progress (being remediated)"),
                    ("deprecated", "Deprecated (temporarily removed)"),
                    ("removed", "Removed (will not return)"),
                    ("na", "N/A (already accessible)"),
                ],
                default="",
                help_text="Accessibility remediation status for this book's copy of the resource, published on the Accessibility Hub. Leave blank to keep it off the hub.",
                max_length=20,
            ),
        ),
    ]
