# Generated by Django 6.0.6 on 2026-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0175_book_remediation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofacultyresource",
            name="remediation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed (remediated)"),
                    ("in_progress", "In Progress (being remediated)"),
                    ("deprecated", "Deprecated (temporarily removed)"),
                    ("removed", "Removed (will not return)"),
                    ("na", "N/A (already accessible)"),
                ],
                default="",
                help_text="Accessibility remediation status for this book's copy of the resource, published on the Accessibility Hub. Leave blank to keep it off the hub.",
                max_length=20,
            ),
        ),
    ]
