# Generated by Django 3.0.4 on 2020-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200923_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationrequest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
