# Generated by Django 3.0.4 on 2021-01-14 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customizationrequest_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
