# Generated by Django 3.2.5 on 2022-02-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_featureflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
