# Generated by Django 3.2.5 on 2022-02-03 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_featureflag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featureflag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
