# Generated by Django 3.2.5 on 2022-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220203_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(help_text='Create flag names with underscores to be more machine friendly. Eg. awesome_feature', max_length=255, unique=True),
        ),
    ]
