# Generated by Django 3.0.4 on 2020-09-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200928_1405'),
        ('pages', '0002_auto_20200813_1540'),
    ]

    operations = [
    ]
