# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160504_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducation',
            name='allies_description',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='allies_heading',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='cnx_description',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='cnx_heading',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='get_started_step_4_description',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='our_books_description',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='our_books_heading',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='our_impact_description',
        ),
        migrations.RemoveField(
            model_name='highereducation',
            name='our_impact_heading',
        ),
        migrations.AddField(
            model_name='highereducation',
            name='adopt_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='adopt_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='adopt_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_1_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_1_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_1_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_2_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_2_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_2_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_3_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_3_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_3_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_4_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_4_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_4_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_5_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_5_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_5_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_1_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_1_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_2_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_2_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_3_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_3_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
