# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='organization_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='organizations',
            name='salesforce_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
