# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160317_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adopters',
            new_name='AdoptersPages',
        ),
    ]
