# Generated by Django 3.0.4 on 2020-11-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('pages', '0003_merge_20200930_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLPHPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('signup_link_href', models.URLField()),
                ('signup_link_text', models.CharField(max_length=255)),
                ('book_heading', models.CharField(max_length=255)),
                ('book_description', models.TextField()),
                ('book_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
