# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160506_1151'),
        ('pages', '0003_auto_20160505_1210'),
    ]

    operations = [
    ]
