# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('pages', '0003_auto_20160505_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducation',
            name='box_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_1_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_3_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_4_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_4_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_5_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='box_5_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
