# Generated by Django 3.0.4 on 2020-11-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('pages', '0004_llphpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llphpage',
            options={'verbose_name': 'LLPH Page'},
        ),
        migrations.AddField(
            model_name='llphpage',
            name='hero_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='llphpage',
            name='info_link_slug',
            field=models.CharField(default='/details/books/life-liberty-and-pursuit-happiness', max_length=255),
        ),
        migrations.AddField(
            model_name='llphpage',
            name='info_link_text',
            field=models.CharField(default='Not an educator? Take a look at the book here.', max_length=255),
        ),
        migrations.AlterField(
            model_name='llphpage',
            name='book_description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
