# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160317_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Adopters',
        ),
    ]
