# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160526_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_1_cta',
            new_name='row_1_box_1_cta',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_1_description',
            new_name='row_1_box_1_description',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_1_heading',
            new_name='row_1_box_1_heading',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_1_image',
            new_name='row_1_box_1_image',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_1_link',
            new_name='row_1_box_1_link',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_2_cta',
            new_name='row_1_box_2_cta',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_2_description',
            new_name='row_1_box_2_description',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_2_heading',
            new_name='row_1_box_2_heading',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_2_image',
            new_name='row_1_box_2_image',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_2_link',
            new_name='row_1_box_2_link',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_3_cta',
            new_name='row_1_box_3_cta',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_3_description',
            new_name='row_1_box_3_description',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_3_heading',
            new_name='row_1_box_3_heading',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_3_image',
            new_name='row_1_box_3_image',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_1_3_link',
            new_name='row_1_box_3_link',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_1_cta',
            new_name='row_2_box_1_cta',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_1_description',
            new_name='row_2_box_1_description',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_1_heading',
            new_name='row_2_box_1_heading',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_1_link',
            new_name='row_2_box_1_link',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_2_cta',
            new_name='row_2_box_2_cta',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_2_description',
            new_name='row_2_box_2_description',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_2_heading',
            new_name='row_2_box_2_heading',
        ),
        migrations.RenameField(
            model_name='highereducation',
            old_name='box_2_2_link',
            new_name='row_2_box_2_link',
        ),
    ]
