# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('pages', '0008_auto_20160526_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_1_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_1_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_2_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_2_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_3_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='row_0_box_3_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], max_length=1, null=True),
        ),
    ]
