# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160526_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducation',
            name='row_0_box_1_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='row_0_box_2_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='row_0_box_3_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
    ]
