# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('pages', '0012_openstaxteam_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagequotes',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='homepagequotes',
            name='quote_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='adopter_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='adopter_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='adopter_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='adopter_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='give_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='give_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='give_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='give_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_2_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='higher_ed_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='higher_ed_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='k12_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='k12_heading',
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_1_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_1_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_1_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_1_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_2_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_2_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_2_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_3_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_3_cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_3_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_0_box_3_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_1_box_1_line_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_1_box_1_line_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_1_box_1_line_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_2_box_1_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_2_box_1_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_2_box_2_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_2_box_2_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_3_box_1_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_3_box_1_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_3_box_1_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_4_box_1_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_4_box_1_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='row_4_box_1_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomePageQuotes',
        ),
    ]
