# Generated by Django 3.0.4 on 2020-12-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('pages', '0012_auto_20201204_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingvideolink',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='marketingvideos',
            name='marketing_video',
        ),
        migrations.RemoveField(
            model_name='marketingvideos',
            name='marketingvideolink_ptr',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='available_image',
        ),
        migrations.RemoveField(
            model_name='resourceavailability',
            name='marketing_video',
        ),
        migrations.RemoveField(
            model_name='resourceavailability',
            name='resource_ptr',
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
        migrations.DeleteModel(
            name='MarketingVideoLink',
        ),
        migrations.DeleteModel(
            name='MarketingVideos',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceAvailability',
        ),
    ]
