# Generated by Django 3.0.4 on 2020-12-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('pages', '0013_auto_20201204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormarketing',
            name='feedback_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
