# Generated by Django 3.0.4 on 2020-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_image_alignment',
            field=models.CharField(blank=True, choices=[('L', 'left'), ('R', 'right'), ('F', 'full')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_link_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
