# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('pages', '0023_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='page',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='adopter',
            new_name='adopter_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='allies',
            new_name='allies_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='give_to_openstax',
            new_name='give_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='wwd_higher_ed',
            new_name='higher_ed_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='wwd_higher_ed_heading',
            new_name='higher_ed_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='wwd_12',
            new_name='k12_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='wwd_k12_heading',
            new_name='k12_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_us_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='ap_disclaimer',
        ),
        migrations.AddField(
            model_name='homepage',
            name='adopter_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='adopter_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='allies_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='allies_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='give_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='give_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_2_text',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_1_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_1_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_1_quote',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_2_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_2_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_2_quote',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_3_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_3_cta_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_3_quote',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='HomePageRelatedLink',
        ),
    ]
