# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20160107_1342'),
        ('pages', '0024_auto_20160111_1714'),
    ]

    operations = [
    ]
