# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20160112_1528'),
        ('pages', '0026_auto_20160112_1608'),
    ]

    operations = [
    ]
