# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('pages', '0029_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', wagtail.wagtailcore.fields.RichTextField()),
                ('quote_image_alignment', models.CharField(choices=[('L', 'Left Aligned'), ('R', 'Right Aligned'), ('F', 'Full Width')], default='F', max_length=1)),
                ('quote_link', models.URLField(blank=True)),
                ('quote_link_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_1_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_1_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_1_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_1_image_alignment',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_1_quote',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_2_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_2_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_2_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_2_image_alignment',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_2_quote',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_3_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_3_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_3_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_3_image_alignment',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_3_quote',
        ),
        migrations.CreateModel(
            name='HomePageQuotes',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Quote')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quote', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_quotes', to='pages.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('pages.quote', models.Model),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
