# Generated by Django 3.0.4 on 2021-04-26 18:15

from django.db import migrations, models
import news.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20210127_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_images',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mobile_banner_images',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='row_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='row_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='row_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='row_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='row_5',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.core.blocks.StructBlock([('image', news.models.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock()), ('alignment', news.models.ImageFormatChoiceBlock()), ('alt_text', wagtail.core.blocks.CharBlock(required=False))], icon='image', label='Aligned image')), ('pullquote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())])), ('aligned_html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media', label='Embed Media URL'))]),
        ),
    ]
