# Generated by Django 3.0.4 on 2021-05-05 18:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20210427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='quotes',
            field=wagtail.fields.StreamField([('quote', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('testimonial', wagtail.blocks.TextBlock(required=False)), ('author', wagtail.blocks.CharBlock(Required=False))])))]),
        ),
    ]
