# Generated by Django 3.0.4 on 2021-05-06 18:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields



class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20210505_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='tutor_logo_url',
            new_name='tutor_logo',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='whats_openstax_image_url',
            new_name='whats_openstax_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_tab1_features',
            field=wagtail.fields.StreamField([('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=False))])))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_tab2_features',
            field=wagtail.fields.StreamField([('resources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=False))])))]),
        ),
    ]
