# Generated by Django 3.0.4 on 2021-05-06 19:53

from django.db import migrations
import pages.custom_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20210506_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='tutor_features_cards',
        ),
        migrations.AddField(
            model_name='homepage',
            name='tutor_features',
            field=wagtail.fields.StreamField([('features', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', pages.custom_blocks.APIImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False))])))], default=''),
            preserve_default=False,
        ),
    ]
