# Generated by Django 3.2.4 on 2021-06-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20210517_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspage',
            name='partner_ally_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='partner_ally_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='partner_full_partner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='partner_full_partner_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
