# Generated by Django 3.2.5 on 2021-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20211215_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_get_started_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_login_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
