# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20160808_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allies',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='allies',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='highereducationallies',
            name='allies_ptr',
        ),
        migrations.RemoveField(
            model_name='highereducationallies',
            name='page',
        ),
        migrations.DeleteModel(
            name='Allies',
        ),
        migrations.DeleteModel(
            name='HigherEducationAllies',
        ),
    ]
