# Generated by Django 3.2.9 on 2022-02-07 20:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_auto_20220207_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='funder_groups',
            field=wagtail.fields.StreamField([('grouplist', wagtail.blocks.StructBlock([('funders', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('funder_name', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=False))])))]))]),
        ),
    ]
