# Generated by Django 3.2.9 on 2022-02-07 20:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_alter_supporters_funder_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='funder_groups',
            field=wagtail.core.fields.StreamField([('funder_info', wagtail.core.blocks.StructBlock([])), ('grouplist', wagtail.core.blocks.StructBlock([('funders', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('funder_name', wagtail.core.blocks.CharBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=False))])))]))]),
        ),
    ]
