# Generated by Django 3.2.9 on 2022-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_subject_subjectorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='page_description',
            field=models.TextField(default=''),
        ),
    ]
