# Generated by Django 3.2.9 on 2022-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_alter_supporters_funder_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporters',
            name='disclaimer',
            field=models.TextField(default=''),
        ),
    ]
