# Generated by Django 3.2.9 on 2022-02-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_subject_subjectorderable'),
        ('pages', '0055_supporters_disclaimer'),
    ]

    operations = [
    ]
