# Generated by Django 3.2.9 on 2022-02-24 18:50

from django.db import migrations
import pages.custom_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_merge_20220223_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tutor_ad',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('image', pages.custom_blocks.APIImageChooserBlock()), ('ad_html', wagtail.blocks.TextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_href', wagtail.blocks.URLBlock())]))], blank=True, null=True),
        ),
    ]
