# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_remove_funder_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourimpactinstitutions',
            name='funder_ptr',
        ),
        migrations.RemoveField(
            model_name='ourimpactinstitutions',
            name='page',
        ),
        migrations.DeleteModel(
            name='OurImpactInstitutions',
        ),
    ]
