# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('pages', '0057_remove_funder_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_heading', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('other_payment_methods_heading', models.CharField(max_length=255)),
                ('payment_method_1_heading', models.CharField(max_length=255)),
                ('payment_method_1_content', wagtail.wagtailcore.fields.RichTextField()),
                ('payment_method_2_heading', models.CharField(max_length=255)),
                ('payment_method_2_content', wagtail.wagtailcore.fields.RichTextField()),
                ('payment_method_3_heading', models.CharField(max_length=255)),
                ('payment_method_3_content', wagtail.wagtailcore.fields.RichTextField()),
                ('payment_method_4_heading', models.CharField(max_length=255)),
                ('payment_method_4_content', wagtail.wagtailcore.fields.RichTextField()),
                ('give_cta', models.CharField(max_length=255)),
                ('give_cta_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
