# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_auto_20160906_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurImpactInstitutions',
            fields=[
                ('institutions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Institutions')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='pages.OurImpact')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('pages.institutions', models.Model),
        ),
    ]
