# Generated by Django 3.2.9 on 2022-03-01 15:35

from django.db import migrations
import pages.custom_blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_alter_subject_tutor_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='funder_groups',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('group_title', wagtail.core.blocks.CharBlock(form_classname='name of funder group')), ('description', wagtail.core.blocks.TextBlock(form_classname='description of funder group')), ('image', pages.custom_blocks.APIImageChooserBlock(required=False)), ('funders', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('funder_name', wagtail.core.blocks.CharBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=False))])))]))]),
        ),
    ]
