# Generated by Django 3.2.5 on 2022-07-13 18:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('pages', '0063_auto_20220614_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormHeadings',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('adoption_intro_heading', models.CharField(max_length=255)),
                ('adoption_intro_description', wagtail.fields.RichTextField()),
                ('interest_intro_heading', models.CharField(max_length=255)),
                ('interest_intro_description', wagtail.fields.RichTextField()),
                ('promote_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
