# Generated by Django 3.2.5 on 2022-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_formheadings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_categories_heading',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='learn_more_about_books',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='learn_more_blog_posts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='learn_more_heading',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='learn_more_webinars',
            field=models.TextField(default=''),
        ),
    ]
