# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='faq_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
