# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0066_auto_20161018_0810'),
        ('pages', '0066_aboutus_faq_link'),
    ]

    operations = [
    ]
