# Generated by Django 4.0.8 on 2022-12-21 16:49

from django.db import migrations, models
import django.db.models.deletion
import pages.custom_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('pages', '0066_allylogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResearchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mission_header', models.CharField(max_length=255)),
                ('mission_body', models.TextField()),
                ('banner_header', models.TextField(blank=True, default='')),
                ('banner_body', models.TextField(blank=True, default='')),
                ('bannerCTA', models.TextField(blank=True, default='')),
                ('bannerURL', models.URLField(blank=True, default='')),
                ('research_area_header', models.CharField(max_length=255)),
                ('research_area_description_mobile', wagtail.fields.RichTextField(default='', help_text='Research Area Description (Mobile Only)')),
                ('research_areas_list', wagtail.fields.StreamField([('research_area_section', wagtail.blocks.StructBlock([('research_area_title', wagtail.blocks.CharBlock()), ('research_area_blurb', wagtail.blocks.RichTextBlock()), ('research_area_blurb_mobile', wagtail.blocks.RichTextBlock()), ('research_areas', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('short_description', wagtail.blocks.CharBlock(help_text='Short Description (Mobile Only)', label='Short Description (Mobile Only)')), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('cta_text', wagtail.blocks.CharBlock(required=False)), ('cta_link', wagtail.blocks.URLBlock(required=False)), ('publication', wagtail.blocks.URLBlock(required=False)), ('github', wagtail.blocks.URLBlock(required=False))])))]))], default='')),
                ('people_header', models.CharField(max_length=255)),
                ('current_members', wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('long_title', wagtail.blocks.CharBlock(required=False)), ('bio', wagtail.blocks.CharBlock()), ('education', wagtail.blocks.CharBlock(required=False)), ('specialization', wagtail.blocks.CharBlock(required=False)), ('research_interest', wagtail.blocks.CharBlock(required=False)), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('website', wagtail.blocks.URLBlock(required=False)), ('linked_in', wagtail.blocks.URLBlock(required=False)), ('google_scholar', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True)),
                ('collaborating_researchers', wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('long_title', wagtail.blocks.CharBlock(required=False)), ('bio', wagtail.blocks.CharBlock()), ('education', wagtail.blocks.CharBlock(required=False)), ('specialization', wagtail.blocks.CharBlock(required=False)), ('research_interest', wagtail.blocks.CharBlock(required=False)), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('website', wagtail.blocks.URLBlock(required=False)), ('linked_in', wagtail.blocks.URLBlock(required=False)), ('google_scholar', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True)),
                ('alumni', wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('linked_in', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True)),
                ('publication_header', models.CharField(max_length=255)),
                ('publications', wagtail.fields.StreamField([('publication', wagtail.blocks.StructBlock([('authors', wagtail.blocks.CharBlock()), ('date', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('excerpt', wagtail.blocks.CharBlock()), ('pdf', wagtail.blocks.URLBlock()), ('github', wagtail.blocks.URLBlock(required=False))], icon='document'))], blank=True, null=True)),
                ('promote_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
