# Generated by Django 4.0.8 on 2023-01-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0067_learningresearchpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresearchpage',
            name='mission_header',
        ),
        migrations.DeleteModel(
            name='ResearchPage',
        ),
    ]
