# Generated by Django 4.0.8 on 2022-12-15 20:55

from django.db import migrations, models
import pages.custom_blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0067_remove_researchpage_external_collaborators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpage',
            old_name='projects_header',
            new_name='research_area_header',
        ),
        migrations.RemoveField(
            model_name='researchpage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='researchpage',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='researchpage',
            name='projects',
        ),
        migrations.AddField(
            model_name='researchpage',
            name='banner_CTA',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='researchpage',
            name='banner_URL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='banner_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='banner_header',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='research_areas',
            field=wagtail.core.fields.StreamField([('research_area_section', wagtail.core.blocks.StructBlock([('research_area_title', wagtail.core.blocks.CharBlock()), ('research_area_blurb', wagtail.core.blocks.RichTextBlock()), ('research_area_blurb_mobile', wagtail.core.blocks.RichTextBlock()), ('research_area', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('short_description', wagtail.core.blocks.CharBlock()), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('cta_text', wagtail.core.blocks.CharBlock(required=False)), ('cta_link', wagtail.core.blocks.URLBlock(required=False)), ('publication', wagtail.core.blocks.URLBlock(required=False)), ('github', wagtail.core.blocks.URLBlock(required=False))])))]))], default=''),
        ),
    ]
