# Generated by Django 4.0.8 on 2023-01-19 14:15

from django.db import migrations
import pages.custom_blocks
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_merge_20230118_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k12mainpage',
            name='faqs',
            field=wagtail.fields.StreamField([('faq', wagtail.blocks.StructBlock([('question', wagtail.blocks.RichTextBlock(required=True)), ('slug', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.RichTextBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='k12mainpage',
            name='features_cards',
            field=wagtail.fields.StreamField([('features_cards', wagtail.blocks.StructBlock([('icon', pages.custom_blocks.APIImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='k12mainpage',
            name='highlights',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('highlight_subheader', wagtail.blocks.TextBlock(required=False)), ('highlight_text', wagtail.blocks.CharBlock(Required=False))])))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='k12mainpage',
            name='stats_grid',
            field=wagtail.fields.StreamField([('stat', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('bold_stat_text', wagtail.blocks.TextBlock(required=False)), ('normal_stat_text', wagtail.blocks.CharBlock(required=False))])))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='learningresearchpage',
            name='alumni',
            field=wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('linked_in', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='learningresearchpage',
            name='collaborating_researchers',
            field=wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('long_title', wagtail.blocks.CharBlock(required=False)), ('bio', wagtail.blocks.CharBlock()), ('education', wagtail.blocks.CharBlock(required=False)), ('specialization', wagtail.blocks.CharBlock(required=False)), ('research_interest', wagtail.blocks.CharBlock(required=False)), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('website', wagtail.blocks.URLBlock(required=False)), ('linked_in', wagtail.blocks.URLBlock(required=False)), ('google_scholar', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='learningresearchpage',
            name='current_members',
            field=wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('long_title', wagtail.blocks.CharBlock(required=False)), ('bio', wagtail.blocks.CharBlock()), ('education', wagtail.blocks.CharBlock(required=False)), ('specialization', wagtail.blocks.CharBlock(required=False)), ('research_interest', wagtail.blocks.CharBlock(required=False)), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('website', wagtail.blocks.URLBlock(required=False)), ('linked_in', wagtail.blocks.URLBlock(required=False)), ('google_scholar', wagtail.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='learningresearchpage',
            name='publications',
            field=wagtail.fields.StreamField([('publication', wagtail.blocks.StructBlock([('authors', wagtail.blocks.CharBlock()), ('date', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('excerpt', wagtail.blocks.CharBlock()), ('pdf', wagtail.blocks.URLBlock()), ('github', wagtail.blocks.URLBlock(required=False))], icon='document'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='learningresearchpage',
            name='research_areas_list',
            field=wagtail.fields.StreamField([('research_area_section', wagtail.blocks.StructBlock([('research_area_title', wagtail.blocks.CharBlock()), ('research_area_blurb', wagtail.blocks.RichTextBlock()), ('research_area_blurb_mobile', wagtail.blocks.RichTextBlock()), ('research_areas', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('short_description', wagtail.blocks.CharBlock(help_text='Short Description (Mobile Only)', label='Short Description (Mobile Only)')), ('photo', pages.custom_blocks.APIImageChooserBlock(required=False)), ('cta_text', wagtail.blocks.CharBlock(required=False)), ('cta_link', wagtail.blocks.URLBlock(required=False)), ('publication', wagtail.blocks.URLBlock(required=False)), ('github', wagtail.blocks.URLBlock(required=False))])))]))], default='', use_json_field=True),
        ),
    ]
