# Generated by Django 4.0.8 on 2022-12-19 18:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_remove_researchpage_research_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='research_area_description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
