# Generated by Django 4.0.8 on 2023-02-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_remove_learningresearchpage_mission_header_and_more'),
        ('pages', '0070_alter_k12mainpage_faqs_and_more'),
    ]

    operations = [
    ]
