# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_auto_20161101_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='questions',
            field=wagtail.core.fields.StreamField((('question', wagtail.core.blocks.StructBlock((('question', wagtail.core.blocks.RichTextBlock(required=True)), ('answer', wagtail.core.blocks.RichTextBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))))),)),
        ),
    ]
