# Generated by Django 4.0.8 on 2022-12-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_alter_researchpage_research_area_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpage',
            old_name='banner_CTA',
            new_name='bannerCTA',
        ),
        migrations.RenameField(
            model_name='researchpage',
            old_name='banner_URL',
            new_name='bannerURL',
        ),
    ]
