# Generated by Django 4.0.8 on 2023-02-02 21:44

from django.db import migrations, models
import pages.custom_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0071_merge_20230202_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='k12mainpage',
            name='subject_list_default',
            field=models.CharField(blank=True, default='Find Your Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='k12mainpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonials', wagtail.blocks.StructBlock([('author_icon', pages.custom_blocks.APIImageChooserBlock(required=False)), ('author_name', wagtail.blocks.CharBlock(required=True)), ('author_title', wagtail.blocks.CharBlock(required=True)), ('testimonial', wagtail.blocks.RichTextBlock(required=True))]))], use_json_field=None),
        ),
    ]
