# Generated by Django 4.0.8 on 2023-03-22 20:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('pages', '0072_k12mainpage_subject_list_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('heading_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_button_link', models.URLField(blank=True, null=True)),
                ('courses_coming_soon', models.TextField(blank=True, null=True)),
                ('assignable_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('assignable_cta_link', models.URLField(blank=True, null=True)),
                ('assignable_cta_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_2_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('section_2_description', models.TextField(blank=True, null=True)),
                ('instructor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor_link', models.URLField(blank=True, null=True)),
                ('admin_text', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_link', models.URLField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('quote_author', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_title', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_school', models.CharField(blank=True, max_length=255, null=True)),
                ('tos_link', models.URLField(blank=True, null=True)),
                ('heading_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('promote_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
