# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0073_giveform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='giveform',
            name='intro_description',
        ),
        migrations.RemoveField(
            model_name='giveform',
            name='intro_heading',
        ),
        migrations.AddField(
            model_name='giveform',
            name='page_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
