# Generated by Django 4.0.8 on 2023-03-24 17:52

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0074_remove_assignable_admin_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignable',
            name='heading_button_link',
        ),
        migrations.RemoveField(
            model_name='assignable',
            name='heading_button_text',
        ),
        migrations.AlterField(
            model_name='assignable',
            name='available_courses',
            field=wagtail.fields.StreamField([('course', wagtail.blocks.StructBlock([('cover', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='assignable',
            name='courses_coming_soon',
            field=wagtail.fields.StreamField([('course', wagtail.blocks.StructBlock([('cover', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
