# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 21:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0074_auto_20161111_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='intro_description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
