# Generated by Django 4.0.8 on 2023-04-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('pages', '0075_remove_assignable_available_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignable',
            name='heading',
        ),
        migrations.AddField(
            model_name='assignable',
            name='heading_title_image',
            field=models.ForeignKey(blank=True, help_text='Title to be displayed on the page. Should be an svg file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
