# Generated by Django 4.0.8 on 2023-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0076_remove_assignable_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignable',
            name='add_assignable_cta_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignable',
            name='add_assignable_cta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignable',
            name='add_assignable_cta_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignable',
            name='add_assignable_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
