# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0077_accessibility_licensing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibility',
            old_name='terms_of_service_content',
            new_name='accessibility_content',
        ),
        migrations.RenameField(
            model_name='licensing',
            old_name='terms_of_service_content',
            new_name='licensing_content',
        ),
    ]
