# Generated by Django 4.0.8 on 2023-05-18 18:21

from django.db import migrations
import pages.custom_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0078_rename_add_assignable_header_assignable_faq_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignable',
            name='section_2_image',
        ),
        migrations.AddField(
            model_name='assignable',
            name='image_carousel',
            field=wagtail.fields.StreamField([('carousel_image', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', pages.custom_blocks.APIImageChooserBlock(required=False))])))], blank=True, null=True, use_json_field=True),
        ),
    ]
