# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0079_auto_20170126_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone_number',
        ),
    ]
