# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0080_remove_contactus_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducation',
            old_name='get_started_step_2_cta',
            new_name='get_started_step_2_logged_in_cta',
        ),
        migrations.AddField(
            model_name='highereducation',
            name='get_started_step_2_logged_out_cta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
