# Generated by Django 5.0.4 on 2024-06-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0084_customizablepage"),
        ("snippets", "0037_pagelayout"),
    ]

    operations = [
        migrations.AddField(
            model_name="customizablepage",
            name="page_layout",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="snippets.pagelayout"),
        ),
    ]
