# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0085_marketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='section_4_books',
        ),
    ]
