# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20170414_0856'),
        ('pages', '0086_remove_marketing_section_4_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('marketing_page_book', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_page_books', to='pages.Marketing')),
                ('tutor_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='books.Book')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
