# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0088_auto_20170602_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingVideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_blurb', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingVideos',
            fields=[
                ('marketingvideolink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.MarketingVideoLink')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('marketing_video', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_videos', to='pages.Marketing')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('pages.marketingvideolink', models.Model),
        ),
    ]
