# Generated by Django 5.0.4 on 2024-06-28 19:48

import django.db.models.deletion
import pages.custom_blocks
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0089_alter_rootpage_body"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rootpage",
            old_name="page_layout",
            new_name="layout",
        ),
        migrations.AddField(
            model_name="rootpage",
            name="promote_image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtailimages.image"
            ),
        ),
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(required=True)),
                                ("sub_heading", wagtail.blocks.CharBlock(required=False)),
                                ("description", pages.custom_blocks.APIRichTextBlock(required=False)),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(required=False)),
                                            (
                                                "cta",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ("text", wagtail.blocks.CharBlock(required=True)),
                                                        ("link", wagtail.blocks.URLBlock(required=True)),
                                                        ("link_aria_label", wagtail.blocks.CharBlock(required=True)),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("text", wagtail.blocks.CharBlock(required=True)),
                                                ("link", wagtail.blocks.URLBlock(required=True)),
                                                ("link_aria_label", wagtail.blocks.CharBlock(required=True)),
                                            ],
                                            required=False,
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "content",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StreamBlock(
                                            [
                                                (
                                                    "cards",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "style",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            ("rounded", "Rounded"),
                                                                            ("square", "Square"),
                                                                        ]
                                                                    ),
                                                                ),
                                                                ("heading", wagtail.blocks.CharBlock(required=True)),
                                                                (
                                                                    "description",
                                                                    pages.custom_blocks.APIRichTextBlock(required=True),
                                                                ),
                                                                (
                                                                    "cta",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "text",
                                                                                wagtail.blocks.CharBlock(required=True),
                                                                            ),
                                                                            (
                                                                                "link",
                                                                                wagtail.blocks.URLBlock(required=True),
                                                                            ),
                                                                            (
                                                                                "link_aria_label",
                                                                                wagtail.blocks.CharBlock(required=True),
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "image",
                                                                                wagtail.images.blocks.ImageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "alt_text",
                                                                                wagtail.blocks.CharBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "cta",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "link",
                                                                                            wagtail.blocks.URLBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "link_aria_label",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        )
                                                    ),
                                                ),
                                                ("paragraph", pages.custom_blocks.APIRichTextBlock(required=False)),
                                                ("html", wagtail.blocks.RawHTMLBlock(required=False)),
                                                (
                                                    "image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "image",
                                                                wagtail.images.blocks.ImageChooserBlock(required=False),
                                                            ),
                                                            ("alt_text", wagtail.blocks.CharBlock(required=False)),
                                                            (
                                                                "cta",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(required=True),
                                                                        ),
                                                                        (
                                                                            "link",
                                                                            wagtail.blocks.URLBlock(required=True),
                                                                        ),
                                                                        (
                                                                            "link_aria_label",
                                                                            wagtail.blocks.CharBlock(required=True),
                                                                        ),
                                                                    ],
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "faqs",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "question",
                                                                    wagtail.blocks.RichTextBlock(required=True),
                                                                ),
                                                                ("slug", wagtail.blocks.CharBlock(required=True)),
                                                                ("answer", wagtail.blocks.RichTextBlock(required=True)),
                                                                (
                                                                    "document",
                                                                    wagtail.documents.blocks.DocumentChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        )
                                                    ),
                                                ),
                                            ],
                                            required=True,
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("paragraph", pages.custom_blocks.APIRichTextBlock()),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ("alt_text", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("text", wagtail.blocks.CharBlock(required=True)),
                                            ("link", wagtail.blocks.URLBlock(required=True)),
                                            ("link_aria_label", wagtail.blocks.CharBlock(required=True)),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
