# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0091_auto_20170614_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='banner_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='new_frontier_cta_link_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='new_frontier_cta_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='intro_description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='technology',
            name='new_frontier_description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
