# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0092_auto_20170614_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
