# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0095_auto_20170919_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='section_5_dollar_1_paragraph',
            field=models.CharField(default='Pays for our engineers and researchers', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='section_5_dollar_2_paragraph',
            field=models.CharField(default='Pays for authors to keep content current', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='section_5_dollar_3_paragraph',
            field=models.CharField(default='Pays for our Support team', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='section_5_dollar_4_paragraph',
            field=models.CharField(default='Helps us keep the lights on', max_length=255),
            preserve_default=False,
        ),
    ]
