# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0096_auto_20170919_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_1_caption',
            field=models.CharField(default='Preview and create a course.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_1_cta',
            field=models.CharField(default='Get Started', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_1_link',
            field=models.URLField(default='https://tutor.openstax.org/dashboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_2_caption',
            field=models.CharField(default='Get advice from pioneers of the tool.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_2_cta',
            field=models.CharField(default='Join A Webinar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='floating_footer_button_2_link',
            field=models.URLField(default='https://openstax.org/blog/upcoming-openstax-webinars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='section_6_heading',
            field=models.CharField(default='Frequently asked questions', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketing',
            name='section_6_knowledge_base_copy',
            field=wagtail.wagtailcore.fields.RichTextField(default='Knowledge base copy goes here.'),
            preserve_default=False,
        ),
    ]
