# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0097_auto_20170919_1320'),
        ('pages', '0093_auto_20170922_2218'),
    ]

    operations = [
    ]
