# Generated by Django 2.0.2 on 2018-05-21 16:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0107_auto_20180521_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_heading', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('featured_provider_blurb', models.TextField()),
                ('featured_provider_link', models.URLField()),
                ('featured_provider_cta', models.CharField(max_length=255)),
                ('providers', wagtail.core.fields.StreamField((('provider', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())), icon='document')),))),
                ('isbn_cta', models.CharField(max_length=255)),
                ('featured_provider_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('isbn_download', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
