# Generated by Django 2.0.2 on 2018-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0108_printorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='featured_provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
