# Generated by Django 5.0.7 on 2024-07-16 15:33

import pages.custom_blocks
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0084_customizablepage_squashed_0110_alter_rootpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", pages.custom_blocks.APIRichTextBlock()),
                                ("image", pages.custom_blocks.APIImageChooserBlock(required=False)),
                                (
                                    "cta",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("text", wagtail.blocks.CharBlock(required=True)),
                                                ("aria_label", wagtail.blocks.CharBlock(required=False)),
                                                (
                                                    "target",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            ("external", wagtail.blocks.URLBlock(required=False)),
                                                            (
                                                                "internal",
                                                                wagtail.blocks.PageChooserBlock(required=False),
                                                            ),
                                                            (
                                                                "document",
                                                                wagtail.documents.blocks.DocumentChooserBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ],
                                                        required=True,
                                                    ),
                                                ),
                                            ],
                                            label="Button",
                                            required=False,
                                        ),
                                        default=[],
                                        label="Calls to Action",
                                        max_num=2,
                                    ),
                                ),
                                (
                                    "config",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image_alignment",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "Left"),
                                                        ("right", "Right"),
                                                        ("topLeft", "Top Left"),
                                                        ("topRight", "Top Right"),
                                                        ("bottomLeft", "Bottom Left"),
                                                        ("bottomRight", "Bottom Right"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "image_size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("auto", "Auto"),
                                                        ("contain", "Contain"),
                                                        ("cover", "Cover"),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        block_counts={"image_alignment": {"max_num": 1}, "image_size": {"max_num": 1}},
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "cards_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "cards",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "text",
                                                                            pages.custom_blocks.APIRichTextBlock(),
                                                                        ),
                                                                        (
                                                                            "cta",
                                                                            wagtail.blocks.ListBlock(
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "aria_label",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=False
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "target",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "external",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            required=False
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "internal",
                                                                                                        wagtail.blocks.PageChooserBlock(
                                                                                                            required=False
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "document",
                                                                                                        wagtail.documents.blocks.DocumentChooserBlock(
                                                                                                            required=False
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    label="Link",
                                                                                    required=False,
                                                                                ),
                                                                                default=[],
                                                                                label="Calls to Action",
                                                                                max_num=1,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                )
                                                            ),
                                                        ),
                                                        (
                                                            "config",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "corner_style",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                ("rounded", "Rounded"),
                                                                                ("square", "Square"),
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                block_counts={"corner_style": {"max_num": 1}},
                                                                max_num=1,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    label="Cards Block",
                                                ),
                                            ),
                                            ("text", pages.custom_blocks.APIRichTextBlock()),
                                            ("html", wagtail.blocks.RawHTMLBlock()),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
