# Generated by Django 2.0.2 on 2018-06-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0111_auto_20180618_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='who_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
