# Generated by Django 2.0.2 on 2018-06-20 18:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0112_auto_20180620_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
        migrations.RemoveField(
            model_name='researchpeople',
            name='people_ptr',
        ),
        migrations.RemoveField(
            model_name='researchpeople',
            name='publications',
        ),
        migrations.AddField(
            model_name='researchpage',
            name='people',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))), icon='user')),), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='ResearchPeople',
        ),
    ]
