# Generated by Django 2.0.2 on 2018-06-20 18:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0113_auto_20180620_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='researchpublications',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='researchpublications',
            name='publications_ptr',
        ),
        migrations.AddField(
            model_name='researchpage',
            name='publications',
            field=wagtail.core.fields.StreamField((('publication', wagtail.core.blocks.StructBlock((('date', wagtail.core.blocks.DateBlock()), ('title', wagtail.core.blocks.CharBlock()), ('excerpt', wagtail.core.blocks.CharBlock()), ('download_url', wagtail.core.blocks.URLBlock()), ('authors', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()),)))), icon='user')),), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='ResearchAuthors',
        ),
        migrations.DeleteModel(
            name='ResearchPublications',
        ),
    ]
