# Generated by Django 2.0.2 on 2018-06-20 18:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0114_auto_20180620_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='publications',
            field=wagtail.core.fields.StreamField((('publication', wagtail.core.blocks.StructBlock((('date', wagtail.core.blocks.DateBlock()), ('title', wagtail.core.blocks.CharBlock()), ('excerpt', wagtail.core.blocks.CharBlock()), ('download_url', wagtail.core.blocks.URLBlock()), ('authors', wagtail.core.blocks.CharBlock())), icon='user')),), blank=True, null=True),
        ),
    ]
