# Generated by Django 2.0.2 on 2018-06-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0116_auto_20180620_1323'),
        ('pages', '0112_aboutuspage_who_image'),
    ]

    operations = [
    ]
