# Generated by Django 2.0.2 on 2018-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0118_remove_researchpage_mission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='featured_provider_intro_blurb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='other_providers_intro_blurb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
