# Generated by Django 2.0.2 on 2018-07-09 16:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0120_auto_20180706_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpage',
            old_name='people',
            new_name='current_members',
        ),
        migrations.AddField(
            model_name='researchpage',
            name='alumni',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock())), icon='user')),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpage',
            name='external_collaborators',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))), icon='user')),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpage',
            name='projects',
            field=wagtail.core.fields.StreamField((('project', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock())), icon='user')),), blank=True, null=True),
        ),
    ]
