# Generated by Django 2.0.2 on 2018-07-12 17:10

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0121_auto_20180709_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_images',
            field=wagtail.core.fields.StreamField((('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock())))),), null=True),
        ),
    ]
