# Generated by Django 2.0.2 on 2018-07-16 19:57

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0122_homepage_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='current_members',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock())), required=False))), icon='user')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='external_collaborators',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock())), required=False))), icon='user')),), blank=True, null=True),
        ),
    ]
