# Generated by Django 2.0.2 on 2018-07-25 20:52

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0127_auto_20180717_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.TextField(max_length=255)),
                ('subheader', models.TextField(max_length=255)),
                ('people', wagtail.core.fields.StreamField((('groups', wagtail.core.blocks.StructBlock((('group', wagtail.core.blocks.CharBlock()), ('people', wagtail.core.blocks.StructBlock((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', pages.models.APIImageChooserBlock(required=False))), icon='user')),)))))),))),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
