# Generated by Django 2.0.2 on 2018-07-25 21:00

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0128_teampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='people',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', pages.models.APIImageChooserBlock(required=False)), ('group', wagtail.core.blocks.ChoiceBlock(choices=[('leadership', 'Leadership'), ('team', 'Team'), ('fab', 'Faculty Advisory Board'), ('advisers', 'Strategic Advisers')]))), icon='user')),)),
        ),
    ]
