# Generated by Django 5.0.7 on 2024-07-24 23:45
# Modified to no-op: layout field was never created (removed from 0084 squashed migration)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0131_alter_impact_making_a_difference"),
    ]

    operations = [
        # No-op: layout field (ForeignKey to snippets.pagelayout) was removed from CreateModel
        # This migration is replaced by 0131_alter_impact_making_a_difference_squashed_0144
    ]
