# Generated by Django 2.0.2 on 2018-08-01 22:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0133_teampage_team_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='publications',
            field=wagtail.core.fields.StreamField([('publication', wagtail.core.blocks.StructBlock([('authors', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateBlock()), ('title', wagtail.core.blocks.CharBlock()), ('excerpt', wagtail.core.blocks.CharBlock()), ('download_url', wagtail.core.blocks.URLBlock())], icon='user'))], blank=True, null=True),
        ),
    ]
