# Generated by Django 2.0.2 on 2018-08-06 14:30

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0134_auto_20180801_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='current_members',
            field=wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('photo', pages.models.APIImageChooserBlock(required=False)), ('website', wagtail.core.blocks.URLBlock(required=False))], icon='user'))], blank=True, null=True),
        ),
    ]
