# Generated by Django 2.0.2 on 2018-09-10 15:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0137_auto_20180830_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='featured_providers',
            field=wagtail.core.fields.StreamField([('provider', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())], icon='document'))], null=True),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='providers',
            field=wagtail.core.fields.StreamField([('provider', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())], icon='document'))]),
        ),
    ]
