# Generated by Django 2.0.2 on 2018-09-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('pages', '0139_homepage_mobile_banner_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutusopenstaxteam',
            name='openstaxteam_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutusopenstaxteam',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutusstrategicadvisors',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutusstrategicadvisors',
            name='strategicadvisors_ptr',
        ),
        migrations.RemoveField(
            model_name='openstaxteam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='strategicadvisors',
            name='image',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsOpenStaxTeam',
        ),
        migrations.DeleteModel(
            name='AboutUsStrategicAdvisors',
        ),
        migrations.DeleteModel(
            name='OpenStaxTeam',
        ),
        migrations.DeleteModel(
            name='StrategicAdvisors',
        ),
    ]
