# Generated by Django 5.0.7 on 2024-07-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0137_alter_rootpage_promote_image"),
        ("pages", "0146_alter_rootpage_body"),
    ]

    operations = []
