# Generated by Django 2.0.2 on 2018-10-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0148_card_rovercardssection2_rovercardssection3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rover',
            name='section_2_tabs',
        ),
        migrations.RemoveField(
            model_name='rover',
            name='section_3_cards',
        ),
    ]
