# Generated by Django 2.0.2 on 2018-10-24 21:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0150_auto_20181018_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='section_4_faqs',
            field=wagtail.core.fields.StreamField([('headline', wagtail.core.blocks.CharBlock()), ('faqs', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(required=False)), ('answer', wagtail.core.blocks.TextBlock(required=False))])))], blank=True, null=True),
        ),
    ]
