# Generated by Django 2.0.2 on 2018-10-23 20:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0150_auto_20181018_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpage',
            name='projects',
            field=wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(help_text='Optional link to project.', required=False))], icon='user'))], blank=True, null=True),
        ),
    ]
