# Generated by Django 2.0.2 on 2018-10-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0151_auto_20181023_1501'),
        ('pages', '0151_auto_20181024_1627'),
    ]

    operations = [
    ]
