# Generated by Django 5.1.1 on 2025-01-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0152_alter_rootpage_body_alter_rootpage_layout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
    ]
