# Generated by Django 2.0.2 on 2018-11-09 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('pages', '0153_impactpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpactPage',
            new_name='MapPage',
        ),
    ]
