# Generated by Django 5.0.12 on 2025-04-24 13:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0154_alter_impact_improving_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="layout",
            field=wagtail.fields.StreamField(
                [("default", 0), ("landing", 11)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {"default": [], "label": "Nav Links"}),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Show Give Button in Header", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("nav_links", 9), ("show_give_now_button", 10)]],
                        {"label": "Landing Page"},
                    ),
                },
                default=[],
            ),
        ),
    ]
