# Generated by Django 5.1.12 on 2025-10-15 14:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0161_assignable_instructor_help_cta_button_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignable",
            name="cta_section_footer",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
