# Generated by Django 5.1.12 on 2025-12-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0162_assignable_cta_section_footer"),
        ("salesforce", "0114_school_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootpage",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Link a school to this landing page. School information will be included in the API response.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="salesforce.school",
            ),
        ),
    ]
