# Generated by Django 2.0.2 on 2018-12-03 21:17

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0162_auto_20181203_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportpage',
            name='disruption',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(max_num=1)), ('description', wagtail.core.blocks.TextBlock(max_num=1)), ('graph', wagtail.core.blocks.StructBlock([('top_caption', wagtail.core.blocks.CharBlock(max_num=1)), ('bottom_caption', wagtail.core.blocks.RawHTMLBlock(max_num=1)), ('image', pages.models.APIImageChooserBlock(max_num=1)), ('imageAlt', wagtail.core.blocks.CharBlock(max_num=1))]))], null=True),
        ),
        migrations.AddField(
            model_name='annualreportpage',
            name='sustainability',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(max_num=1)), ('description', wagtail.core.blocks.TextBlock(max_num=1)), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', pages.models.APIImageChooserBlock(max_num=1)), ('imageAlt', wagtail.core.blocks.CharBlock(max_num=1))])))], null=True),
        ),
        migrations.AddField(
            model_name='annualreportpage',
            name='testimonials',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(max_num=1)), ('description', wagtail.core.blocks.TextBlock(max_num=1)), ('testimonials', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', pages.models.APIImageChooserBlock(max_num=1)), ('imageAlt', wagtail.core.blocks.CharBlock(max_num=1)), ('quote', wagtail.core.blocks.CharBlock(max_num=1)), ('link', wagtail.core.blocks.URLBlock(max_num=1)), ('linkText', wagtail.core.blocks.CharBlock(max_num=1))])))], null=True),
        ),
        migrations.AlterField(
            model_name='annualreportpage',
            name='reach',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(max_num=1)), ('description', wagtail.core.blocks.TextBlock(max_num=1)), ('facts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(max_num=1)), ('unit', wagtail.core.blocks.CharBlock(max_num=1)), ('text', wagtail.core.blocks.CharBlock(max_num=1))])))], null=True),
        ),
    ]
