# Generated by Django 5.2.11 on 2026-03-17 23:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0166_pardotformpage_pardotformfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 91),
                    ("section", 94),
                    ("columns", 105),
                    ("divider", 112),
                    ("html", 26),
                    ("tabbed_content", 123),
                ],
                block_lookup={
                    0: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Custom color for the button. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {"block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}}, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: ("wagtail.blocks.StructBlock", [[("text", 0), ("cta_block", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    18: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Accent color for a card. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": [], "label": "Accent Colors"}),
                    20: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Divider color between cards. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": [], "label": "Divider Colors"}),
                    22: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Background color for the cards block. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels for the cards. default 0.", "min_value": 0},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 15),
                                ("card_style", 16),
                                ("card_columns", 17),
                                ("accent_colors", 19),
                                ("divider_colors", 21),
                                ("background_color", 22),
                                ("border_size", 23),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("cards", 14), ("config", 24)]], {"label": "Cards Block"}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"default": [], "label": "Actions", "max_num": 2}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical"), ("stacked", "Stacked")],
                            "help_text": "Layout of the buttons. Default horizontal.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 30), ("layout", 31), ("rendering_condition", 32)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("description", 27), ("actions", 29), ("config", 33)]], {}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": [], "label": "Links"}),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    38: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Custom color for the links. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [[("color", 37), ("custom_color", 38), ("size", 39), ("layout", 40), ("analytics_label", 30)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    42: ("wagtail.blocks.StructBlock", [[("links", 36), ("config", 41)]], {}),
                    43: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    44: ("wagtail.blocks.RichTextBlock", (), {"help_text": "The quote content."}),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Accent color for the quote. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [[("accent_color", 47)]],
                        {"block_counts": {"accent_color": {"max_num": 1}}, "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 43), ("content", 44), ("name", 45), ("title", 46), ("config", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    52: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    53: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 50), ("slug", 51), ("answer", 52), ("document", 53)]],
                        {},
                    ),
                    55: ("wagtail.blocks.StreamBlock", [[("faq", 54)]], {}),
                    56: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    57: ("wagtail.blocks.ListBlock", (56,), {}),
                    58: ("wagtail.blocks.StructBlock", [[("books", 57)]], {"label": "Books Block"}),
                    59: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Pardot Form", "page_type": ["pages.PardotFormPage"]},
                    ),
                    60: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 25),
                                ("text", 0),
                                ("html", 26),
                                ("cta_block", 34),
                                ("links_group", 42),
                                ("quote", 49),
                                ("faq", 55),
                                ("book_list", 58),
                            ]
                        ],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Background color of the well. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    62: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Sets the gradient end color. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to_right", "To Right"),
                                ("to_left", "To Left"),
                                ("to_top", "To Top"),
                                ("to_bottom", "To Bottom"),
                                ("to_top_right", "To Top Right"),
                                ("to_top_left", "To Top Left"),
                                ("to_bottom_right", "To Bottom Right"),
                                ("to_bottom_left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to_right.",
                        },
                    ),
                    64: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    65: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Border color. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    66: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    67: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    68: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    69: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    70: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    73: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "[a-zA-Z0-9\\-_]",
                        },
                    ),
                    74: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 61),
                                ("gradient_color", 62),
                                ("gradient_direction", 63),
                                ("border_radius", 64),
                                ("border_color", 65),
                                ("border_size", 66),
                                ("padding", 67),
                                ("margin", 68),
                                ("pull_up", 69),
                                ("width", 70),
                                ("text_alignment", 71),
                                ("analytics_label", 72),
                                ("id", 73),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    75: ("wagtail.blocks.StructBlock", [[("content", 60), ("config", 74)]], {"label": "Well"}),
                    76: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 25),
                                ("text", 0),
                                ("html", 26),
                                ("cta_block", 34),
                                ("links_group", 42),
                                ("quote", 49),
                                ("faq", 55),
                                ("book_list", 58),
                                ("pardot_form", 59),
                                ("well", 75),
                            ]
                        ],
                        {},
                    ),
                    77: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    78: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    79: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    80: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    81: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    82: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    83: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    84: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    87: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Border color for the hero image. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    88: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    89: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "How much the image overhangs the section boundary in pixels. default 0."},
                    ),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 79),
                                ("id", 73),
                                ("background_color", 80),
                                ("gradient_color", 62),
                                ("gradient_direction", 63),
                                ("padding", 81),
                                ("padding_top", 82),
                                ("padding_bottom", 83),
                                ("text_alignment", 84),
                                ("analytics_label", 85),
                                ("image_border_radius", 86),
                                ("image_border_color", 87),
                                ("image_border_size", 88),
                                ("image_overhang", 89),
                                ("rendering_condition", 32),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 76), ("image", 77), ("image_alt", 78), ("config", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    93: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 73),
                                ("background_color", 80),
                                ("gradient_color", 62),
                                ("gradient_direction", 63),
                                ("padding", 81),
                                ("padding_top", 82),
                                ("padding_bottom", 83),
                                ("text_alignment", 84),
                                ("analytics_label", 85),
                                ("flex", 92),
                                ("rendering_condition", 32),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("content", 76), ("config", 93)]], {}),
                    95: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Background color of the columns container. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    96: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    97: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    98: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    99: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    101: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    102: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    103: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    104: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 95),
                                ("gradient_color", 62),
                                ("gradient_direction", 63),
                                ("padding", 96),
                                ("padding_top", 97),
                                ("padding_bottom", 98),
                                ("flex", 99),
                                ("analytics_label", 100),
                                ("id", 73),
                                ("gap", 101),
                                ("left_size", 102),
                                ("right_size", 103),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 76), ("right_content", 76), ("config", 104)]],
                        {"label": "Columns"},
                    ),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    107: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 106),
                                ("width", 107),
                                ("height", 108),
                                ("offset_vertical", 109),
                                ("offset_horizontal", 110),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    112: ("wagtail.blocks.StructBlock", [[("image", 43), ("config", 111)]], {}),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    114: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 91), ("section", 94), ("columns", 105), ("divider", 112), ("html", 26)]],
                        {},
                    ),
                    115: ("wagtail.blocks.StructBlock", [[("label", 113), ("content", 114)]], {}),
                    116: ("wagtail.blocks.ListBlock", (115,), {"label": "Tabs"}),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    118: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Color of the active tab indicator. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    119: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid hex color."},
                            "help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000.",
                            "regex": "#[a-zA-Z0-9]{6}",
                        },
                    ),
                    120: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    121: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    122: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 117),
                                ("active_color", 118),
                                ("background_color", 119),
                                ("gradient_color", 62),
                                ("gradient_direction", 63),
                                ("default_tab", 120),
                                ("analytics_label", 100),
                                ("border_width", 121),
                                ("id", 73),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 116), ("config", 122)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
    ]
