# Generated by Django 5.2.12 on 2026-06-09 22:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0169_alter_rootpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignable",
            name="faqs",
            field=wagtail.fields.StreamField(
                [("faq", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    2: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("slug", 1), ("answer", 2), ("document", 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creatorfestpage",
            name="page_panels",
            field=wagtail.fields.StreamField(
                [("panel", 13)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("alt_text", 0), ("link", 3), ("alignment", 4), ("identifier", 5)]],
                        {"required": False},
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    8: ("pages.custom_blocks.APIRichTextBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("alt_text", 0), ("link", 3), ("alignment", 4), ("identifier", 5)]],
                        {},
                    ),
                    10: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 9), ("headline", 1), ("description", 10)]],
                        {"null": True},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("superheading", 0),
                                ("heading", 1),
                                ("background_image", 6),
                                ("embed", 7),
                                ("paragraph", 8),
                                ("cards", 12),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creatorfestpage",
            name="register",
            field=wagtail.fields.StreamField(
                [("box", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    2: ("wagtail.blocks.URLBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 0), ("address", 1), ("button_url", 2), ("button_text", 0)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="questions",
            field=wagtail.fields.StreamField(
                [("question", 4)],
                block_lookup={
                    0: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    2: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("slug", 1), ("answer", 2), ("document", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("tagline", 0), ("paragraph", 1), ("image", 2), ("html", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "full title"}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    2: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="improving_access",
            field=wagtail.fields.StreamField(
                [("content", 12)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("alt_text", 1), ("link", 2), ("alignment", 3), ("identifier", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    8: ("wagtail.blocks.URLBlock", (), {}),
                    9: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 9), ("description", 6), ("link_text", 1), ("link_href", 2)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("heading", 6),
                                ("description", 7),
                                ("button_text", 6),
                                ("button_href", 8),
                                ("cards", 11),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="making_a_difference",
            field=wagtail.fields.StreamField(
                [("content", 8)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    2: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["pages.ImpactStory", "news.NewsArticle"]},
                    ),
                    5: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("story_text", 3), ("linked_story", 4), ("embedded_video", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("heading", 0), ("description", 1), ("stories", 7)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="quote",
            field=wagtail.fields.StreamField(
                [("content", 7)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("alt_text", 1), ("link", 2), ("alignment", 3), ("identifier", 4)]],
                        {},
                    ),
                    6: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("image", 5), ("quote", 6)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="reach",
            field=wagtail.fields.StreamField(
                [("content", 11)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("alt_text", 1), ("link", 2), ("alignment", 3), ("identifier", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    8: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 8), ("description", 6), ("link_text", 1), ("link_href", 2)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("heading", 6), ("description", 7), ("cards", 10)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="supporter_community",
            field=wagtail.fields.StreamField(
                [("content", 9)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt_text", 2), ("link", 3), ("alignment", 4), ("identifier", 5)]],
                        {},
                    ),
                    7: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    8: ("wagtail.blocks.URLBlock", (), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("image", 6), ("quote", 7), ("link_text", 0), ("link_href", 8)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="impactstory",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("aligned_image", 5),
                    ("pullquote", 8),
                    ("aligned_html", 9),
                    ("document", 10),
                    ("embed", 11),
                    ("blog_cta", 15),
                ],
                block_lookup={
                    0: ("pages.custom_blocks.APIRichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("news.models.ImageChooserBlock", (), {}),
                    2: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    3: ("news.models.ImageFormatChoiceBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 2), ("alignment", 3), ("alt_text", 4)]],
                        {"icon": "image", "label": "Aligned image"},
                    ),
                    6: ("wagtail.blocks.TextBlock", ("quote title",), {}),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: ("wagtail.blocks.StructBlock", [[("quote", 6), ("attribution", 7)]], {}),
                    9: ("wagtail.blocks.RawHTMLBlock", (), {"icon": "code", "label": "Raw HTML"}),
                    10: ("news.models.BlogDocumentChooserBlock", (), {"icon": "doc-full-inverse"}),
                    11: ("wagtail.embeds.blocks.EmbedBlock", (), {"icon": "media", "label": "Embed Media URL"}),
                    12: ("wagtail.blocks.TextBlock", (), {}),
                    13: ("wagtail.blocks.URLBlock", (), {}),
                    14: ("news.models.CTAAlignmentChoiceBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("description", 12),
                                ("button_text", 7),
                                ("button_href", 13),
                                ("alignment", 14),
                            ]
                        ],
                        {"icon": "form", "label": "Call to Action block"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpartnerprogrampage",
            name="section_3_tall_cards",
            field=wagtail.fields.StreamField(
                [("card", 4)],
                block_lookup={
                    0: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    1: ("wagtail.blocks.URLBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: ("wagtail.blocks.StructBlock", [[("html", 0), ("link", 1), ("link_text", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpartnerprogrampage",
            name="section_3_wide_cards",
            field=wagtail.fields.StreamField(
                [("card", 8)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("pages.custom_blocks.ImageFormatChoiceBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used by the frontend for Google Analytics.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("alt_text", 1), ("link", 2), ("alignment", 3), ("identifier", 4)]],
                        {},
                    ),
                    6: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("icon", 5), ("html", 6)]], {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpartnership",
            name="program_tab_content",
            field=wagtail.fields.StreamField(
                [("tab", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    2: ("wagtail.blocks.StructBlock", [[("heading", 0), ("description", 1)]], {}),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="k12mainpage",
            name="faqs",
            field=wagtail.fields.StreamField(
                [("faq", 4)],
                block_lookup={
                    0: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    2: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("slug", 1), ("answer", 2), ("document", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="k12mainpage",
            name="features_cards",
            field=wagtail.fields.StreamField(
                [("features_cards", 3)],
                block_lookup={
                    0: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("pages.custom_blocks.APIRichTextBlock", (), {"required": True}),
                    3: ("wagtail.blocks.StructBlock", [[("icon", 0), ("title", 1), ("description", 2)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="k12mainpage",
            name="testimonials",
            field=wagtail.fields.StreamField(
                [("testimonials", 3)],
                block_lookup={
                    0: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("pages.custom_blocks.APIRichTextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("author_icon", 0), ("author_name", 1), ("author_title", 1), ("testimonial", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="learningresearchpage",
            name="research_areas_list",
            field=wagtail.fields.StreamField(
                [("research_area_section", 8)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short Description (Mobile Only)", "label": "Short Description (Mobile Only)"},
                    ),
                    3: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 0),
                                ("description", 0),
                                ("short_description", 2),
                                ("photo", 3),
                                ("cta_text", 4),
                                ("cta_link", 5),
                                ("publication", 5),
                                ("github", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("research_area_title", 0),
                                ("research_area_blurb", 1),
                                ("research_area_blurb_mobile", 1),
                                ("research_areas", 7),
                            ]
                        ],
                        {},
                    ),
                },
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 90),
                    ("section", 93),
                    ("columns", 104),
                    ("divider", 111),
                    ("html", 26),
                    ("tabbed_content", 122),
                ],
                block_lookup={
                    0: ("pages.custom_blocks.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {"block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}}, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: ("wagtail.blocks.StructBlock", [[("text", 0), ("cta_block", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    18: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for a card. Must be hex eg: #ff0000."},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": [], "label": "Accent Colors"}),
                    20: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Divider color between cards. Must be hex eg: #ff0000."},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": [], "label": "Divider Colors"}),
                    22: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards block. Must be hex eg: #ff0000."},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels for the cards. default 0.", "min_value": 0},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 15),
                                ("card_style", 16),
                                ("card_columns", 17),
                                ("accent_colors", 19),
                                ("divider_colors", 21),
                                ("background_color", 22),
                                ("border_size", 23),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("cards", 14), ("config", 24)]], {"label": "Cards Block"}),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"default": [], "label": "Actions", "max_num": 2}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline")],
                            "help_text": "Layout of the buttons. Inline places description and buttons side-by-side.",
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 30), ("layout", 31), ("rendering_condition", 32)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("description", 27), ("actions", 29), ("config", 33)]], {}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": [], "label": "Links"}),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    38: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the links. Must be hex eg: #ff0000."},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [[("color", 37), ("custom_color", 38), ("size", 39), ("layout", 40), ("analytics_label", 30)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    42: ("wagtail.blocks.StructBlock", [[("links", 36), ("config", 41)]], {}),
                    43: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    44: ("pages.custom_blocks.APIRichTextBlock", (), {"help_text": "The quote content."}),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    47: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for the quote. Must be hex eg: #ff0000."},
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [[("accent_color", 47)]],
                        {"block_counts": {"accent_color": {"max_num": 1}}, "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 43), ("content", 44), ("name", 45), ("title", 46), ("config", 48)]],
                        {},
                    ),
                    50: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    52: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    53: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 50), ("slug", 51), ("answer", 52), ("document", 53)]],
                        {},
                    ),
                    55: ("wagtail.blocks.StreamBlock", [[("faq", 54)]], {}),
                    56: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    57: ("wagtail.blocks.ListBlock", (56,), {}),
                    58: ("wagtail.blocks.StructBlock", [[("books", 57)]], {"label": "Books Block"}),
                    59: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 25),
                                ("text", 0),
                                ("html", 26),
                                ("cta_block", 34),
                                ("links_group", 42),
                                ("quote", 49),
                                ("faq", 55),
                                ("book_list", 58),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the well. Must be hex eg: #ff0000."},
                    ),
                    61: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Sets the gradient end color. Must be hex eg: #ff0000."},
                    ),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to_right", "To Right"),
                                ("to_left", "To Left"),
                                ("to_top", "To Top"),
                                ("to_bottom", "To Bottom"),
                                ("to_top_right", "To Top Right"),
                                ("to_top_left", "To Top Left"),
                                ("to_bottom_right", "To Bottom Right"),
                                ("to_bottom_left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to_right.",
                        },
                    ),
                    63: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    64: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color. Must be hex eg: #ff0000."},
                    ),
                    65: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    66: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    67: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    68: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    69: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    72: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "[a-zA-Z0-9\\-_]",
                        },
                    ),
                    73: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 60),
                                ("gradient_color", 61),
                                ("gradient_direction", 62),
                                ("border_radius", 63),
                                ("border_color", 64),
                                ("border_size", 65),
                                ("padding", 66),
                                ("margin", 67),
                                ("pull_up", 68),
                                ("width", 69),
                                ("text_alignment", 70),
                                ("analytics_label", 71),
                                ("id", 72),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    74: ("wagtail.blocks.StructBlock", [[("content", 59), ("config", 73)]], {"label": "Well"}),
                    75: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 25),
                                ("text", 0),
                                ("html", 26),
                                ("cta_block", 34),
                                ("links_group", 42),
                                ("quote", 49),
                                ("faq", 55),
                                ("book_list", 58),
                                ("well", 74),
                            ]
                        ],
                        {},
                    ),
                    76: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    77: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    79: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey."
                        },
                    ),
                    80: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    81: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    82: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    86: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color for the hero image. Must be hex eg: #ff0000."},
                    ),
                    87: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    88: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "How much the image overhangs the section boundary in pixels. default 0."},
                    ),
                    89: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 78),
                                ("id", 72),
                                ("background_color", 79),
                                ("gradient_color", 61),
                                ("gradient_direction", 62),
                                ("padding", 80),
                                ("padding_top", 81),
                                ("padding_bottom", 82),
                                ("text_alignment", 83),
                                ("analytics_label", 84),
                                ("image_border_radius", 85),
                                ("image_border_color", 86),
                                ("image_border_size", 87),
                                ("image_overhang", 88),
                                ("rendering_condition", 32),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 75), ("image", 76), ("image_alt", 77), ("config", 89)]],
                        {},
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    92: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 72),
                                ("background_color", 79),
                                ("gradient_color", 61),
                                ("gradient_direction", 62),
                                ("padding", 80),
                                ("padding_top", 81),
                                ("padding_bottom", 82),
                                ("text_alignment", 83),
                                ("analytics_label", 84),
                                ("flex", 91),
                                ("rendering_condition", 32),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    93: ("wagtail.blocks.StructBlock", [[("content", 75), ("config", 92)]], {}),
                    94: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the columns container. Must be hex eg: #ff0000."},
                    ),
                    95: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    96: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    97: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    100: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    101: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    102: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    103: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 94),
                                ("gradient_color", 61),
                                ("gradient_direction", 62),
                                ("padding", 95),
                                ("padding_top", 96),
                                ("padding_bottom", 97),
                                ("flex", 98),
                                ("analytics_label", 99),
                                ("id", 72),
                                ("gap", 100),
                                ("left_size", 101),
                                ("right_size", 102),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 75), ("right_content", 75), ("config", 103)]],
                        {"label": "Columns"},
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    106: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_mssages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 105),
                                ("width", 106),
                                ("height", 107),
                                ("offset_vertical", 108),
                                ("offset_horizontal", 109),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    111: ("wagtail.blocks.StructBlock", [[("image", 43), ("config", 110)]], {}),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    113: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 90), ("section", 93), ("columns", 104), ("divider", 111), ("html", 26)]],
                        {},
                    ),
                    114: ("wagtail.blocks.StructBlock", [[("label", 112), ("content", 113)]], {}),
                    115: ("wagtail.blocks.ListBlock", (114,), {"label": "Tabs"}),
                    116: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    117: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color of the active tab indicator. Must be hex eg: #ff0000."},
                    ),
                    118: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000."},
                    ),
                    119: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    120: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    121: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 116),
                                ("active_color", 117),
                                ("background_color", 118),
                                ("gradient_color", 61),
                                ("gradient_direction", 62),
                                ("default_tab", 119),
                                ("analytics_label", 99),
                                ("border_width", 120),
                                ("id", 72),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 115), ("config", 121)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="tutormarketing",
            name="cost_cards",
            field=wagtail.fields.StreamField(
                [("cards", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("pages.custom_blocks.APIRichTextBlock", (), {"required": True}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="tutormarketing",
            name="faqs",
            field=wagtail.fields.StreamField(
                [("faq", 4)],
                block_lookup={
                    0: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    2: (
                        "pages.custom_blocks.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("slug", 1), ("answer", 2), ("document", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="tutormarketing",
            name="features_cards",
            field=wagtail.fields.StreamField(
                [("cards", 3)],
                block_lookup={
                    0: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("pages.custom_blocks.APIRichTextBlock", (), {"required": True}),
                    3: ("wagtail.blocks.StructBlock", [[("icon", 0), ("title", 1), ("description", 2)]], {}),
                },
            ),
        ),
    ]
