# Generated by Django 5.2.12 on 2026-06-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0176_alter_generalpage_body_alter_rootpage_body"),
        ("pages", "0176_alter_rootpage_body"),
    ]

    operations = []
