# Generated by Django 5.2.12 on 2026-06-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0178_alter_rootpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="give",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="give",
            name="promote_image",
        ),
        migrations.RemoveField(
            model_name="giveform",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="giveform",
            name="promote_image",
        ),
        migrations.RemoveField(
            model_name="llphpage",
            name="book_cover",
        ),
        migrations.RemoveField(
            model_name="llphpage",
            name="hero_background",
        ),
        migrations.RemoveField(
            model_name="llphpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="mathquizpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="tutormarketing",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="tutormarketing",
            name="promote_image",
        ),
        migrations.DeleteModel(
            name="CreatorFestPage",
        ),
        migrations.DeleteModel(
            name="Give",
        ),
        migrations.DeleteModel(
            name="GiveForm",
        ),
        migrations.DeleteModel(
            name="LLPHPage",
        ),
        migrations.DeleteModel(
            name="MathQuizPage",
        ),
        migrations.DeleteModel(
            name="TutorMarketing",
        ),
    ]
