# Generated by Django 2.0.9 on 2019-01-14 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('pages', '0178_rovepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RovePage',
            new_name='RoverPage',
        ),
    ]
