# Generated by Django 5.2.12 on 2026-06-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0179_remove_give_page_ptr_remove_give_promote_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
