# Generated by Django 5.2.12 on 2026-06-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0181_alter_rootpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text='Display label, e.g. "Core Team".', max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable key used by the frontend for styling/filtering.", max_length=100, unique=True
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, help_text="Lower numbers sort first.")),
            ],
            options={
                "verbose_name": "Person tag",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
