# Generated by Django 5.2.12 on 2026-06-30 03:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0182_persontag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 121),
                    ("section", 124),
                    ("columns", 135),
                    ("divider", 142),
                    ("html", 30),
                    ("tabbed_content", 153),
                ],
                block_lookup={
                    0: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {"block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}}, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: ("wagtail.blocks.StructBlock", [[("text", 0), ("cta_block", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square"), ("impact", "Impact")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    18: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for a card. Must be hex eg: #ff0000."},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": [], "label": "Accent Colors"}),
                    20: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Divider color between cards. Must be hex eg: #ff0000."},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": [], "label": "Divider Colors"}),
                    22: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards block. Must be hex eg: #ff0000."},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Outer border width in px (all sides). Omit to use the style default; 0 = no border.",
                            "min_value": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top accent bar height in px, independent of the border. Color comes from Accent Colors.",
                            "min_value": 0,
                        },
                    ),
                    25: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top and bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    26: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 15),
                                ("card_style", 16),
                                ("card_columns", 17),
                                ("accent_colors", 19),
                                ("divider_colors", 21),
                                ("background_color", 22),
                                ("border_size", 23),
                                ("accent_size", 24),
                                ("padding", 25),
                                ("padding_top", 26),
                                ("padding_bottom", 27),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "accent_size": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("cards", 14), ("config", 28)]], {"label": "Cards Block"}),
                    30: ("wagtail_html_editor.blocks.EnhancedHTMLBlock", (), {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {"default": [], "label": "Actions", "max_num": 2}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline")],
                            "help_text": "Layout of the buttons. Inline places description and buttons side-by-side.",
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 34), ("layout", 35), ("rendering_condition", 36)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("description", 31), ("actions", 33), ("config", 37)]], {}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": [], "label": "Links"}),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("button", "Button"), ("text", "Text")],
                            "help_text": "Button renders the links as buttons (default); Text renders them as plain links.",
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    43: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the links. Must be hex eg: #ff0000."},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("style", 41),
                                ("color", 42),
                                ("custom_color", 43),
                                ("size", 44),
                                ("layout", 45),
                                ("analytics_label", 34),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                                "style": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    47: ("wagtail.blocks.StructBlock", [[("links", 40), ("config", 46)]], {}),
                    48: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    49: ("openstax.api_fields.APIRichTextBlock", (), {"help_text": "The quote content."}),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image-left", "Image Left"),
                                ("image-right", "Image Right"),
                                ("image-top", "Image Top"),
                                ("compact", "Compact"),
                            ],
                            "help_text": 'How the image and text are arranged. Compact is a small image + short text ("did you know") treatment. Default Image Left.',
                        },
                    ),
                    53: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for the quote. Must be hex eg: #ff0000."},
                    ),
                    54: (
                        "wagtail.blocks.StreamBlock",
                        [[("layout", 52), ("accent_color", 53)]],
                        {"block_counts": {"accent_color": {"max_num": 1}, "layout": {"max_num": 1}}, "required": False},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 48), ("content", 49), ("name", 50), ("title", 51), ("config", 54)]],
                        {},
                    ),
                    56: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic to display large, e.g. 8M+."}),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional supporting text shown below the number.", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("blue", "Blue"), ("green", "Green"), ("orange", "Orange")],
                            "help_text": "Brand color for the number. Defaults to the inherited text color.",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 56), ("caption", 57), ("color", 58)]],
                        {"label": "Big Number"},
                    ),
                    60: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    62: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    63: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 60), ("slug", 61), ("answer", 62), ("document", 63)]],
                        {},
                    ),
                    65: ("wagtail.blocks.StreamBlock", [[("faq", 64)]], {}),
                    66: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    67: ("wagtail.blocks.ListBlock", (66,), {}),
                    68: ("wagtail.blocks.StructBlock", [[("books", 67)]], {"label": "Books Block"}),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title shown above the grid.", "required": False},
                    ),
                    70: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Role, e.g. "Director of Research".', "required": False},
                    ),
                    72: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    73: ("wagtail.blocks.TextBlock", (), {"help_text": "Shown on the card.", "required": False}),
                    74: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "If set, the card becomes clickable and opens an expanded modal.",
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("orcid", "ORCID"),
                                ("website", "Website"),
                                ("email", "Email"),
                                ("scholar", "Google Scholar"),
                                ("x", "X"),
                            ],
                            "help_text": "Determines the icon shown for this link.",
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Full URL, or for the Email type a mailto: link or email address.",
                            "required": True,
                        },
                    ),
                    77: ("wagtail.blocks.StructBlock", [[("type", 75), ("url", 76)]], {}),
                    78: ("wagtail.blocks.ListBlock", (77,), {"default": [], "required": False}),
                    79: ("pages.custom_blocks.PersonTagChooserBlock", ("pages.PersonTag",), {}),
                    80: ("wagtail.blocks.ListBlock", (79,), {"default": [], "required": False}),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 70),
                                ("title", 71),
                                ("image", 72),
                                ("short_bio", 73),
                                ("full_bio", 74),
                                ("links", 78),
                                ("tags", 80),
                            ]
                        ],
                        {},
                    ),
                    82: ("wagtail.blocks.ListBlock", (81,), {}),
                    83: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Number of columns for the grid. default auto.", "max_value": 6, "min_value": 1},
                    ),
                    84: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Width of individual cards. default 27.", "min_value": 0},
                    ),
                    85: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for a card accent, cycled per card. eg: #ff0000,#00ff00,#0000ff.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for card divider lines, cycled per card. eg: #ff0000,#00ff00.",
                            "label": "Divider Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    87: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards. Must be hex eg: #ff0000."},
                    ),
                    88: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Border width in px.", "min_value": 0}),
                    89: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "^[a-zA-Z0-9_-]+$",
                        },
                    ),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_columns", 83),
                                ("card_style", 16),
                                ("card_size", 84),
                                ("accent_colors", 85),
                                ("divider_colors", 86),
                                ("background_color", 87),
                                ("border_size", 88),
                                ("id", 89),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "id": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    91: ("wagtail.blocks.StructBlock", [[("heading", 69), ("people", 82), ("config", 90)]], {}),
                    92: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 29),
                                ("text", 0),
                                ("html", 30),
                                ("cta_block", 38),
                                ("links_group", 47),
                                ("quote", 55),
                                ("big_number", 59),
                                ("faq", 65),
                                ("book_list", 68),
                                ("person", 91),
                            ]
                        ],
                        {},
                    ),
                    93: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the well. Must be hex eg: #ff0000."},
                    ),
                    94: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Sets the gradient end color. Must be hex eg: #ff0000."},
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to right", "To Right"),
                                ("to left", "To Left"),
                                ("to top", "To Top"),
                                ("to bottom", "To Bottom"),
                                ("to top right", "To Top Right"),
                                ("to top left", "To Top Left"),
                                ("to bottom right", "To Bottom Right"),
                                ("to bottom left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to right.",
                        },
                    ),
                    96: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    97: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color. Must be hex eg: #ff0000."},
                    ),
                    98: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    99: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    100: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    101: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    102: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    105: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 93),
                                ("gradient_color", 94),
                                ("gradient_direction", 95),
                                ("border_radius", 96),
                                ("border_color", 97),
                                ("border_size", 98),
                                ("padding", 99),
                                ("margin", 100),
                                ("pull_up", 101),
                                ("width", 102),
                                ("text_alignment", 103),
                                ("analytics_label", 104),
                                ("id", 89),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    106: ("wagtail.blocks.StructBlock", [[("content", 92), ("config", 105)]], {"label": "Well"}),
                    107: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 29),
                                ("text", 0),
                                ("html", 30),
                                ("cta_block", 38),
                                ("links_group", 47),
                                ("quote", 55),
                                ("big_number", 59),
                                ("faq", 65),
                                ("book_list", 68),
                                ("person", 91),
                                ("well", 106),
                            ]
                        ],
                        {},
                    ),
                    108: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    109: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    110: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey."
                        },
                    ),
                    111: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    112: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    113: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    114: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    115: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    116: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    117: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color for the hero image. Must be hex eg: #ff0000."},
                    ),
                    118: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    119: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "How much the image overhangs the section boundary. Must be a valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    120: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 109),
                                ("id", 89),
                                ("background_color", 110),
                                ("gradient_color", 94),
                                ("gradient_direction", 95),
                                ("padding", 111),
                                ("padding_top", 112),
                                ("padding_bottom", 113),
                                ("text_alignment", 114),
                                ("analytics_label", 115),
                                ("image_border_radius", 116),
                                ("image_border_color", 117),
                                ("image_border_size", 118),
                                ("image_overhang", 119),
                                ("rendering_condition", 36),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 107), ("image", 72), ("image_alt", 108), ("config", 120)]],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 89),
                                ("background_color", 110),
                                ("gradient_color", 94),
                                ("gradient_direction", 95),
                                ("padding", 111),
                                ("padding_top", 112),
                                ("padding_bottom", 113),
                                ("text_alignment", 114),
                                ("analytics_label", 115),
                                ("flex", 122),
                                ("rendering_condition", 36),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    124: ("wagtail.blocks.StructBlock", [[("content", 107), ("config", 123)]], {}),
                    125: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the columns container. Must be hex eg: #ff0000."},
                    ),
                    126: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    127: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    128: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    129: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    130: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    131: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    132: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    133: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    134: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 125),
                                ("gradient_color", 94),
                                ("gradient_direction", 95),
                                ("padding", 126),
                                ("padding_top", 127),
                                ("padding_bottom", 128),
                                ("flex", 129),
                                ("analytics_label", 130),
                                ("id", 89),
                                ("gap", 131),
                                ("left_size", 132),
                                ("right_size", 133),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 107), ("right_content", 107), ("config", 134)]],
                        {"label": "Columns"},
                    ),
                    136: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    137: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    138: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    139: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    140: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 136),
                                ("width", 137),
                                ("height", 138),
                                ("offset_vertical", 139),
                                ("offset_horizontal", 140),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    142: ("wagtail.blocks.StructBlock", [[("image", 48), ("config", 141)]], {}),
                    143: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 121), ("section", 124), ("columns", 135), ("divider", 142), ("html", 30)]],
                        {},
                    ),
                    145: ("wagtail.blocks.StructBlock", [[("label", 143), ("content", 144)]], {}),
                    146: ("wagtail.blocks.ListBlock", (145,), {"label": "Tabs"}),
                    147: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    148: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color of the active tab indicator. Must be hex eg: #ff0000."},
                    ),
                    149: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000."},
                    ),
                    150: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    151: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    152: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 147),
                                ("active_color", 148),
                                ("background_color", 149),
                                ("gradient_color", 94),
                                ("gradient_direction", 95),
                                ("default_tab", 150),
                                ("analytics_label", 130),
                                ("border_width", 151),
                                ("id", 89),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    153: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 146), ("config", 152)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
    ]
