# Generated by Django 5.2.12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0183_alter_rootpage_body"),
        ("pages", "0183_cards_colors_list_to_csv"),
    ]

    operations = [
    ]
