# Generated by Django 5.2.12 on 2026-07-02 19:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0184_merge_0183_alter_rootpage_body_0183_cards_colors_list_to_csv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 118),
                    ("section", 121),
                    ("columns", 132),
                    ("divider", 139),
                    ("html", 28),
                    ("tabbed_content", 150),
                ],
                block_lookup={
                    0: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {"block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}}, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: ("wagtail.blocks.StructBlock", [[("text", 0), ("cta_block", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square"), ("impact", "Impact")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    18: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for the top accent bar, cycled per card. eg: #ff0000,#00ff00,#0000ff.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for card divider lines, cycled per card. eg: #ff0000,#00ff00.",
                            "label": "Divider Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    20: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards block. Must be hex eg: #ff0000."},
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Outer border width in px (all sides). Omit to use the style default; 0 = no border.",
                            "min_value": 0,
                        },
                    ),
                    22: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top accent bar height in px, independent of the border. Color comes from Accent Colors.",
                            "min_value": 0,
                        },
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top and bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    25: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 15),
                                ("card_style", 16),
                                ("card_columns", 17),
                                ("accent_colors", 18),
                                ("divider_colors", 19),
                                ("background_color", 20),
                                ("border_size", 21),
                                ("accent_size", 22),
                                ("padding", 23),
                                ("padding_top", 24),
                                ("padding_bottom", 25),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "accent_size": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("cards", 14), ("config", 26)]], {"label": "Cards Block"}),
                    28: ("wagtail_html_editor.blocks.EnhancedHTMLBlock", (), {}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"default": [], "label": "Actions", "max_num": 2}),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline")],
                            "help_text": "Layout of the buttons. Inline places description and buttons side-by-side.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 32), ("layout", 33), ("rendering_condition", 34)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("description", 29), ("actions", 31), ("config", 35)]], {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": [], "label": "Links"}),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("button", "Button"), ("text", "Text")],
                            "help_text": "Button renders the links as buttons (default); Text renders them as plain links.",
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    41: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the links. Must be hex eg: #ff0000."},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("style", 39),
                                ("color", 40),
                                ("custom_color", 41),
                                ("size", 42),
                                ("layout", 43),
                                ("analytics_label", 32),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                                "style": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    45: ("wagtail.blocks.StructBlock", [[("links", 38), ("config", 44)]], {}),
                    46: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    47: ("openstax.api_fields.APIRichTextBlock", (), {"help_text": "The quote content."}),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image-left", "Image Left"),
                                ("image-right", "Image Right"),
                                ("image-top", "Image Top"),
                                ("compact", "Compact"),
                            ],
                            "help_text": 'How the image and text are arranged. Compact is a small image + short text ("did you know") treatment. Default Image Left.',
                        },
                    ),
                    51: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for the quote. Must be hex eg: #ff0000."},
                    ),
                    52: (
                        "wagtail.blocks.StreamBlock",
                        [[("layout", 50), ("accent_color", 51)]],
                        {"block_counts": {"accent_color": {"max_num": 1}, "layout": {"max_num": 1}}, "required": False},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 46), ("content", 47), ("name", 48), ("title", 49), ("config", 52)]],
                        {},
                    ),
                    54: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic to display large, e.g. 8M+."}),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional supporting text shown below the number.", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("blue", "Blue"), ("green", "Green"), ("orange", "Orange")],
                            "help_text": "Brand color for the number. Defaults to the inherited text color.",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 54), ("caption", 55), ("color", 56)]],
                        {"label": "Big Number"},
                    ),
                    58: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    60: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    61: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 58), ("slug", 59), ("answer", 60), ("document", 61)]],
                        {},
                    ),
                    63: ("wagtail.blocks.StreamBlock", [[("faq", 62)]], {}),
                    64: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    65: ("wagtail.blocks.ListBlock", (64,), {}),
                    66: ("wagtail.blocks.StructBlock", [[("books", 65)]], {"label": "Books Block"}),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title shown above the grid.", "required": False},
                    ),
                    68: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Role, e.g. "Director of Research".', "required": False},
                    ),
                    70: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    71: ("wagtail.blocks.TextBlock", (), {"help_text": "Shown on the card.", "required": False}),
                    72: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "If set, the card becomes clickable and opens an expanded modal.",
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("orcid", "ORCID"),
                                ("website", "Website"),
                                ("email", "Email"),
                                ("scholar", "Google Scholar"),
                                ("x", "X"),
                            ],
                            "help_text": "Determines the icon shown for this link.",
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Full URL, or for the Email type a mailto: link or email address.",
                            "required": True,
                        },
                    ),
                    75: ("wagtail.blocks.StructBlock", [[("type", 73), ("url", 74)]], {}),
                    76: ("wagtail.blocks.ListBlock", (75,), {"default": [], "required": False}),
                    77: ("pages.custom_blocks.PersonTagChooserBlock", ("pages.PersonTag",), {}),
                    78: ("wagtail.blocks.ListBlock", (77,), {"default": [], "required": False}),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 68),
                                ("title", 69),
                                ("image", 70),
                                ("short_bio", 71),
                                ("full_bio", 72),
                                ("links", 76),
                                ("tags", 78),
                            ]
                        ],
                        {},
                    ),
                    80: ("wagtail.blocks.ListBlock", (79,), {}),
                    81: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Number of columns for the grid. default auto.", "max_value": 6, "min_value": 1},
                    ),
                    82: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Width of individual cards. default 27.", "min_value": 0},
                    ),
                    83: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for a card accent, cycled per card. eg: #ff0000,#00ff00,#0000ff.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    84: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards. Must be hex eg: #ff0000."},
                    ),
                    85: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Border width in px.", "min_value": 0}),
                    86: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "^[a-zA-Z0-9_-]+$",
                        },
                    ),
                    87: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_columns", 81),
                                ("card_style", 16),
                                ("card_size", 82),
                                ("accent_colors", 83),
                                ("divider_colors", 19),
                                ("background_color", 84),
                                ("border_size", 85),
                                ("id", 86),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "id": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("heading", 67), ("people", 80), ("config", 87)]], {}),
                    89: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 27),
                                ("text", 0),
                                ("html", 28),
                                ("cta_block", 36),
                                ("links_group", 45),
                                ("quote", 53),
                                ("big_number", 57),
                                ("faq", 63),
                                ("book_list", 66),
                                ("person", 88),
                            ]
                        ],
                        {},
                    ),
                    90: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the well. Must be hex eg: #ff0000."},
                    ),
                    91: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Sets the gradient end color. Must be hex eg: #ff0000."},
                    ),
                    92: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to right", "To Right"),
                                ("to left", "To Left"),
                                ("to top", "To Top"),
                                ("to bottom", "To Bottom"),
                                ("to top right", "To Top Right"),
                                ("to top left", "To Top Left"),
                                ("to bottom right", "To Bottom Right"),
                                ("to bottom left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to right.",
                        },
                    ),
                    93: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    94: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color. Must be hex eg: #ff0000."},
                    ),
                    95: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    96: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    97: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    98: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    99: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    102: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 90),
                                ("gradient_color", 91),
                                ("gradient_direction", 92),
                                ("border_radius", 93),
                                ("border_color", 94),
                                ("border_size", 95),
                                ("padding", 96),
                                ("margin", 97),
                                ("pull_up", 98),
                                ("width", 99),
                                ("text_alignment", 100),
                                ("analytics_label", 101),
                                ("id", 86),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    103: ("wagtail.blocks.StructBlock", [[("content", 89), ("config", 102)]], {"label": "Well"}),
                    104: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 27),
                                ("text", 0),
                                ("html", 28),
                                ("cta_block", 36),
                                ("links_group", 45),
                                ("quote", 53),
                                ("big_number", 57),
                                ("faq", 63),
                                ("book_list", 66),
                                ("person", 88),
                                ("well", 103),
                            ]
                        ],
                        {},
                    ),
                    105: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    107: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey."
                        },
                    ),
                    108: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    109: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    110: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    111: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    114: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color for the hero image. Must be hex eg: #ff0000."},
                    ),
                    115: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    116: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "How much the image overhangs the section boundary. Must be a valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 106),
                                ("id", 86),
                                ("background_color", 107),
                                ("gradient_color", 91),
                                ("gradient_direction", 92),
                                ("padding", 108),
                                ("padding_top", 109),
                                ("padding_bottom", 110),
                                ("text_alignment", 111),
                                ("analytics_label", 112),
                                ("image_border_radius", 113),
                                ("image_border_color", 114),
                                ("image_border_size", 115),
                                ("image_overhang", 116),
                                ("rendering_condition", 34),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 104), ("image", 70), ("image_alt", 105), ("config", 117)]],
                        {},
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    120: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 86),
                                ("background_color", 107),
                                ("gradient_color", 91),
                                ("gradient_direction", 92),
                                ("padding", 108),
                                ("padding_top", 109),
                                ("padding_bottom", 110),
                                ("text_alignment", 111),
                                ("analytics_label", 112),
                                ("flex", 119),
                                ("rendering_condition", 34),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    121: ("wagtail.blocks.StructBlock", [[("content", 104), ("config", 120)]], {}),
                    122: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the columns container. Must be hex eg: #ff0000."},
                    ),
                    123: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    124: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    125: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    126: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    128: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    129: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    130: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 122),
                                ("gradient_color", 91),
                                ("gradient_direction", 92),
                                ("padding", 123),
                                ("padding_top", 124),
                                ("padding_bottom", 125),
                                ("flex", 126),
                                ("analytics_label", 127),
                                ("id", 86),
                                ("gap", 128),
                                ("left_size", 129),
                                ("right_size", 130),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 104), ("right_content", 104), ("config", 131)]],
                        {"label": "Columns"},
                    ),
                    133: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    134: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    135: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    137: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    138: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 133),
                                ("width", 134),
                                ("height", 135),
                                ("offset_vertical", 136),
                                ("offset_horizontal", 137),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    139: ("wagtail.blocks.StructBlock", [[("image", 46), ("config", 138)]], {}),
                    140: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 118), ("section", 121), ("columns", 132), ("divider", 139), ("html", 28)]],
                        {},
                    ),
                    142: ("wagtail.blocks.StructBlock", [[("label", 140), ("content", 141)]], {}),
                    143: ("wagtail.blocks.ListBlock", (142,), {"label": "Tabs"}),
                    144: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    145: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color of the active tab indicator. Must be hex eg: #ff0000."},
                    ),
                    146: (
                        "pages.custom_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000."},
                    ),
                    147: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    148: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    149: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 144),
                                ("active_color", 145),
                                ("background_color", 146),
                                ("gradient_color", 91),
                                ("gradient_direction", 92),
                                ("default_tab", 147),
                                ("analytics_label", 127),
                                ("border_width", 148),
                                ("id", 86),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "required": False,
                        },
                    ),
                    150: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 143), ("config", 149)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
    ]
