# Generated by Django 2.0.13 on 2019-02-25 18:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0187_auto_20190219_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='cost_details',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='cost_heading',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='current_partners_details',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='current_partners_heading',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='program_details',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='program_heading',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='timeline_details',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='timeline_heading',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='what_you_get_details',
        ),
        migrations.RemoveField(
            model_name='institutionalpartnership',
            name='what_you_get_heading',
        ),
        migrations.AddField(
            model_name='institutionalpartnership',
            name='application_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalpartnership',
            name='application_quote_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionalpartnership',
            name='application_quote_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionalpartnership',
            name='application_quote_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionalpartnership',
            name='program_tab_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock())], null=True),
        ),
    ]
