# Generated by Django 2.0.13 on 2019-03-26 18:21

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pages', '0191_remove_institutionalpartnership_application_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPartnerProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('section_1_heading', models.CharField(max_length=255)),
                ('section_1_description', wagtail.core.fields.RichTextField()),
                ('section_1_link_text', models.CharField(max_length=255)),
                ('section_1_link', models.URLField()),
                ('quote', models.TextField()),
                ('quote_name', models.CharField(max_length=255)),
                ('quote_title', models.CharField(max_length=255)),
                ('quote_school', models.CharField(max_length=255)),
                ('section_2_heading', models.CharField(max_length=255)),
                ('section_2_description', wagtail.core.fields.RichTextField()),
                ('section_2_image_alt', models.CharField(max_length=255)),
                ('section_3_heading', models.CharField(max_length=255)),
                ('section_3_description', models.TextField()),
                ('section_3_wide_cards', wagtail.core.fields.StreamField([('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock()), ('identifier', wagtail.core.blocks.CharBlock(help_text='Used by the frontend for Google Analytics.', required=False))])), ('html', wagtail.core.blocks.RichTextBlock())])))])),
                ('section_3_tall_cards', wagtail.core.fields.StreamField([('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.RichTextBlock()), ('link', wagtail.core.blocks.URLBlock()), ('link_text', wagtail.core.blocks.CharBlock())])))])),
                ('section_4_quote_text', models.TextField()),
                ('section_4_quote_name', models.CharField(max_length=255)),
                ('section_4_quote_title', models.CharField(max_length=255)),
                ('section_5_heading', models.CharField(max_length=255)),
                ('section_5_description', wagtail.core.fields.RichTextField()),
                ('section_5_image_alt', models.CharField(max_length=255)),
                ('section_6_heading', models.CharField(max_length=255)),
                ('section_6_description', models.TextField()),
                ('section_6_cards', wagtail.core.fields.StreamField([('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading_number', wagtail.core.blocks.CharBlock()), ('heading_unit', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock())])))])),
                ('section_7_heading', models.CharField(max_length=255)),
                ('section_7_subheading', models.CharField(max_length=255)),
                ('section_7_icons', wagtail.core.fields.StreamField([('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock()), ('identifier', wagtail.core.blocks.CharBlock(help_text='Used by the frontend for Google Analytics.', required=False))])), ('image_alt_text', wagtail.core.blocks.CharBlock())])))])),
                ('section_7_link_text', models.CharField(max_length=255)),
                ('section_7_link_target', models.URLField()),
                ('section_8_quote_text', models.TextField()),
                ('section_8_quote_name', models.CharField(max_length=255)),
                ('section_8_quote_title', models.CharField(max_length=255)),
                ('section_8_quote_school', models.CharField(max_length=255)),
                ('section_9_heading', models.CharField(max_length=255)),
                ('section_9_submit_url', models.URLField()),
                ('section_9_form_prompt', models.CharField(max_length=255)),
                ('section_9_button_text', models.CharField(max_length=255)),
                ('section_9_contact_html', wagtail.core.fields.RichTextField()),
                ('section_2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('section_5_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
