# Generated by Django 2.0.13 on 2019-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0192_institutionalpartnerprogrampage'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalpartnerprogrampage',
            name='section_4_quote_school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
