# Generated by Django 2.0.13 on 2019-04-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('pages', '0194_auto_20190401_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalpartnerprogrampage',
            name='section_4_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
