# Generated by Django 6.0.6 on 2026-07-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0194_alter_assignable_faqs_alter_faq_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibility",
            name="current_version_compiled_by",
            field=models.CharField(blank=True, max_length=255, verbose_name="current version compiled by"),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="current_version_ref",
            field=models.CharField(blank=True, max_length=20, verbose_name="current version ref"),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="custom_review_frequency",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="next_review_date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="current_version_compiled_by",
            field=models.CharField(blank=True, max_length=255, verbose_name="current version compiled by"),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="current_version_ref",
            field=models.CharField(blank=True, max_length=20, verbose_name="current version ref"),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="custom_review_frequency",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="next_review_date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="licensing",
            name="current_version_compiled_by",
            field=models.CharField(blank=True, max_length=255, verbose_name="current version compiled by"),
        ),
        migrations.AddField(
            model_name="licensing",
            name="current_version_ref",
            field=models.CharField(blank=True, max_length=20, verbose_name="current version ref"),
        ),
        migrations.AddField(
            model_name="licensing",
            name="custom_review_frequency",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="licensing",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licensing",
            name="next_review_date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="current_version_compiled_by",
            field=models.CharField(blank=True, max_length=255, verbose_name="current version compiled by"),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="current_version_ref",
            field=models.CharField(blank=True, max_length=20, verbose_name="current version ref"),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="custom_review_frequency",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="next_review_date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="current_version_compiled_by",
            field=models.CharField(blank=True, max_length=255, verbose_name="current version compiled by"),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="current_version_ref",
            field=models.CharField(blank=True, max_length=20, verbose_name="current version ref"),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="custom_review_frequency",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="next_review_date",
            field=models.DateField(editable=False, null=True),
        ),
    ]
