# Generated by Django 6.0.6 on 2026-07-13 20:12

import pages.table_block
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0197_alter_rootpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 198),
                    ("section", 201),
                    ("columns", 212),
                    ("divider", 219),
                    ("html", 29),
                    ("tabbed_content", 230),
                ],
                block_lookup={
                    0: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {
                            "block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Accent color for this card: the border on rounded style, the top accent bar on square (needs Accent Size). Leave unset for the default palette.",
                            "required": False,
                        },
                    ),
                    14: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Color for divider lines in this card. Leave unset for the default palette.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("cta_block", 12), ("accent_color", 13), ("divider_color", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square"), ("impact", "Impact")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("grid", "Grid"),
                                ("masonry", "Masonry (Pinterest-style columns, packed by height)"),
                            ],
                            "help_text": "Grid aligns cards into rows (default); Masonry packs them into columns by height, for decorative card walls.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    21: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards block. Must be hex eg: #ff0000."},
                    ),
                    22: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Outer border width in px (all sides). Omit to use the style default; 0 = no border.",
                            "min_value": 0,
                        },
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top accent bar height in px, independent of the border. Color comes from each card's Accent Color.",
                            "min_value": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top and bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    25: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    26: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 17),
                                ("card_style", 18),
                                ("layout", 19),
                                ("card_columns", 20),
                                ("background_color", 21),
                                ("border_size", 22),
                                ("accent_size", 23),
                                ("padding", 24),
                                ("padding_top", 25),
                                ("padding_bottom", 26),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_size": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("cards", 16), ("config", 27)]], {"label": "Cards Block"}),
                    29: ("wagtail_html_editor.blocks.EnhancedHTMLBlock", (), {}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"default": [], "label": "Actions", "max_num": 2}),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline")],
                            "help_text": "Layout of the buttons. Inline places description and buttons side-by-side.",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 33), ("layout", 34), ("rendering_condition", 35)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("description", 30), ("actions", 32), ("config", 36)]], {}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {"default": [], "label": "Links"}),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("button", "Button"), ("text", "Text")],
                            "help_text": "Button renders the links as buttons (default); Text renders them as plain links.",
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    42: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the links. Must be hex eg: #ff0000."},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("style", 40),
                                ("color", 41),
                                ("custom_color", 42),
                                ("size", 43),
                                ("layout", 44),
                                ("analytics_label", 33),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                                "style": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("links", 39), ("config", 45)]], {}),
                    47: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    48: ("openstax.api_fields.APIRichTextBlock", (), {"help_text": "The quote content."}),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image-left", "Image Left"),
                                ("image-right", "Image Right"),
                                ("image-top", "Image Top"),
                                ("compact", "Compact"),
                            ],
                            "help_text": 'How the image and text are arranged. Compact is a small image + short text ("did you know") treatment. Default Image Left.',
                        },
                    ),
                    52: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for the quote. Must be hex eg: #ff0000."},
                    ),
                    53: (
                        "wagtail.blocks.StreamBlock",
                        [[("layout", 51), ("accent_color", 52)]],
                        {
                            "block_counts": {"accent_color": {"max_num": 1}, "layout": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 47), ("content", 48), ("name", 49), ("title", 50), ("config", 53)]],
                        {},
                    ),
                    55: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic to display large, e.g. 8M+."}),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional supporting text shown below the number.", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("blue", "Blue"), ("green", "Green"), ("orange", "Orange")],
                            "help_text": "Brand color for the number. Defaults to the inherited text color.",
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 55), ("caption", 56), ("color", 57)]],
                        {"label": "Big Number"},
                    ),
                    59: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    61: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    62: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describes the table; rendered as a <caption> for accessibility.",
                            "required": False,
                        },
                    ),
                    64: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("text", "Text"), ("number", "Number"), ("date", "Date")],
                            "help_text": "How readers sort this column. Default text.",
                            "required": False,
                        },
                    ),
                    66: ("wagtail.blocks.StructBlock", [[("header", 64), ("type", 65)]], {}),
                    67: ("wagtail.blocks.ListBlock", (66,), {"default": [], "label": "Columns"}),
                    68: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "Rich-text cell content. Ignored when a Call To Action is set.",
                            "required": False,
                        },
                    ),
                    69: ("wagtail.blocks.StructBlock", [[("content", 68), ("cta", 12)]], {}),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": []}),
                    71: ("wagtail.blocks.StructBlock", [[("cells", 70)]], {}),
                    72: ("wagtail.blocks.ListBlock", (71,), {"default": [], "label": "Rows"}),
                    73: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.Subject",),
                        {"help_text": "Only books in this subject. Leave empty for all subjects.", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("live", "Live"),
                                ("coming_soon", "Coming Soon"),
                                ("new_edition_available", "New Edition Forthcoming"),
                                ("deprecated", "Deprecated"),
                            ],
                            "help_text": "Only books in this state. Leave empty for all listed books.",
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title A–Z"),
                                ("-publish_date", "Newest first"),
                                ("publish_date", "Oldest first"),
                            ],
                            "help_text": "Row order. Default Title A–Z.",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 100.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title"),
                                ("title_link", "Title (linked to book page)"),
                                ("subjects", "Subjects"),
                                ("publish_date", "Publish date"),
                                ("book_state", "State"),
                                ("cover", "Cover image"),
                                ("is_ap", "AP"),
                                ("read_online", "Read online (link)"),
                            ]
                        },
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Column header shown to readers. Defaults to the field label.",
                            "required": False,
                        },
                    ),
                    79: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Overrides how the value is shown and sorted. Default per field.",
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 77), ("header", 78), ("type", 79)]],
                        {"label": "Column"},
                    ),
                    81: ("wagtail.blocks.ListBlock", (80,), {"label": "Columns", "min_num": 1}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 73), ("book_state", 74), ("order", 75), ("limit", 76), ("columns", 81)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Only articles with this subject, e.g. Science. Matches the article's subjects list.",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Only articles with this tag (exact tag name).", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("-date", "Newest first"),
                                ("date", "Oldest first"),
                                ("heading", "Heading A–Z"),
                            ],
                            "help_text": "Row order. Default newest first.",
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 20.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("heading", "Heading"),
                                ("heading_link", "Heading (linked to article)"),
                                ("subheading", "Subheading"),
                                ("author", "Author"),
                                ("date", "Post date"),
                                ("image", "Article image"),
                            ]
                        },
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 87), ("header", 78), ("type", 79)]],
                        {"label": "Column"},
                    ),
                    89: ("wagtail.blocks.ListBlock", (88,), {"label": "Columns", "min_num": 1}),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 83), ("tag", 84), ("order", 85), ("limit", 86), ("columns", 89)]],
                        {},
                    ),
                    91: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["books.Book"]}),
                    92: (
                        "wagtail.blocks.ListBlock",
                        (91,),
                        {
                            "help_text": "The book(s) whose resources fill the table. A resource shared across several books is listed once, with all its book names.",
                            "label": "Books",
                            "min_num": 1,
                        },
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("instructor", "Instructor resources"), ("student", "Student resources")]},
                    ),
                    94: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("all", "All"), ("k12", "K12 only")],
                            "help_text": 'K12 only limits rows to resources flagged "Display on K12".',
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": pages.table_block.resource_category_choices,
                            "help_text": "Only resources with this category. Leave blank for all categories.",
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("book", "Book(s)"),
                                ("heading", "Resource"),
                                ("description", "Description"),
                                ("link", "Link"),
                                ("coming_soon", "Coming soon"),
                                ("k12", "K12"),
                                ("unlocked", "Unlocked"),
                                ("resource_category", "Category"),
                            ]
                        },
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 96), ("header", 78), ("type", 79)]],
                        {"label": "Column"},
                    ),
                    98: ("wagtail.blocks.ListBlock", (97,), {"label": "Columns", "min_num": 1}),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("books", 92),
                                ("resource_type", 93),
                                ("audience", 94),
                                ("resource_category", 95),
                                ("columns", 98),
                            ]
                        ],
                        {},
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("he", "Higher Ed subjects"), ("k12", "K12 subjects")]},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "K12 only: limit to a category, e.g. Math.", "required": False},
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("name", "Subject"),
                                ("category", "Category"),
                                ("color", "Color"),
                                ("icon", "Icon"),
                                ("link", "Link (K12 subject pages)"),
                            ]
                        },
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 102), ("header", 78), ("type", 79)]],
                        {"label": "Column"},
                    ),
                    104: ("wagtail.blocks.ListBlock", (103,), {"label": "Columns", "min_num": 1}),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("variant", 100), ("k12_category", 101), ("columns", 104)]],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be a relative path starting with /apps/cms/api/."},
                            "help_text": "Relative CMS API path including query string, e.g. /apps/cms/api/v2/pages/?type=books.Book&fields=title,cover_url&book_state=live. Must start with /apps/cms/api/. No absolute URLs — they break across environments.",
                            "label": "Endpoint path",
                            "regex": "^/apps/cms/api/\\S*$",
                        },
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "items",
                            "help_text": 'JSON key holding the list of rows. Default "items" (the Wagtail API shape); clear it if the response is a bare list.',
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Dotted path into each item, e.g. title or meta.slug.", "required": True},
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Column header. Defaults to the field path.", "required": False},
                    ),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Cell type. Default text.",
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 108), ("header", 109), ("type", 110)]],
                        {"label": "Column"},
                    ),
                    112: ("wagtail.blocks.ListBlock", (111,), {"label": "Columns", "min_num": 1}),
                    113: ("wagtail.blocks.StructBlock", [[("path", 106), ("items_key", 107), ("columns", 112)]], {}),
                    114: (
                        "wagtail.blocks.StreamBlock",
                        [[("books", 82), ("news", 90), ("book_resources", 99), ("subjects", 105), ("endpoint", 113)]],
                        {
                            "help_text": "Fill the table from CMS content instead of manual rows. When set, manual Columns and Rows are ignored.",
                            "label": "Data source",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Shade alternating rows. Default shade unless Row Colors is set.",
                        },
                    ),
                    116: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ffffff,#f2f2f2."},
                            "help_text": "Comma-separated hex colors cycled across body rows, e.g. #ffffff,#f2f2f2. Overrides the default zebra shade.",
                            "label": "Row Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("off", "Off"), ("on", "On")], "help_text": "Tighter cell padding."},
                    ),
                    118: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Let readers sort by clicking column headers.",
                        },
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Show a text box that filters rows by their content.",
                        },
                    ),
                    120: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "1-based column number the table is sorted by on load.", "min_value": 1},
                    ),
                    121: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("asc", "Ascending"), ("desc", "Descending")],
                            "help_text": "Direction for the default sort. Default ascending.",
                        },
                    ),
                    122: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": 'Show at most this many rows, with a "Show more" control for the rest.',
                            "min_value": 1,
                        },
                    ),
                    123: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown when the table has no rows (e.g. a dynamic source returns nothing).",
                            "required": False,
                        },
                    ),
                    124: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "^[a-zA-Z0-9_-]+$",
                        },
                    ),
                    125: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("striped", 115),
                                ("row_colors", 116),
                                ("condensed", 117),
                                ("sortable", 118),
                                ("filterable", 119),
                                ("default_sort_column", 120),
                                ("default_sort_direction", 121),
                                ("row_limit", 122),
                                ("empty_message", 123),
                                ("id", 124),
                            ]
                        ],
                        {
                            "block_counts": {
                                "condensed": {"max_num": 1},
                                "default_sort_column": {"max_num": 1},
                                "default_sort_direction": {"max_num": 1},
                                "empty_message": {"max_num": 1},
                                "filterable": {"max_num": 1},
                                "id": {"max_num": 1},
                                "row_colors": {"max_num": 1},
                                "row_limit": {"max_num": 1},
                                "sortable": {"max_num": 1},
                                "striped": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 63), ("columns", 67), ("rows", 72), ("data_source", 114), ("config", 125)]],
                        {},
                    ),
                    127: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": True}),
                    128: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    129: ("wagtail.blocks.StructBlock", [[("image", 127), ("alt_text", 128)]], {"label": "Image"}),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [[("table", 126), ("image", 129), ("text", 0)]],
                        {
                            "collapsed": True,
                            "help_text": "Optional table, image, or extra text shown as part of the answer.",
                            "label": "Additional content",
                            "required": False,
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 59), ("slug", 60), ("answer", 61), ("document", 62), ("content", 130)]],
                        {},
                    ),
                    132: ("wagtail.blocks.StreamBlock", [[("faq", 131)]], {}),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible text of the item.", "required": True},
                    ),
                    134: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "Hidden until the item is expanded.", "required": True},
                    ),
                    135: ("wagtail.blocks.StructBlock", [[("header", 133), ("content", 134), ("id", 124)]], {}),
                    136: ("wagtail.blocks.ListBlock", (135,), {"label": "Items"}),
                    137: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("2", "H2"), ("3", "H3"), ("4", "H4")],
                            "help_text": "Heading level for each item, for the document outline and screen-reader navigation. Default H3.",
                        },
                    ),
                    138: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("false", "No"), ("true", "Yes")],
                            "help_text": "Allow more than one item to be open at the same time. Default No.",
                        },
                    ),
                    139: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Hex color for the expand/collapse icon and item divider."},
                    ),
                    140: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors cycled per item, e.g. #ff0000,#00ff00. Overrides Accent Color.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    141: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Adds a colored border above the whole accordion."},
                    ),
                    142: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading_level", 137),
                                ("allow_multiple", 138),
                                ("accent_color", 139),
                                ("accent_colors", 140),
                                ("top_border_color", 141),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_color": {"max_num": 1},
                                "accent_colors": {"max_num": 1},
                                "allow_multiple": {"max_num": 1},
                                "heading_level": {"max_num": 1},
                                "top_border_color": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    143: ("wagtail.blocks.StructBlock", [[("items", 136), ("config", 142)]], {"label": "Accordion"}),
                    144: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    145: ("wagtail.blocks.ListBlock", (144,), {}),
                    146: ("wagtail.blocks.StructBlock", [[("books", 145)]], {"label": "Books Block"}),
                    147: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title shown above the grid.", "required": False},
                    ),
                    148: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Role, e.g. "Director of Research".', "required": False},
                    ),
                    149: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    150: ("wagtail.blocks.TextBlock", (), {"help_text": "Shown on the card.", "required": False}),
                    151: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "If set, the card becomes clickable and opens an expanded modal.",
                            "required": False,
                        },
                    ),
                    152: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("orcid", "ORCID"),
                                ("website", "Website"),
                                ("email", "Email"),
                                ("scholar", "Google Scholar"),
                                ("x", "X"),
                            ],
                            "help_text": "Determines the icon shown for this link.",
                        },
                    ),
                    153: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Full URL, or for the Email type a mailto: link or email address.",
                            "required": True,
                        },
                    ),
                    154: ("wagtail.blocks.StructBlock", [[("type", 152), ("url", 153)]], {}),
                    155: ("wagtail.blocks.ListBlock", (154,), {"default": [], "required": False}),
                    156: ("pages.custom_blocks.PersonTagChooserBlock", ("pages.PersonTag",), {}),
                    157: ("wagtail.blocks.ListBlock", (156,), {"default": [], "required": False}),
                    158: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 64),
                                ("title", 148),
                                ("image", 149),
                                ("short_bio", 150),
                                ("full_bio", 151),
                                ("links", 155),
                                ("tags", 157),
                            ]
                        ],
                        {},
                    ),
                    159: ("wagtail.blocks.ListBlock", (158,), {}),
                    160: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Number of columns for the grid. default auto.", "max_value": 6, "min_value": 1},
                    ),
                    161: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Width of individual cards. default 27.", "min_value": 0},
                    ),
                    162: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for a card accent, cycled per card. eg: #ff0000,#00ff00,#0000ff.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    163: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for card divider lines, cycled per card. eg: #ff0000,#00ff00.",
                            "label": "Divider Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    164: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards. Must be hex eg: #ff0000."},
                    ),
                    165: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Border width in px.", "min_value": 0}),
                    166: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_columns", 160),
                                ("card_style", 18),
                                ("card_size", 161),
                                ("accent_colors", 162),
                                ("divider_colors", 163),
                                ("background_color", 164),
                                ("border_size", 165),
                                ("id", 124),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "id": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    167: ("wagtail.blocks.StructBlock", [[("heading", 147), ("people", 159), ("config", 166)]], {}),
                    168: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 28),
                                ("text", 0),
                                ("html", 29),
                                ("cta_block", 37),
                                ("links_group", 46),
                                ("quote", 54),
                                ("big_number", 58),
                                ("faq", 132),
                                ("accordion", 143),
                                ("book_list", 146),
                                ("person", 167),
                                ("table", 126),
                            ]
                        ],
                        {},
                    ),
                    169: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the well. Must be hex eg: #ff0000."},
                    ),
                    170: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Sets the gradient end color. Must be hex eg: #ff0000."},
                    ),
                    171: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to right", "To Right"),
                                ("to left", "To Left"),
                                ("to top", "To Top"),
                                ("to bottom", "To Bottom"),
                                ("to top right", "To Top Right"),
                                ("to top left", "To Top Left"),
                                ("to bottom right", "To Bottom Right"),
                                ("to bottom left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to right.",
                        },
                    ),
                    172: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    173: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color. Must be hex eg: #ff0000."},
                    ),
                    174: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    175: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    176: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    177: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    178: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    179: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    180: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stack", "Stack"),
                                ("wrap", "Wrap (side by side, reflowing to fewer per row on narrow screens)"),
                            ],
                            "help_text": 'How the well lays out its content blocks. "Wrap" puts them side by side (e.g. a row of Big Numbers), reflowing to fewer per row as the screen narrows. Default stack.',
                        },
                    ),
                    181: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("normal", "Normal"), ("display", "Display Quote")],
                            "help_text": "Renders a Text block's h6 headings as a large, fluid-sized display quote (e.g. a testimonial pull-quote) instead of regular heading size. Default normal.",
                        },
                    ),
                    182: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    183: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 169),
                                ("gradient_color", 170),
                                ("gradient_direction", 171),
                                ("border_radius", 172),
                                ("border_color", 173),
                                ("border_size", 174),
                                ("padding", 175),
                                ("margin", 176),
                                ("pull_up", 177),
                                ("width", 178),
                                ("text_alignment", 179),
                                ("layout", 180),
                                ("heading_style", 181),
                                ("analytics_label", 182),
                                ("id", 124),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "heading_style": {"max_num": 1},
                                "id": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    184: ("wagtail.blocks.StructBlock", [[("content", 168), ("config", 183)]], {"label": "Well"}),
                    185: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 28),
                                ("text", 0),
                                ("html", 29),
                                ("cta_block", 37),
                                ("links_group", 46),
                                ("quote", 54),
                                ("big_number", 58),
                                ("faq", 132),
                                ("accordion", 143),
                                ("book_list", 146),
                                ("person", 167),
                                ("table", 126),
                                ("well", 184),
                            ]
                        ],
                        {},
                    ),
                    186: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    187: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey."
                        },
                    ),
                    188: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    189: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    190: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    191: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    192: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    193: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    194: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color for the hero image. Must be hex eg: #ff0000."},
                    ),
                    195: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    196: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "How much the image overhangs the section boundary. Must be a valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    197: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 186),
                                ("id", 124),
                                ("background_color", 187),
                                ("gradient_color", 170),
                                ("gradient_direction", 171),
                                ("padding", 188),
                                ("padding_top", 189),
                                ("padding_bottom", 190),
                                ("text_alignment", 191),
                                ("analytics_label", 192),
                                ("image_border_radius", 193),
                                ("image_border_color", 194),
                                ("image_border_size", 195),
                                ("image_overhang", 196),
                                ("rendering_condition", 35),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    198: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 185), ("image", 149), ("image_alt", 128), ("config", 197)]],
                        {},
                    ),
                    199: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    200: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 124),
                                ("background_color", 187),
                                ("gradient_color", 170),
                                ("gradient_direction", 171),
                                ("padding", 188),
                                ("padding_top", 189),
                                ("padding_bottom", 190),
                                ("text_alignment", 191),
                                ("analytics_label", 192),
                                ("flex", 199),
                                ("rendering_condition", 35),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    201: ("wagtail.blocks.StructBlock", [[("content", 185), ("config", 200)]], {}),
                    202: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the columns container. Must be hex eg: #ff0000."},
                    ),
                    203: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    204: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    205: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    206: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    207: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    208: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    209: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    210: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    211: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 202),
                                ("gradient_color", 170),
                                ("gradient_direction", 171),
                                ("padding", 203),
                                ("padding_top", 204),
                                ("padding_bottom", 205),
                                ("flex", 206),
                                ("analytics_label", 207),
                                ("id", 124),
                                ("gap", 208),
                                ("left_size", 209),
                                ("right_size", 210),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    212: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 185), ("right_content", 185), ("config", 211)]],
                        {"label": "Columns"},
                    ),
                    213: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    214: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    215: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    216: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    217: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    218: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 213),
                                ("width", 214),
                                ("height", 215),
                                ("offset_vertical", 216),
                                ("offset_horizontal", 217),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    219: ("wagtail.blocks.StructBlock", [[("image", 47), ("config", 218)]], {}),
                    220: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    221: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 198), ("section", 201), ("columns", 212), ("divider", 219), ("html", 29)]],
                        {},
                    ),
                    222: ("wagtail.blocks.StructBlock", [[("label", 220), ("content", 221)]], {}),
                    223: ("wagtail.blocks.ListBlock", (222,), {"label": "Tabs"}),
                    224: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    225: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color of the active tab indicator. Must be hex eg: #ff0000."},
                    ),
                    226: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000."},
                    ),
                    227: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    228: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    229: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 224),
                                ("active_color", 225),
                                ("background_color", 226),
                                ("gradient_color", 170),
                                ("gradient_direction", 171),
                                ("default_tab", 227),
                                ("analytics_label", 207),
                                ("border_width", 228),
                                ("id", 124),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    230: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 223), ("config", 229)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
    ]
