# Generated by Django 2.0.13 on 2019-05-23 16:21

from django.db import migrations, models
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0197_auto_20190514_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverpage',
            name='nav_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_1',
            field=wagtail.core.fields.StreamField([('access_button_link', wagtail.core.blocks.URLBlock()), ('access_button_cta', wagtail.core.blocks.CharBlock()), ('image', pages.models.APIImageChooserBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('button_link', wagtail.core.blocks.URLBlock()), ('button_cta', wagtail.core.blocks.CharBlock()), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_2',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.RawHTMLBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.TextBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_3',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.TextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', pages.models.APIImageChooserBlock()), ('blurb', wagtail.core.blocks.TextBlock())]))), ('button_link', wagtail.core.blocks.URLBlock()), ('button_cta', wagtail.core.blocks.CharBlock()), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_4',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('image', pages.models.APIImageChooserBlock()), ('image_alt_text', wagtail.core.blocks.CharBlock())]))), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_5',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.RawHTMLBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock())]))), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_6',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.RichTextBlock()), ('image', pages.models.APIImageChooserBlock()), ('image_alt_text', wagtail.core.blocks.CharBlock()), ('caption', wagtail.core.blocks.CharBlock()), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='roverpage',
            name='section_7',
            field=wagtail.core.fields.StreamField([('faqs', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock()), ('answer', wagtail.core.blocks.TextBlock())]))), ('webinar_button_url', wagtail.core.blocks.URLBlock()), ('webinar_button_cta', wagtail.core.blocks.CharBlock()), ('signup_button_url', wagtail.core.blocks.URLBlock()), ('signup_button_cta', wagtail.core.blocks.CharBlock()), ('nav_text', wagtail.core.blocks.CharBlock(required=False))]),
        ),
    ]
