# Generated by Django 2.0.13 on 2019-06-17 21:04

from django.db import migrations
import pages.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0199_aboutuspage_where_map_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverpage',
            name='popup',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('instructions', wagtail.core.blocks.TextBlock()), ('sign_in_text', wagtail.core.blocks.CharBlock()), ('cancel_text', wagtail.core.blocks.CharBlock()), ('background_image', pages.models.APIImageChooserBlock())])))], null=True),
        ),
    ]
