# Generated by Django 2.0.13 on 2019-07-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('pages', '0201_auto_20190618_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourimpact',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
