# Generated by Django 2.2.5 on 2019-09-25 17:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0204_auto_20190925_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverpage',
            name='section_5',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.RawHTMLBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock())]))), ('nav_text', wagtail.core.blocks.CharBlock(required=False)), ('see_more_text', wagtail.core.blocks.CharBlock(required=False)), ('see_more_url', wagtail.core.blocks.URLBlock(required=False))]),
        ),
    ]
