# Generated by Django 6.0.6 on 2026-08-12 02:30

import pages.table_block
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0205_alter_rootpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 201),
                    ("section", 204),
                    ("columns", 215),
                    ("divider", 223),
                    ("html", 30),
                    ("tabbed_content", 234),
                ],
                block_lookup={
                    0: ("openstax.api_fields.APIRichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Visible text of the link or button.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessible label for the link or button. if provided, must begin with the visible text.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External links are full urls that can go anywhere", "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor links reference the ID of an element on the page, and scroll the page there.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 3), ("internal", 4), ("document", 5), ("anchor", 6)]],
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("orange", "Orange"),
                                ("white", "White"),
                                ("blue_outline", "Blue Outline"),
                                ("deep_green_outline", "Deep Green Outline"),
                            ],
                            "help_text": "Specifies the button style. Default unspecified, meaning the first button in the block is orange and the second is white.",
                        },
                    ),
                    9: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the button. Must be hex eg: #ff0000."},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("style", 8), ("custom_color", 9)]],
                        {
                            "block_counts": {"custom_color": {"max_num": 1}, "style": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Link", "required": False},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"default": [], "label": "Call To Action", "max_num": 1}),
                    13: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Accent color for this card: the border on rounded style, the top accent bar on square (needs Accent Size). Leave unset for the default palette."
                        },
                    ),
                    14: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color for divider lines in this card. Leave unset for the default palette."},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("accent_color", 13), ("divider_color", 14)]],
                        {
                            "block_counts": {"accent_color": {"max_num": 1}, "divider_color": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("text", 0), ("cta_block", 12), ("config", 15)]], {}),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Sets the width of the individual cards. default 27.", "min_value": 0},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("rounded", "Rounded"), ("square", "Square"), ("impact", "Impact")],
                            "help_text": "The border style of the cards. default borderless.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("grid", "Grid"),
                                ("masonry", "Masonry (Pinterest-style columns, packed by height)"),
                            ],
                            "help_text": "Grid aligns cards into rows (default); Masonry packs them into columns by height, for decorative card walls.",
                        },
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of columns for the cards grid. default auto.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    22: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards block. Must be hex eg: #ff0000."},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Outer border width in px (all sides). Omit to use the style default; 0 = no border.",
                            "min_value": 0,
                        },
                    ),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top accent bar height in px, independent of the border. Color comes from each card's Accent Color.",
                            "min_value": 0,
                        },
                    ),
                    25: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top and bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    26: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Top spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Bottom spacing around the block, in 10px increments.", "min_value": 0},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_size", 18),
                                ("card_style", 19),
                                ("layout", 20),
                                ("card_columns", 21),
                                ("background_color", 22),
                                ("border_size", 23),
                                ("accent_size", 24),
                                ("padding", 25),
                                ("padding_top", 26),
                                ("padding_bottom", 27),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_size": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("cards", 17), ("config", 28)]], {"label": "Cards Block"}),
                    30: ("pages.shared_blocks.CollapsedHTMLBlock", (), {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional description text displayed alongside the buttons.", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7), ("config", 10)]],
                        {"label": "Button", "required": False},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {"default": [], "label": "Actions", "max_num": 2}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this group.', "required": False},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline")],
                            "help_text": "Layout of the buttons. Inline places description and buttons side-by-side.",
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Condition that determines if this block should render. eg: defined by the frontend.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [[("analytics_label", 34), ("layout", 35), ("rendering_condition", 36)]],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("description", 31), ("actions", 33), ("config", 37)]], {}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("aria_label", 2), ("target", 7)]],
                        {"label": "Link", "required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": [], "label": "Links"}),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("button", "Button"), ("text", "Text")],
                            "help_text": "Button renders the links as buttons (default); Text renders them as plain links.",
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("blue", "Blue"), ("deep-green", "Deep Green")],
                            "help_text": "The color of the link buttons. Default white.",
                        },
                    ),
                    43: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Custom color for the links. Must be hex eg: #ff0000."},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                            "help_text": "Size of the links. Default medium.",
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("horizontal", "Horizontal"), ("vertical", "Vertical")],
                            "help_text": "Layout direction of the links. Default horizontal.",
                        },
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("style", 41),
                                ("color", 42),
                                ("custom_color", 43),
                                ("size", 44),
                                ("layout", 45),
                                ("analytics_label", 34),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "color": {"max_num": 1},
                                "custom_color": {"max_num": 1},
                                "layout": {"max_num": 1},
                                "size": {"max_num": 1},
                                "style": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    47: ("wagtail.blocks.StructBlock", [[("links", 40), ("config", 46)]], {}),
                    48: (
                        "pages.custom_blocks.APIImageChooserBlock",
                        (),
                        {"help_text": "Optional profile image for the quote.", "required": False},
                    ),
                    49: ("openstax.api_fields.APIRichTextBlock", (), {"help_text": "The quote content."}),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person or entity to attribute the quote to."},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Additional title or label about the quotee.", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image-left", "Image Left"),
                                ("image-right", "Image Right"),
                                ("image-top", "Image Top"),
                                ("compact", "Compact"),
                            ],
                            "help_text": 'How the image and text are arranged. Compact is a small image + short text ("did you know") treatment. Default Image Left.',
                        },
                    ),
                    53: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Accent color for the quote. Must be hex eg: #ff0000."},
                    ),
                    54: (
                        "wagtail.blocks.StreamBlock",
                        [[("layout", 52), ("accent_color", 53)]],
                        {
                            "block_counts": {"accent_color": {"max_num": 1}, "layout": {"max_num": 1}},
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 48), ("content", 49), ("name", 50), ("title", 51), ("config", 54)]],
                        {},
                    ),
                    56: ("wagtail.blocks.CharBlock", (), {"help_text": "The statistic to display large, e.g. 8M+."}),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional supporting text shown below the number.", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("blue", "Blue"), ("green", "Green"), ("orange", "Orange")],
                            "help_text": "Brand color for the number. Defaults to the inherited text color.",
                            "required": False,
                        },
                    ),
                    59: ("wagtail.blocks.StructBlock", [[("number", 56), ("caption", 57), ("color", 58)]], {}),
                    60: ("wagtail.blocks.StreamBlock", [[("big_number", 59)]], {"required": False}),
                    61: ("wagtail.blocks.StructBlock", [[("content", 60)]], {}),
                    62: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "The visible text of the question (does not collapse).", "required": True},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Not visible to user, must be unique in this FAQ.", "required": True},
                    ),
                    64: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "The answer to the question, is hidden until the question is expanded.",
                            "required": True,
                        },
                    ),
                    65: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Not sure this does anything.", "required": False},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describes the table; rendered as a <caption> for accessibility.",
                            "required": False,
                        },
                    ),
                    67: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("text", "Text"), ("number", "Number"), ("date", "Date")],
                            "help_text": "How readers sort this column. Default text.",
                            "required": False,
                        },
                    ),
                    69: ("wagtail.blocks.StructBlock", [[("header", 67), ("type", 68)]], {}),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": [], "label": "Columns"}),
                    71: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "Rich-text cell content. Ignored when a Call To Action is set.",
                            "required": False,
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("content", 71), ("cta", 12)]], {}),
                    73: ("wagtail.blocks.ListBlock", (72,), {"default": []}),
                    74: ("wagtail.blocks.StructBlock", [[("cells", 73)]], {}),
                    75: ("wagtail.blocks.ListBlock", (74,), {"default": [], "label": "Rows"}),
                    76: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.Subject",),
                        {"help_text": "Only books in this subject. Leave empty for all subjects.", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("live", "Live"),
                                ("coming_soon", "Coming Soon"),
                                ("new_edition_available", "New Edition Forthcoming"),
                                ("deprecated", "Deprecated"),
                            ],
                            "help_text": "Only books in this state. Leave empty for all listed books.",
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title A–Z"),
                                ("-publish_date", "Newest first"),
                                ("publish_date", "Oldest first"),
                            ],
                            "help_text": "Row order. Default Title A–Z.",
                            "required": False,
                        },
                    ),
                    79: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 100.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title"),
                                ("title_link", "Title (linked to book page)"),
                                ("subjects", "Subjects"),
                                ("publish_date", "Publish date"),
                                ("book_state", "State"),
                                ("cover", "Cover image"),
                                ("is_ap", "AP"),
                                ("read_online", "Read online (link)"),
                            ]
                        },
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Column header shown to readers. Defaults to the field label.",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Overrides how the value is shown and sorted. Default per field.",
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 80), ("header", 81), ("type", 82)]],
                        {"label": "Column"},
                    ),
                    84: ("wagtail.blocks.ListBlock", (83,), {"label": "Columns", "min_num": 1}),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 76), ("book_state", 77), ("order", 78), ("limit", 79), ("columns", 84)]],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Only articles with this subject, e.g. Science. Matches the article's subjects list.",
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Only articles with this tag (exact tag name).", "required": False},
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("-date", "Newest first"),
                                ("date", "Oldest first"),
                                ("heading", "Heading A–Z"),
                            ],
                            "help_text": "Row order. Default newest first.",
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Maximum number of rows. Default 20.",
                            "max_value": 500,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("heading", "Heading"),
                                ("heading_link", "Heading (linked to article)"),
                                ("subheading", "Subheading"),
                                ("author", "Author"),
                                ("date", "Post date"),
                                ("image", "Article image"),
                            ]
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 90), ("header", 81), ("type", 82)]],
                        {"label": "Column"},
                    ),
                    92: ("wagtail.blocks.ListBlock", (91,), {"label": "Columns", "min_num": 1}),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [[("subject", 86), ("tag", 87), ("order", 88), ("limit", 89), ("columns", 92)]],
                        {},
                    ),
                    94: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.Subject",),
                        {
                            "help_text": "All books in this Higher Ed subject. Leave empty for all subjects.",
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("snippets.K12Subject",),
                        {
                            "help_text": "All books in this K12 subject area. Combine with the subject above to require both.",
                            "required": False,
                        },
                    ),
                    96: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["books.Book"]}),
                    97: (
                        "wagtail.blocks.ListBlock",
                        (96,),
                        {
                            "help_text": "Pick individual books instead. When set, the subject filters above are ignored. Leave empty to use the subjects above — or, with no filters at all, every book. A resource shared across several books is listed once, with all its book names.",
                            "label": "Specific books",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("instructor", "Instructor resources"), ("student", "Student resources")]},
                    ),
                    99: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("all", "All"), ("k12", "K12 only")],
                            "help_text": 'K12 only limits rows to resources flagged "Display on K12".',
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": pages.table_block.resource_category_choices,
                            "help_text": "Only resources with this category. Leave blank for all categories.",
                            "required": False,
                        },
                    ),
                    101: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("book", "Book(s)"),
                                ("heading", "Resource"),
                                ("description", "Description"),
                                ("link", "Link"),
                                ("coming_soon", "Coming soon"),
                                ("k12", "K12"),
                                ("unlocked", "Unlocked"),
                                ("resource_category", "Category"),
                            ]
                        },
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 101), ("header", 81), ("type", 82)]],
                        {"label": "Column"},
                    ),
                    103: ("wagtail.blocks.ListBlock", (102,), {"label": "Columns", "min_num": 1}),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("subject", 94),
                                ("k12_subject", 95),
                                ("books", 97),
                                ("resource_type", 98),
                                ("audience", 99),
                                ("resource_category", 100),
                                ("columns", 103),
                            ]
                        ],
                        {},
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("he", "Higher Ed subjects"), ("k12", "K12 subjects")]},
                    ),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "K12 only: limit to a category, e.g. Math.", "required": False},
                    ),
                    107: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("name", "Subject"),
                                ("category", "Category"),
                                ("color", "Color"),
                                ("icon", "Icon"),
                                ("link", "Link (K12 subject pages)"),
                            ]
                        },
                    ),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 107), ("header", 81), ("type", 82)]],
                        {"label": "Column"},
                    ),
                    109: ("wagtail.blocks.ListBlock", (108,), {"label": "Columns", "min_num": 1}),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("variant", 105), ("k12_category", 106), ("columns", 109)]],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be a relative path starting with /apps/cms/api/."},
                            "help_text": "Relative CMS API path including query string, e.g. /apps/cms/api/v2/pages/?type=books.Book&fields=title,cover_url&book_state=live. Must start with /apps/cms/api/. No absolute URLs — they break across environments.",
                            "label": "Endpoint path",
                            "regex": "^/apps/cms/api/\\S*$",
                        },
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "items",
                            "help_text": 'JSON key holding the list of rows. Default "items" (the Wagtail API shape); clear it if the response is a bare list.',
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Dotted path into each item, e.g. title or meta.slug.", "required": True},
                    ),
                    114: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Column header. Defaults to the field path.", "required": False},
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("number", "Number"),
                                ("date", "Date"),
                                ("link", "Link"),
                                ("image", "Image"),
                            ],
                            "help_text": "Cell type. Default text.",
                            "required": False,
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 113), ("header", 114), ("type", 115)]],
                        {"label": "Column"},
                    ),
                    117: ("wagtail.blocks.ListBlock", (116,), {"label": "Columns", "min_num": 1}),
                    118: ("wagtail.blocks.StructBlock", [[("path", 111), ("items_key", 112), ("columns", 117)]], {}),
                    119: (
                        "wagtail.blocks.StreamBlock",
                        [[("books", 85), ("news", 93), ("book_resources", 104), ("subjects", 110), ("endpoint", 118)]],
                        {
                            "help_text": "Fill the table from CMS content instead of manual rows. When set, manual Columns and Rows are ignored.",
                            "label": "Data source",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    120: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Shade alternating rows. Default shade unless Row Colors is set.",
                        },
                    ),
                    121: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ffffff,#f2f2f2."},
                            "help_text": "Comma-separated hex colors cycled across body rows, e.g. #ffffff,#f2f2f2. Overrides the default zebra shade.",
                            "label": "Row Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("off", "Off"), ("on", "On")], "help_text": "Tighter cell padding."},
                    ),
                    123: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Let readers sort by clicking column headers.",
                        },
                    ),
                    124: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("off", "Off"), ("on", "On")],
                            "help_text": "Show a text box that filters rows by their content.",
                        },
                    ),
                    125: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "1-based column number the table is sorted by on load.", "min_value": 1},
                    ),
                    126: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("asc", "Ascending"), ("desc", "Descending")],
                            "help_text": "Direction for the default sort. Default ascending.",
                        },
                    ),
                    127: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": 'Show at most this many rows, with a "Show more" control for the rest.',
                            "min_value": 1,
                        },
                    ),
                    128: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown when the table has no rows (e.g. a dynamic source returns nothing).",
                            "required": False,
                        },
                    ),
                    129: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid id."},
                            "help_text": "HTML id of this element. not visible to users, but is visible in urls and is used to link to a certain part of the page with an anchor link. eg: cool_section",
                            "regex": "^[a-zA-Z0-9_-]+$",
                        },
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("striped", 120),
                                ("row_colors", 121),
                                ("condensed", 122),
                                ("sortable", 123),
                                ("filterable", 124),
                                ("default_sort_column", 125),
                                ("default_sort_direction", 126),
                                ("row_limit", 127),
                                ("empty_message", 128),
                                ("id", 129),
                            ]
                        ],
                        {
                            "block_counts": {
                                "condensed": {"max_num": 1},
                                "default_sort_column": {"max_num": 1},
                                "default_sort_direction": {"max_num": 1},
                                "empty_message": {"max_num": 1},
                                "filterable": {"max_num": 1},
                                "id": {"max_num": 1},
                                "row_colors": {"max_num": 1},
                                "row_limit": {"max_num": 1},
                                "sortable": {"max_num": 1},
                                "striped": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 66), ("columns", 70), ("rows", 75), ("data_source", 119), ("config", 130)]],
                        {},
                    ),
                    132: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": True}),
                    133: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    134: ("wagtail.blocks.StructBlock", [[("image", 132), ("alt_text", 133)]], {"label": "Image"}),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [[("table", 131), ("image", 134), ("text", 0)]],
                        {
                            "collapsed": True,
                            "help_text": "Optional table, image, or extra text shown as part of the answer.",
                            "label": "Additional content",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 62), ("slug", 63), ("answer", 64), ("document", 65), ("content", 135)]],
                        {},
                    ),
                    137: ("wagtail.blocks.StreamBlock", [[("faq", 136)]], {}),
                    138: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible text of the item.", "required": True},
                    ),
                    139: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {"help_text": "Hidden until the item is expanded.", "required": True},
                    ),
                    140: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Accent color for this item: the expand/collapse icon and divider. Leave blank for the default."
                        },
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [[("accent_color", 140)]],
                        {"block_counts": {"accent_color": {"max_num": 1}}, "collapsed": True, "required": False},
                    ),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [[("header", 138), ("content", 139), ("id", 129), ("config", 141)]],
                        {},
                    ),
                    143: ("wagtail.blocks.ListBlock", (142,), {"label": "Items"}),
                    144: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("2", "H2"), ("3", "H3"), ("4", "H4")],
                            "help_text": "Heading level for each item, for the document outline and screen-reader navigation. Default H3.",
                        },
                    ),
                    145: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("false", "No"), ("true", "Yes")],
                            "help_text": "Allow more than one item to be open at the same time. Default No.",
                        },
                    ),
                    146: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Adds a colored border above the whole accordion."},
                    ),
                    147: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading_level", 144), ("allow_multiple", 145), ("top_border_color", 146)]],
                        {
                            "block_counts": {
                                "allow_multiple": {"max_num": 1},
                                "heading_level": {"max_num": 1},
                                "top_border_color": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    148: ("wagtail.blocks.StructBlock", [[("items", 143), ("config", 147)]], {"label": "Accordion"}),
                    149: ("pages.custom_blocks.BookBlock", (), {"required": True}),
                    150: ("wagtail.blocks.ListBlock", (149,), {}),
                    151: ("wagtail.blocks.StructBlock", [[("books", 150)]], {"label": "Books Block"}),
                    152: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional title shown above the grid.", "required": False},
                    ),
                    153: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Role, e.g. "Director of Research".', "required": False},
                    ),
                    154: ("pages.custom_blocks.APIImageChooserBlock", (), {"required": False}),
                    155: ("wagtail.blocks.TextBlock", (), {"help_text": "Shown on the card.", "required": False}),
                    156: (
                        "openstax.api_fields.APIRichTextBlock",
                        (),
                        {
                            "help_text": "If set, the card becomes clickable and opens an expanded modal.",
                            "required": False,
                        },
                    ),
                    157: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("orcid", "ORCID"),
                                ("website", "Website"),
                                ("email", "Email"),
                                ("scholar", "Google Scholar"),
                                ("x", "X"),
                            ],
                            "help_text": "Determines the icon shown for this link.",
                        },
                    ),
                    158: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Full URL, or for the Email type a mailto: link or email address.",
                            "required": True,
                        },
                    ),
                    159: ("wagtail.blocks.StructBlock", [[("type", 157), ("url", 158)]], {}),
                    160: ("wagtail.blocks.ListBlock", (159,), {"default": [], "required": False}),
                    161: ("pages.custom_blocks.PersonTagChooserBlock", ("pages.PersonTag",), {}),
                    162: ("wagtail.blocks.ListBlock", (161,), {"default": [], "required": False}),
                    163: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 67),
                                ("title", 153),
                                ("image", 154),
                                ("short_bio", 155),
                                ("full_bio", 156),
                                ("links", 160),
                                ("tags", 162),
                            ]
                        ],
                        {},
                    ),
                    164: ("wagtail.blocks.ListBlock", (163,), {}),
                    165: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Number of columns for the grid. default auto.", "max_value": 6, "min_value": 1},
                    ),
                    166: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Width of individual cards. default 27.", "min_value": 0},
                    ),
                    167: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for a card accent, cycled per card. eg: #ff0000,#00ff00,#0000ff.",
                            "label": "Accent Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    168: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "Must be comma-separated hex colors. eg: #ff0000,#00ff00."},
                            "help_text": "Comma-separated hex colors for card divider lines, cycled per card. eg: #ff0000,#00ff00.",
                            "label": "Divider Colors",
                            "regex": "^#[0-9a-fA-F]{6}(\\s*,\\s*#[0-9a-fA-F]{6})*$",
                            "required": False,
                        },
                    ),
                    169: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color for the cards. Must be hex eg: #ff0000."},
                    ),
                    170: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Border width in px.", "min_value": 0}),
                    171: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("card_columns", 165),
                                ("card_style", 19),
                                ("card_size", 166),
                                ("accent_colors", 167),
                                ("divider_colors", 168),
                                ("background_color", 169),
                                ("border_size", 170),
                                ("id", 129),
                            ]
                        ],
                        {
                            "block_counts": {
                                "accent_colors": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "card_columns": {"max_num": 1},
                                "card_size": {"max_num": 1},
                                "card_style": {"max_num": 1},
                                "divider_colors": {"max_num": 1},
                                "id": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    172: ("wagtail.blocks.StructBlock", [[("heading", 152), ("people", 164), ("config", 171)]], {}),
                    173: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 29),
                                ("text", 0),
                                ("html", 30),
                                ("cta_block", 38),
                                ("links_group", 47),
                                ("quote", 55),
                                ("big_number", 59),
                                ("big_numbers", 61),
                                ("faq", 137),
                                ("accordion", 148),
                                ("book_list", 151),
                                ("person", 172),
                                ("table", 131),
                            ]
                        ],
                        {},
                    ),
                    174: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the well. Must be hex eg: #ff0000."},
                    ),
                    175: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Sets the gradient end color. Must be hex eg: #ff0000."},
                    ),
                    176: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to right", "To Right"),
                                ("to left", "To Left"),
                                ("to top", "To Top"),
                                ("to bottom", "To Bottom"),
                                ("to top right", "To Top Right"),
                                ("to top left", "To Top Left"),
                                ("to bottom right", "To Bottom Right"),
                                ("to bottom left", "To Bottom Left"),
                            ],
                            "help_text": "Direction of the gradient. Default to right.",
                        },
                    ),
                    177: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius in pixels. default 0.", "min_value": 0},
                    ),
                    178: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color. Must be hex eg: #ff0000."},
                    ),
                    179: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size in pixels. default 0.", "min_value": 0},
                    ),
                    180: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding inside the well. default 0.", "min_value": 0},
                    ),
                    181: ("wagtail.blocks.IntegerBlock", (), {"help_text": "Margin outside the well. default 0."}),
                    182: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Pulls the well up by this many pixels (negative margin-top). default 0."},
                    ),
                    183: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Width of the well. Must be valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    184: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment inside the well. Default left.",
                        },
                    ),
                    185: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this well.', "required": False},
                    ),
                    186: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 174),
                                ("gradient_color", 175),
                                ("gradient_direction", 176),
                                ("border_radius", 177),
                                ("border_color", 178),
                                ("border_size", 179),
                                ("padding", 180),
                                ("margin", 181),
                                ("pull_up", 182),
                                ("width", 183),
                                ("text_alignment", 184),
                                ("analytics_label", 185),
                                ("id", 129),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_color": {"max_num": 1},
                                "border_radius": {"max_num": 1},
                                "border_size": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "margin": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "pull_up": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    187: ("wagtail.blocks.StructBlock", [[("content", 173), ("config", 186)]], {"label": "Well"}),
                    188: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("cards_block", 29),
                                ("text", 0),
                                ("html", 30),
                                ("cta_block", 38),
                                ("links_group", 47),
                                ("quote", 55),
                                ("big_number", 59),
                                ("big_numbers", 61),
                                ("faq", 137),
                                ("accordion", 148),
                                ("book_list", 151),
                                ("person", 172),
                                ("table", 131),
                                ("well", 187),
                            ]
                        ],
                        {},
                    ),
                    189: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("top_left", "Top Left"),
                                ("top_right", "Top Right"),
                                ("bottom_left", "Bottom Left"),
                                ("bottom_right", "Bottom Right"),
                            ],
                            "help_text": "Controls if the image is on the left or right side of the content, and if it prefers to be at the top, center, or bottom of the available space.",
                        },
                    ),
                    190: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {
                            "help_text": "Sets the background color of the section. value must be hex eg: #ff0000. Default grey."
                        },
                    ),
                    191: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above and below this section. default 0.", "min_value": 0},
                    ),
                    192: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space above this section. default 0.", "min_value": 0},
                    ),
                    193: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Creates space below this section. default 0.", "min_value": 0},
                    ),
                    194: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Configures text alignment within the container. Default Left.",
                        },
                    ),
                    195: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Sets the "analytics nav" field for links within this section.',
                            "required": False,
                        },
                    ),
                    196: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border radius for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    197: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Border color for the hero image. Must be hex eg: #ff0000."},
                    ),
                    198: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border size for the hero image in pixels. default 0.", "min_value": 0},
                    ),
                    199: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "How much the image overhangs the section boundary. Must be a valid css measurement. eg: 30px, 50%, 10rem.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    200: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("image_alignment", 189),
                                ("id", 129),
                                ("background_color", 190),
                                ("gradient_color", 175),
                                ("gradient_direction", 176),
                                ("padding", 191),
                                ("padding_top", 192),
                                ("padding_bottom", 193),
                                ("text_alignment", 194),
                                ("analytics_label", 195),
                                ("image_border_radius", 196),
                                ("image_border_color", 197),
                                ("image_border_size", 198),
                                ("image_overhang", 199),
                                ("rendering_condition", 36),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "image_alignment": {"max_num": 1},
                                "image_border_color": {"max_num": 1},
                                "image_border_radius": {"max_num": 1},
                                "image_border_size": {"max_num": 1},
                                "image_overhang": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    201: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 188), ("image", 154), ("image_alt", 133), ("config", 200)]],
                        {},
                    ),
                    202: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior of this section. Default none.",
                        },
                    ),
                    203: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("id", 129),
                                ("background_color", 190),
                                ("gradient_color", 175),
                                ("gradient_direction", 176),
                                ("padding", 191),
                                ("padding_top", 192),
                                ("padding_bottom", 193),
                                ("text_alignment", 194),
                                ("analytics_label", 195),
                                ("flex", 202),
                                ("rendering_condition", 36),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "rendering_condition": {"max_num": 1},
                                "text_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    204: ("wagtail.blocks.StructBlock", [[("content", 188), ("config", 203)]], {}),
                    205: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the columns container. Must be hex eg: #ff0000."},
                    ),
                    206: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding for the columns container. default 0.", "min_value": 0},
                    ),
                    207: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding above the columns container. default 0.", "min_value": 0},
                    ),
                    208: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Padding below the columns container. default 0.", "min_value": 0},
                    ),
                    209: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("flex", "Flex"), ("flex_grow", "Flex Grow"), ("flex_shrink", "Flex Shrink")],
                            "help_text": "Flex behavior. Default none.",
                        },
                    ),
                    210: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": 'Sets the "analytics nav" field for links within this block.', "required": False},
                    ),
                    211: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Gap between the two columns in pixels. default 0.", "min_value": 0},
                    ),
                    212: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the left column. default 1.", "min_value": 1},
                    ),
                    213: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Relative size of the right column. default 1.", "min_value": 1},
                    ),
                    214: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("background_color", 205),
                                ("gradient_color", 175),
                                ("gradient_direction", 176),
                                ("padding", 206),
                                ("padding_top", 207),
                                ("padding_bottom", 208),
                                ("flex", 209),
                                ("analytics_label", 210),
                                ("id", 129),
                                ("gap", 211),
                                ("left_size", 212),
                                ("right_size", 213),
                            ]
                        ],
                        {
                            "block_counts": {
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "flex": {"max_num": 1},
                                "gap": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "left_size": {"max_num": 1},
                                "padding": {"max_num": 1},
                                "padding_bottom": {"max_num": 1},
                                "padding_top": {"max_num": 1},
                                "right_size": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    215: (
                        "wagtail.blocks.StructBlock",
                        [[("left_content", 188), ("right_content", 188), ("config", 214)]],
                        {"label": "Columns"},
                    ),
                    216: ("pages.custom_blocks.APIImageChooserBlock", (), {}),
                    217: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("content_left", "Left side of content."),
                                ("content_right", "Right side of content."),
                                ("body_left", "Left side of window."),
                                ("body_right", "Right side of window."),
                            ],
                            "help_text": 'Sets the horizontal alignment of the image. can be further customized with the "Offset..." configurations. Default is Left side of window.',
                        },
                    ),
                    218: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the width of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    219: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Specifies the height of the image. Percentages are relative to the container (body or content, depending on alignment option). Must be valid css measurement. eg: 30px, 50%, 10rem. Default is the size of the image.",
                            "regex": "^[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    220: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image up or down. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is -50%, which moves the image up by half its width (centering it vertically on the divider).",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    221: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {"invalid": "not a valid size."},
                            "help_text": "Moves the image left or right. Percentages are relative to the image size. Must be valid css measurement. eg: 30px, 50%, 10rem. Default is no offset, which means the image's outer edge will align with the container's edge for left and right alignment. or it'll be perfectly centered for centered alignment.",
                            "regex": "^\\-?[0-9]+(px|%|rem)$",
                            "required": False,
                        },
                    ),
                    222: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alignment", 217),
                                ("width", 218),
                                ("height", 219),
                                ("offset_vertical", 220),
                                ("offset_horizontal", 221),
                            ]
                        ],
                        {
                            "block_counts": {
                                "alignment": {"max_num": 1},
                                "height": {"max_num": 1},
                                "offset_horizontal": {"max_num": 1},
                                "offset_vertical": {"max_num": 1},
                                "width": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    223: ("wagtail.blocks.StructBlock", [[("image", 216), ("config", 222)]], {}),
                    224: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The visible label for this tab.", "required": True},
                    ),
                    225: (
                        "wagtail.blocks.StreamBlock",
                        [[("hero", 201), ("section", 204), ("columns", 215), ("divider", 223), ("html", 30)]],
                        {},
                    ),
                    226: ("wagtail.blocks.StructBlock", [[("label", 224), ("content", 225)]], {}),
                    227: ("wagtail.blocks.ListBlock", (226,), {"label": "Tabs"}),
                    228: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Alignment of the tab labels. Default left.",
                        },
                    ),
                    229: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Color of the active tab indicator. Must be hex eg: #ff0000."},
                    ),
                    230: (
                        "pages.shared_blocks.OpenStaxColorBlock",
                        (),
                        {"help_text": "Background color of the tabbed content area. Must be hex eg: #ff0000."},
                    ),
                    231: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Index of the default active tab (0-based). default 0.", "min_value": 0},
                    ),
                    232: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Border width for the tab bar in pixels. default 0.", "min_value": 0},
                    ),
                    233: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tab_alignment", 228),
                                ("active_color", 229),
                                ("background_color", 230),
                                ("gradient_color", 175),
                                ("gradient_direction", 176),
                                ("default_tab", 231),
                                ("analytics_label", 210),
                                ("border_width", 232),
                                ("id", 129),
                            ]
                        ],
                        {
                            "block_counts": {
                                "active_color": {"max_num": 1},
                                "analytics_label": {"max_num": 1},
                                "background_color": {"max_num": 1},
                                "border_width": {"max_num": 1},
                                "default_tab": {"max_num": 1},
                                "gradient_color": {"max_num": 1},
                                "gradient_direction": {"max_num": 1},
                                "id": {"max_num": 1},
                                "tab_alignment": {"max_num": 1},
                            },
                            "collapsed": True,
                            "required": False,
                        },
                    ),
                    234: (
                        "wagtail.blocks.StructBlock",
                        [[("tabs", 227), ("config", 233)]],
                        {"label": "Tabbed Content"},
                    ),
                },
            ),
        ),
    ]
