# Generated by Django 2.2.5 on 2019-10-08 19:31

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pages', '0205_auto_20190925_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorFestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('banner_headline', models.CharField(max_length=255)),
                ('banner_content', wagtail.core.fields.RichTextField()),
                ('register', wagtail.core.fields.StreamField([('box', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('address', wagtail.core.blocks.RichTextBlock()), ('button_url', wagtail.core.blocks.URLBlock()), ('button_text', wagtail.core.blocks.CharBlock())])))])),
                ('navigator', wagtail.core.fields.StreamField([('menu_item', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.PageChooserBlock())])))], null=True)),
                ('page_panels', wagtail.core.fields.StreamField([('panel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('superheading', wagtail.core.blocks.CharBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock()), ('identifier', wagtail.core.blocks.CharBlock(help_text='Used by the frontend for Google Analytics.', required=False))])), ('video', wagtail.core.blocks.RawHTMLBlock()), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('alignment', pages.models.ImageFormatChoiceBlock()), ('identifier', wagtail.core.blocks.CharBlock(help_text='Used by the frontend for Google Analytics.', required=False))])), ('headline', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock())])))])))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
