# Generated by Django 6.0.6 on 2026-08-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0206_alter_rootpage_body"),
        ("pages", "0207_alter_assignable_faqs_alter_faq_questions_and_more"),
    ]

    operations = []
