# Generated by Django 2.2.5 on 2019-10-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('pages', '0215_auto_20191021_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printorder',
            old_name='isbn_cta',
            new_name='us_isbn_cta',
        ),
        migrations.RenameField(
            model_name='printorder',
            old_name='isbn_download',
            new_name='us_isbn_download',
        ),
        migrations.AddField(
            model_name='printorder',
            name='canadian_isbn_cta',
            field=models.CharField(default='Download a list of ISBN numbers', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='canadian_isbn_download',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
