# Generated by Django 2.2.8 on 2020-01-21 20:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0219_auto_20200121_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='featured_providers',
            field=wagtail.core.fields.StreamField([('provider', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock()), ('canadian', wagtail.core.blocks.BooleanBlock(required=False))], icon='document'))], null=True),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='providers',
            field=wagtail.core.fields.StreamField([('provider', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('blurb', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock()), ('canadian', wagtail.core.blocks.BooleanBlock(required=False))], icon='document'))]),
        ),
    ]
