# Generated by Django 2.2.8 on 2020-02-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0222_partnerspage_partner_list_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerspage',
            name='partner_list_label',
        ),
    ]
