# Generated by Django 2.2.8 on 2020-02-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0223_remove_partnerspage_partner_list_label'),
        ('pages', '0222_delete_ecosystemallies'),
    ]

    operations = [
    ]
