# Generated by Django 3.0.4 on 2020-06-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0231_auto_20200511_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='canadian_isbn_cta',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='canadian_isbn_download',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='us_isbn_cta',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='us_isbn_download',
        ),
    ]
