# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 16:59
from __future__ import unicode_literals

from django.db import migrations
from wagtail.wagtailredirects.models import Redirect
from django.db import connection
import os
migration_path = os.path.dirname(os.path.realpath(__file__))


def add_osc_shortcodes(*args, **kwargs):
    cursor = connection.cursor()
    cursor.execute(
        "ALTER TABLE wagtailredirects_redirect ALTER redirect_link TYPE character varying(255);")
    short_code_path = os.path.join(
        migration_path, 'wagtailredirects_redirect.csv')
    cursor.execute(
        "COPY wagtailredirects_redirect FROM '{0}' DELIMITER ',' CSV HEADER;".format(short_code_path))


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailredirects', '0005_capitalizeverbose'),
    ]

    operations = [
        migrations.RunPython(add_osc_shortcodes),
    ]
