from .models import School, AdoptionOpportunityRecord, Partner

from rest_framework import serializers


class SchoolSerializer(serializers.ModelSerializer):

    class Meta:
        model = School
        fields = ('id',
                  'name',
                  'phone',
                  'website',
                  'type',
                  'adoption_date',
                  'key_institutional_partner',
                  'achieving_the_dream_school',
                  'hbcu',
                  'texas_higher_ed',
                  'undergraduate_enrollment',
                  'pell_grant_recipients',
                  'percent_students_pell_grant',
                  'current_year_students',
                  'all_time_students',
                  'current_year_savings',
                  'all_time_savings',
                  'physical_country',
                  'physical_street',
                  'physical_city',
                  'physical_state_province',
                  'physical_zip_postal_code',
                  'long',
                  'lat',
                  'testimonial',)


class AdoptionOpportunityRecordSerializer(serializers.ModelSerializer):
    class Meta:
        model = AdoptionOpportunityRecord
        fields = ('opportunity_id',
                  'account_id',
                  'book_name',
                  'email',
                  'school',
                  'yearly_students',
                  'updated')
        read_only_fields = ('opportunity_id',
                  'account_id',
                  'book_name',
                  'email',
                  'school',
                  'yearly_students')

class PartnerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Partner
        fields = ('salesforce_id',
        'partner_name',
        'partner_type',
        'partner_description',
        'short_partner_description',
        'books',
        'landing_page',
        'verified_by_instructor',
        'integrated',
        'affordability_cost',
        'affordability_institutional',
        'app_available',
        'adaptivity_adaptive_presentation',
        'adaptivity_affective_state',
        'adaptivity_breadth_and_depth',
        'adaptivity_customized_path',
        'adaptivity_instructor_control',
        'adaptivity_quantitative_randomization',
        'adaptivity_varied_level',
        'admin_calendar_links',
        'admin_online_submission',
        'admin_realtime_progress',
        'admin_shared_students',
        'admin_syllabus',
        'assigment_outside_resources',
        'assignment_editing',
        'assignment_multimedia',
        'assignment_multiple_quantitative',
        'assignment_pretest',
        'address_Longitude',
        'assignment_scientific_structures',
        'assignment_summative_assessments',
        'autonomy_digital_badges',
        'autonomy_on_demand_extras',
        'autonomy_self_reflection',
        'collaboration_peer_feedback',
        'collaboration_peer_interaction',
        'collaboration_teacher_learner_contact',
        'collaboration_tutor',
        'content_batch_uploads',
        'content_resource_sharing',
        'content_sharing_among_courses',
        'customization_assessement_repository',
        'customization_create_learning_outcomes',
        'customization_reorder_content',
        'customization_reorder_learning_outcomes',
        'feedback_early_warning',
        'feedback_knowledge_gaps',
        'feedback_learner_progress_tasks',
        'feedback_multipart',
        'feedback_understanding',
        'grading_change_scores',
        'grading_class_and_student_level',
        'grading_group_work',
        'grading_learning_portfolio',
        'grading_rubric_based',
        'grading_tolerances_sig_fig',
        'interactivity_annotate',
        'interactivity_different_representations',
        'interactivity_gaming',
        'interactivity_previous_knowledge',
        'interactivity_simulations',
        'interactivity_varying_means',
        'LMS_analytics',
        'LMS_sends_grades',
        'LMS_SSO',
        'measure_alternate_assessment',
        'measure_assessments_in_most',
        'measure_mapping',
        'reporting_competency',
        'reporting_student_workload',
        'scaffolding_hints',
        'scaffolding_learner_explanations'
        'scaffolding_mental_practice',
        'scaffolding_narrative',
        'scaffolding_social_intervention',
        'usability_design_orients_users',
        'usability_glossary',
        'usability_partial_progress',
        'accessibility_language_UI'
        'accessibility_language_content',
        'accessibility_VPAT',
        'accessibility_WCAG',
        'accessibility_universal_design' )

        read_only_fields = ('salesforce_id',
        'partner_name',
        'partner_type',
        'partner_description',
        'short_partner_description',
        'books',
        'landing_page',
        'verified_by_instructor',
        'integrated',
        'affordability_cost',
        'affordability_institutional',
        'app_available',
        'adaptivity_adaptive_presentation',
        'adaptivity_affective_state',
        'adaptivity_breadth_and_depth',
        'adaptivity_customized_path',
        'adaptivity_instructor_control',
        'adaptivity_quantitative_randomization',
        'adaptivity_varied_level',
        'admin_calendar_links',
        'admin_online_submission',
        'admin_realtime_progress',
        'admin_shared_students',
        'admin_syllabus',
        'assigment_outside_resources',
        'assignment_editing',
        'assignment_multimedia',
        'assignment_multiple_quantitative',
        'assignment_pretest',
        'address_Longitude',
        'assignment_scientific_structures',
        'assignment_summative_assessments',
        'autonomy_digital_badges',
        'autonomy_on_demand_extras',
        'autonomy_self_reflection',
        'collaboration_peer_feedback',
        'collaboration_peer_interaction',
        'collaboration_teacher_learner_contact',
        'collaboration_tutor',
        'content_batch_uploads',
        'content_resource_sharing',
        'content_sharing_among_courses',
        'customization_assessement_repository',
        'customization_create_learning_outcomes',
        'customization_reorder_content',
        'customization_reorder_learning_outcomes',
        'feedback_early_warning',
        'feedback_knowledge_gaps',
        'feedback_learner_progress_tasks',
        'feedback_multipart',
        'feedback_understanding',
        'grading_change_scores',
        'grading_class_and_student_level',
        'grading_group_work',
        'grading_learning_portfolio',
        'grading_rubric_based',
        'grading_tolerances_sig_fig',
        'interactivity_annotate',
        'interactivity_different_representations',
        'interactivity_gaming',
        'interactivity_previous_knowledge',
        'interactivity_simulations',
        'interactivity_varying_means',
        'LMS_analytics',
        'LMS_sends_grades',
        'LMS_SSO',
        'measure_alternate_assessment',
        'measure_assessments_in_most',
        'measure_mapping',
        'reporting_competency',
        'reporting_student_workload',
        'scaffolding_hints',
        'scaffolding_learner_explanations'
        'scaffolding_mental_practice',
        'scaffolding_narrative',
        'scaffolding_social_intervention',
        'usability_design_orients_users',
        'usability_glossary',
        'usability_partial_progress',
        'accessibility_language_UI'
        'accessibility_language_content',
        'accessibility_VPAT',
        'accessibility_WCAG',
        'accessibility_universal_design' )