# Generated by Django 5.2.12 on 2026-06-05 03:31

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='PageEmbedding',
            fields=[
                ('index_name', models.CharField(max_length=255)),
                ('document_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
