# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 19:10
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

def add_faculty_group(*args,**kwargs):
    Group.objects.create(name='Faculty') 

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_faculty_group),
    ]
