# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpendingverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpendingverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPendingVerification',
        ),
    ]
