#!/usr/bin/env bash

DJANGO_SETTINGS_MODULE=openstax.settings.docker python3 manage.py migrate
DJANGO_SETTINGS_MODULE=openstax.settings.docker python3 manage.py createsuperuser
DJANGO_SETTINGS_MODULE=openstax.settings.docker python3 manage.py runserver 0.0.0.0:8000
