# Generated by Django 3.0.4 on 2021-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20210607_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thankyounote',
            name='user_info',
        ),
        migrations.AddField(
            model_name='thankyounote',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thankyounote',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thankyounote',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
