# Generated by Django 3.2.4 on 2021-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20210609_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankyounote',
            name='consent_to_share_or_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thankyounote',
            name='contact_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
