# Generated by Django 4.1.7 on 2023-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20220516_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankyounote',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
