# Generated by Django 5.1.1 on 2025-01-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0008_thankyounote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="thankyounote",
            name="salesforce_id",
            field=models.CharField(
                blank=True, default="", help_text="Not null if uploaded to Salesforce", max_length=255
            ),
        ),
    ]
