# Generated by Django 5.1.1 on 2025-01-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0009_alter_thankyounote_options"),
        ("donations", "0009_thankyounote_salesforce_id"),
    ]

    operations = []
