# Generated by Django 5.2.12 on 2026-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0011_sitebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="thankyounote",
            name="account_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="OpenStax Accounts UUID, set when the note is submitted by a logged-in user",
                null=True,
            ),
        ),
    ]
