# Generated by Django 6.0.7 on 2026-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0012_thankyounote_account_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Download Popup"),
                            ("instructor_resources", "Instructor Resources Popup"),
                            ("student_resources", "Student Resources Popup"),
                            ("other", "Other Popups (View Online, K12)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        help_text="A/B variant label for this placement. This is what shows up in analytics, so name it accordingly. Two or more rows sharing a placement with different variants run an A/B test on that placement; a single row means no test.",
                        max_length=255,
                    ),
                ),
                ("url", models.URLField(help_text="Where this donation link sends people")),
                (
                    "header_subtitle",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Overrides the Donation Popup's subtitle for this variant; leave blank to use the default",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Donation Link",
                "verbose_name_plural": "Donation Links",
                "ordering": ["placement", "variant"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placement", "variant"), name="unique_donation_link_placement_variant"
                    )
                ],
            },
        ),
    ]
