# Generated by Django 6.0.7 on 2026-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0015_donationlink_give_link_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationlink",
            name="header_image",
            field=models.ImageField(
                blank=True,
                help_text="Overrides the Donation Popup's image for this variant; leave blank to use the default",
                null=True,
                upload_to="",
            ),
        ),
    ]
