# Generated by Django 6.0.7 on 2026-09-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0017_donationlink_header_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationlink",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Where this donation link sends people; leave blank to use the Donation Popup's link. Blank lets a variant test copy or imagery without repeating the destination.",
            ),
        ),
    ]
