# Generated by Django 3.0.4 on 2020-07-16 22:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    replaces = [('snippets', '0001_initial'), ('snippets', '0002_communityresource'), ('snippets', '0003_delete_communityresource'), ('snippets', '0004_auto_20160708_1008'), ('snippets', '0005_facultyresource_unlocked_resource'), ('snippets', '0006_roles'), ('snippets', '0007_auto_20170411_1354'), ('snippets', '0008_auto_20170427_1226'), ('snippets', '0009_studentresource_unlocked_resource'), ('snippets', '0010_communityresource_sharedcontent'), ('snippets', '0011_delete_communityresource'), ('snippets', '0012_auto_20180418_1034'), ('snippets', '0013_newssources'), ('snippets', '0014_auto_20180509_1010'), ('snippets', '0015_auto_20180517_1103'), ('snippets', '0016_newssource'), ('snippets', '0017_auto_20180801_1719'), ('snippets', '0018_facultyresource_creator_fest_resource'), ('snippets', '0019_sharedcontent_content_logged_in'), ('snippets', '0020_subject_search_description'), ('snippets', '0021_subject_seo_title'), ('snippets', '0022_subject_page_content')]

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('unlocked_resource', models.BooleanField(default=False)),
                ('creator_fest_resource', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('unlocked_resource', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_content', models.TextField(blank=True, help_text='Content that appears on the subjects page when looking at a subject.')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('salesforce_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for identification.', max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('content_logged_in', models.TextField(blank=True, null=True)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
