# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_communityresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityResource',
        ),
    ]
