# Generated by Django 3.0.4 on 2020-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_delete_givetoday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationFormContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('disclaimer', models.TextField()),
                ('next_steps', models.TextField()),
            ],
        ),
    ]
