# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20160708_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresource',
            name='unlocked_resource',
            field=models.BooleanField(default=False),
        ),
    ]
