# Generated by Django 3.0.4 on 2020-09-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_customizationformcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizationFormContent',
        ),
    ]
