# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20160708_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyresource',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentresource',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
