# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20170411_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='role',
            name='salesforce_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
