# Generated by Django 2.0.2 on 2018-04-05 19:13

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_studentresource_unlocked_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for identification.', max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
