# Generated by Django 2.0.2 on 2018-04-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_communityresource_sharedcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityResource',
        ),
    ]
