# Generated by Django 3.2.9 on 2022-01-25 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('snippets', '0012_auto_20210715_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject', models.CharField(blank=True, help_text='should match subject names in Subject snippets.', max_length=255, null=True)),
                ('subject_category', models.CharField(blank=True, help_text='category for subject.', max_length=255, null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
