# Generated by Django 2.0.2 on 2018-08-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcontent',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
