# Generated by Django 2.0.2 on 2018-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20180801_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresource',
            name='creator_fest_resource',
            field=models.BooleanField(default=False),
        ),
    ]
