# Generated by Django 3.2.9 on 2022-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_subjectcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('deep-green', 'Deep Green'), ('gold', 'Gold'), ('gray', 'Gray'), ('green', 'Green'), ('light-blue', 'Light Blue'), ('light-gray', 'Light Gray'), ('medium-blue', 'Medium Blue'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='blue', help_text='The color of the vertical stripe on Subject page.', max_length=255),
        ),
    ]
