# Generated by Django 2.0.13 on 2019-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0019_sharedcontent_content_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='search_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
