# Generated by Django 3.2.5 on 2022-05-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0022_merge_0020_contentlicense_0021_blogcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentLicense',
        ),
    ]
