# Generated by Django 4.0.8 on 2023-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0025_facultyresource_icon_studentresource_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresource',
            name='resource_category',
            field=models.CharField(blank=True, help_text='Category for GA4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentresource',
            name='resource_category',
            field=models.CharField(blank=True, help_text='Category for GA4', max_length=255, null=True),
        ),
    ]
