# Generated by Django 4.1.7 on 2023-11-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0030_alter_erratacontent_book_state'),
        ('snippets', '0030_amazonbookblurb'),
    ]

    operations = [
    ]
