# Generated by Django 4.1.7 on 2024-01-30 18:04

from django.db import migrations


def migrate_old_data(apps, schema_editor):
    PromoteSnippet = apps.get_model("snippets", "PromoteSnippet")
    AssignableAvailable = apps.get_model("snippets", "AssignableAvailable")
    for assignable_snippet in AssignableAvailable.objects.all():
        snippet = PromoteSnippet.objects.create(
            name=assignable_snippet.name,
            description=assignable_snippet.description,
            image=assignable_snippet.image
        )
        snippet.save()

class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0033_promotesnippet"),
    ]

    operations = [
        migrations.RunPython(migrate_old_data),
        migrations.DeleteModel(
            name="AssignableAvailable",
        ),
    ]
