# Generated by Django 4.1.7 on 2024-01-30 18:04

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0033_promotesnippet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssignableAvailable",
        ),
    ]
