# Generated by Django 5.0.4 on 2024-06-28 01:41
# Modified to remove PageLayout model operations (created and deleted in same release)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0036_contentwarning"),
    ]

    operations = [
        # PageLayout was created and deleted in the same release cycle
        # Squashing migrations 0037-0041 into no-op
    ]

