# Generated by Django 5.0.4 on 2024-06-28 18:00
# Modified to no-op (PageLayout model operations removed)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0037_pagelayout"),
    ]

    operations = [
        # No-op: PageLayout operations squashed
    ]

