# Generated by Django 5.0.4 on 2024-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0037_pagelayout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelayout",
            name="layout",
            field=models.CharField(choices=[("Default", "default")], default="default", max_length=255),
        ),
    ]
