# Generated by Django 5.0.7 on 2024-07-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0039_alter_pagelayout_layout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagelayout",
            name="background_image",
        ),
    ]
