# Generated by Django 5.0.7 on 2024-07-23 16:39
# Modified to no-op (PageLayout model operations removed)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0039_alter_pagelayout_layout"),
    ]

    operations = [
        # No-op: PageLayout operations squashed
    ]

