# Generated by Django 5.0.12 on 2025-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0042_alter_amazonbookblurb_locale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="k12subject",
            name="subject_color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("midnight", "Midnight"),
                    ("deep-green", "Deep Green"),
                    ("gold", "Gold"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("light-blue", "Light Blue"),
                    ("light-gray", "Light Gray"),
                    ("medium-blue", "Medium Blue"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("raise-green", "Raise Green"),
                ],
                default="blue",
                help_text="The color of the vertical stripe on Subject page.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("midnight", "Midnight"),
                    ("deep-green", "Deep Green"),
                    ("gold", "Gold"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("light-blue", "Light Blue"),
                    ("light-gray", "Light Gray"),
                    ("medium-blue", "Medium Blue"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("raise-green", "Raise Green"),
                ],
                default="blue",
                help_text="The color of the vertical stripe on Subject page.",
                max_length=255,
            ),
        ),
    ]
