# Generated by Django 5.2.12 on 2026-06-13 02:35
#
# Adds per-locale uniqueness to the snippets used as wagtail-transfer lookup
# keys (see WAGTAILTRANSFER_LOOKUP_FIELDS in settings/base.py), so an import
# matches an existing row instead of raising MultipleObjectsReturned.
#
# NOTE: AddConstraint fails if existing rows already violate a constraint
# (two same-name snippets in one locale, or >1 of a singleton snippet per
# locale). If this migration errors on deploy, dedupe the offending rows
# first, then re-run. The refresh-from-prod runbook calls this out.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0045_delete_givebanner"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="amazonbookblurb",
            constraint=models.UniqueConstraint(fields=("locale",), name="unique_amazonbookblurb_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="blogcollection",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_blogcollection_name_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="blogcontenttype",
            constraint=models.UniqueConstraint(
                fields=("content_type", "locale"), name="unique_blogcontenttype_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentwarning",
            constraint=models.UniqueConstraint(fields=("locale",), name="unique_contentwarning_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="erratacontent",
            constraint=models.UniqueConstraint(
                fields=("heading", "book_state", "locale"), name="unique_erratacontent_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyresource",
            constraint=models.UniqueConstraint(
                fields=("heading", "locale"), name="unique_facultyresource_heading_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="k12subject",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_k12subject_name_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="newssource",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_newssource_name_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="nowebinarmessage",
            constraint=models.UniqueConstraint(fields=("locale",), name="unique_nowebinarmessage_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="promotesnippet",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_promotesnippet_name_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="requireloginmessage",
            constraint=models.UniqueConstraint(fields=("locale",), name="unique_requireloginmessage_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("salesforce_name", "locale"), name="unique_role_salesforce_name_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedcontent",
            constraint=models.UniqueConstraint(
                fields=("title", "locale"), name="unique_sharedcontent_title_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentresource",
            constraint=models.UniqueConstraint(
                fields=("heading", "locale"), name="unique_studentresource_heading_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_subject_name_per_locale"),
        ),
        migrations.AddConstraint(
            model_name="subjectcategory",
            constraint=models.UniqueConstraint(
                fields=("subject", "subject_category", "locale"), name="unique_subjectcategory_per_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="webinarcollection",
            constraint=models.UniqueConstraint(
                fields=("name", "locale"), name="unique_webinarcollection_name_per_locale"
            ),
        ),
    ]
