# Generated by Django 5.2.12 on 2026-06-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0046_amazonbookblurb_unique_amazonbookblurb_per_locale_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blogcollection",
            name="unique_blogcollection_name_per_locale",
        ),
        migrations.RemoveConstraint(
            model_name="blogcontenttype",
            name="unique_blogcontenttype_per_locale",
        ),
        migrations.RemoveConstraint(
            model_name="erratacontent",
            name="unique_erratacontent_per_locale",
        ),
        migrations.RemoveConstraint(
            model_name="promotesnippet",
            name="unique_promotesnippet_name_per_locale",
        ),
        migrations.RemoveConstraint(
            model_name="subjectcategory",
            name="unique_subjectcategory_per_locale",
        ),
        migrations.RemoveConstraint(
            model_name="webinarcollection",
            name="unique_webinarcollection_name_per_locale",
        ),
        migrations.AddConstraint(
            model_name="blogcollection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("name", "locale"),
                name="unique_blogcollection_name_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogcontenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_type__isnull", False)),
                fields=("content_type", "locale"),
                name="unique_blogcontenttype_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="erratacontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("heading__isnull", False)),
                fields=("heading", "book_state", "locale"),
                name="unique_erratacontent_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotesnippet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("name", "locale"),
                name="unique_promotesnippet_name_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject__isnull", False), ("subject_category__isnull", False)),
                fields=("subject", "subject_category", "locale"),
                name="unique_subjectcategory_per_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="webinarcollection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("name", "locale"),
                name="unique_webinarcollection_name_per_locale",
            ),
        ),
    ]
