# Generated by Django 5.2.12 on 2026-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0047_remove_blogcollection_unique_blogcollection_name_per_locale_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="promotesnippet",
            name="unique_promotesnippet_name_per_locale",
        ),
        migrations.AlterField(
            model_name="promotesnippet",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="promotesnippet",
            constraint=models.UniqueConstraint(fields=("name", "locale"), name="unique_promotesnippet_name_per_locale"),
        ),
    ]
