# Generated by Django 5.2.12 on 2026-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0048_remove_promotesnippet_unique_promotesnippet_name_per_locale_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="erratacontent",
            name="unique_erratacontent_per_locale",
        ),
        migrations.AlterField(
            model_name="erratacontent",
            name="heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="erratacontent",
            constraint=models.UniqueConstraint(
                fields=("heading", "book_state", "locale"), name="unique_erratacontent_per_locale"
            ),
        ),
    ]
