# Generated by Django 6.0.6 on 2026-08-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0049_alter_erratacontent_heading_non_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultyresource",
            name="creator_fest_resource",
        ),
    ]
