# Generated by Django 2.0.13 on 2019-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_encrypted_salt', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_salt', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_base_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Salesforce Settings',
            },
        ),
    ]
