# Generated by Django 3.2.5 on 2022-05-17 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oxauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStaxUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openstax_accounts_id', models.IntegerField()),
                ('openstax_accounts_uuid', models.UUIDField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
