# Generated by Django 5.0.2 on 2024-02-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oxauth", "0002_create_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="openstax_accounts_id",
        ),
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="openstax_accounts_uuid",
        ),
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="user",
        ),
    ]
