# Generated by Django 4.2.8 on 2024-02-06 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oxauth", "0002_create_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="openstax_accounts_id",
        ),
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="openstax_accounts_uuid",
        ),
        migrations.RemoveField(
            model_name="openstaxuserprofile",
            name="user",
        ),
    ]
