# Generated by Django 4.2.8 on 2024-01-03 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oxauth", "0002_create_user_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenStaxUserProfile",
        ),
    ]
