# Generated by Django 4.2.8 on 2023-12-20 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oxauth", "0003_alter_openstaxuserprofile_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenStaxUserProfile",
        ),
    ]
