# Generated by Django 4.2.8 on 2023-12-20 16:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("oxmenus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="menu",
            field=wagtail.fields.StreamField(
                [
                    (
                        "menu_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "menu_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("label", wagtail.blocks.CharBlock(max_length=255)),
                                                ("partial_url", wagtail.blocks.CharBlock(max_length=255)),
                                            ],
                                            required=True,
                                        )
                                    ),
                                )
                            ],
                            required=True,
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
