# Generated by Django 5.2.12 on 2026-06-14 16:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0004_menus_partial_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menus",
            options={"ordering": ["sort_order", "id"], "verbose_name": "Menu", "verbose_name_plural": "Menus"},
        ),
        migrations.AddField(
            model_name="menus",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Controls the order menus appear in the nav (lowest first), e.g. 10, 20, 30. Leaving gaps makes it easy to insert a menu later without renumbering.",
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="feature_flag",
            field=models.CharField(
                blank=True,
                default="",
                help_text='PostHog flag key that gates this whole dropdown, e.g. "nav-new-subjects". Blank = always show.',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="flag_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Show only when the flag equals this value, e.g. "variant-b". Blank = show whenever the flag is on.',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="key",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Stable identifier for this dropdown; survives name changes, e.g. "subjects-dropdown".',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="menu",
            field=wagtail.fields.StreamField(
                [("menu_block", 8)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional heading for this group of items within the dropdown, e.g. "By Subject". Leave blank for an ungrouped list.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Text shown for this item in the nav, e.g. "About Us" or "For K12 Teachers".',
                            "max_length": 255,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Where the item links. Usually a path on openstax.org, e.g. "/about" or "/subjects/math". Use a full "https://..." URL only for external links.',
                            "max_length": 255,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Stable identifier for targeting/experiments; survives label changes. Lowercase + hyphens, e.g. "about-us-link".',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'PostHog flag key that gates this item, e.g. "nav-k12-item". Leave blank to always show.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Show this item only when the flag equals this value, e.g. "variant-b". Blank = show whenever the flag is on.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 1), ("partial_url", 2), ("key", 3), ("feature_flag", 4), ("flag_value", 5)]],
                        {"required": True},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("name", 0), ("menu_items", 7)]], {"required": True}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="menus",
            name="name",
            field=models.CharField(help_text='Top-level nav label, e.g. "What we do" or "Subjects".', max_length=255),
        ),
        migrations.AlterField(
            model_name="menus",
            name="partial_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text='If set, this menu renders as a single top-level link (not a dropdown), e.g. "/k12". Leave blank for a dropdown with items below.',
                max_length=255,
            ),
        ),
    ]
