# Generated by Django 5.2.12 on 2026-06-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0005_alter_menus_options_menus_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menus",
            name="component_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user-menu", 'User menu ("Hi, First Name")'),
                    ("give-button", "Give button"),
                    ("rice-logo", "RICE logo"),
                ],
                default="",
                help_text="For dynamic items the site renders live (user menu, Give button, logo). Leave blank for normal links and dropdowns.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="menus",
            name="region",
            field=models.CharField(
                choices=[("utility", "Utility bar"), ("main", "Main nav"), ("footer", "Footer")],
                default="main",
                help_text="Which part of the site this menu appears in.",
                max_length=20,
            ),
        ),
    ]
