# Generated by Django 5.2.12 on 2026-06-14 23:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0006_menus_component_key_menus_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="menu",
            field=wagtail.fields.StreamField(
                [("menu_block", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional heading for this group of items within the dropdown, e.g. "By Subject". Leave blank for an ungrouped list.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Text shown for this item in the nav, e.g. "About Us" or "For K12 Teachers".',
                            "max_length": 255,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Where the item links. Usually a path on openstax.org, e.g. "/about" or "/subjects/math". Use a full "https://..." URL only for external links.',
                            "max_length": 255,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Stable identifier for targeting/experiments; survives label changes. Lowercase + hyphens, e.g. "about-us-link".',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'PostHog flag key that gates this item, e.g. "nav-k12-item". Leave blank to always show.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Show this item only when the flag equals this value, e.g. "variant-b". Blank = show whenever the flag is on.',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 1), ("partial_url", 2), ("key", 3), ("feature_flag", 4), ("flag_value", 5)]],
                        {"required": True},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("name", 0), ("menu_items", 7)]], {"required": True}),
                },
                help_text="Only for dropdowns — the items shown when this dropdown opens. Leave empty for a single link (set Partial URL) or a dynamic component (set Component key).",
            ),
        ),
    ]
