# Generated by Django 6.0.6 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0006_drop_orphan_component_key_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="name",
            field=models.CharField(
                help_text='Top-level nav label, e.g. "What we do" or "Subjects".', max_length=255, unique=True
            ),
        ),
    ]
