# Generated by Django 5.2.12 on 2026-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0007_alter_menus_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="component_key",
            field=models.CharField(
                blank=True,
                choices=[("user-menu", 'User menu ("Hi, First Name")'), ("rice-logo", "RICE logo")],
                default="",
                help_text="For dynamic items the site renders live (user menu, logo). Leave blank for normal links and dropdowns.",
                max_length=50,
            ),
        ),
    ]
