# Generated by Django 5.2.12 on 2026-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0008_alter_menus_component_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="component_key",
            field=models.CharField(
                blank=True,
                choices=[("user-menu", 'User menu ("Hi, First Name")')],
                default="",
                help_text="For dynamic items the site renders live (currently the user menu). Leave blank for normal links and dropdowns.",
                max_length=50,
            ),
        ),
    ]
