# Generated by Django 6.0.7 on 2026-09-15
#
# Step 3 of making Menus translatable: now that every row has translation_key/locale
# populated (0011), tighten both fields to non-nullable and apply the
# (translation_key, locale) unique constraint TranslatableMixin requires.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxmenus", "0011_bootstrap_menus_translatable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="locale",
            field=models.ForeignKey(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menus",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="menus",
            unique_together={("translation_key", "locale")},
        ),
    ]
