# Generated by Django 6.0.7 on 2026-09-15
#
# Seeds the three footer link columns (Help / OpenStax / Policies) as Menus rows
# with placement='footer', mirroring the hardcoded JSX columns in os-webview so the
# footer becomes CMS-editable. Reversible: the reverse only deletes rows that still
# match exactly what this migration seeded, so it is a no-op against rows an editor
# has since changed.

import json
import uuid

from django.conf import settings
from django.db import migrations
from wagtail.coreutils import get_supported_content_language_variant

FOOTER_MENUS = [
    {
        'key': 'footer-help',
        'name': 'Help',
        'sort_order': 10,
        'items': [
            ('Contact Us', '/contact', 'contact-us'),
            ('Support Center', 'https://help.openstax.org/s/', 'support-center'),
            ('FAQ', '/faq', 'faq'),
            ('Order Print', '/print/', 'order-print'),
            ('System Status', 'https://status.openstax.org/', 'system-status'),
        ],
    },
    {
        'key': 'footer-openstax',
        'name': 'OpenStax',
        'sort_order': 20,
        'items': [
            ('Press', '/press', 'press'),
            ('Newsletter', 'http://www2.openstax.org/l/218812/2016-10-04/lvk', 'newsletter'),
            ('Careers', '/careers', 'careers'),
        ],
    },
    {
        'key': 'footer-policies',
        'name': 'Policies',
        'sort_order': 30,
        'items': [
            ('Accessibility Statement', '/accessibility-statement', 'accessibility-statement'),
            ('Terms of Use', '/tos', 'terms-of-use'),
            ('Licensing', '/license', 'licensing'),
            ('Privacy Notice', '/privacy', 'privacy-notice'),
        ],
    },
]


def _menu_content(items):
    """The block-tree shape without the random per-node "id"s, so it can be
    compared for equality regardless of when/how many times it was generated."""
    return [
        {
            'type': 'menu_block',
            'value': {
                'name': '',
                'menu_items': [
                    {
                        'type': 'item',
                        'value': {
                            'label': label,
                            'partial_url': partial_url,
                            'key': key,
                            'feature_flag': '',
                            'flag_value': '',
                        },
                    }
                    for label, partial_url, key in items
                ],
            },
        }
    ]


def _strip_ids(node):
    """Recursively drop "id" keys so stored stream data can be compared against
    freshly-generated content regardless of the (random) ids each carries."""
    if isinstance(node, list):
        return [_strip_ids(item) for item in node]
    if isinstance(node, dict):
        return {k: _strip_ids(v) for k, v in node.items() if k != 'id'}
    return node


def _add_stream_ids(node):
    """Add a fresh "id" to every stream-child dict (one with "type"/"value" keys),
    without touching plain content dicts nested under "value"."""
    if isinstance(node, list):
        return [_add_stream_ids(item) for item in node]
    if isinstance(node, dict) and 'type' in node and 'value' in node:
        return {'id': str(uuid.uuid4()), 'type': node['type'], 'value': _add_stream_ids(node['value'])}
    if isinstance(node, dict):
        return {k: _add_stream_ids(v) for k, v in node.items()}
    return node


def _menu_stream_json(items):
    return json.dumps(_add_stream_ids(_menu_content(items)))


def _default_locale(apps):
    Locale = apps.get_model('wagtailcore', 'Locale')
    language_code = get_supported_content_language_variant(settings.LANGUAGE_CODE)
    return Locale.objects.get(language_code=language_code)


def seed_footer_menus(apps, schema_editor):
    Menus = apps.get_model('oxmenus', 'Menus')
    locale = _default_locale(apps)
    for entry in FOOTER_MENUS:
        Menus.objects.create(
            name=entry['name'],
            key=entry['key'],
            placement='footer',
            sort_order=entry['sort_order'],
            menu=_menu_stream_json(entry['items']),
            translation_key=uuid.uuid4(),
            locale=locale,
        )


def unseed_footer_menus(apps, schema_editor):
    Menus = apps.get_model('oxmenus', 'Menus')
    seeded_keys = [entry['key'] for entry in FOOTER_MENUS]
    for menu in Menus.objects.filter(placement='footer', key__in=seeded_keys):
        entry = next(e for e in FOOTER_MENUS if e['key'] == menu.key)
        # .raw_data is the plain list-of-dicts the StreamField stores; strip the
        # random per-node "id"s before comparing against freshly-built content.
        stored_content = _strip_ids(list(menu.menu.raw_data))
        if menu.name == entry['name'] and menu.sort_order == entry['sort_order'] \
                and stored_content == _menu_content(entry['items']):
            menu.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oxmenus', '0012_menus_translatable_unique_together'),
    ]

    operations = [
        migrations.RunPython(seed_footer_menus, unseed_footer_menus),
    ]
