# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0002_add_verbose_names'),
        ('wagtailforms', '0002_add_verbose_names'),
        ('wagtailcore', '0019_verbose_names_cleanup'),
        ('wagtailsearchpromotions', '0001_initial'),
        ('demo', '0007_auto_20151021_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='blogpagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='blogpagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='blogpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='blogpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventpagespeaker',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='BlogPageCarouselItem',
        ),
        migrations.DeleteModel(
            name='BlogPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
        migrations.DeleteModel(
            name='EventIndexPage',
        ),
        migrations.DeleteModel(
            name='EventIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
        migrations.DeleteModel(
            name='EventPageCarouselItem',
        ),
        migrations.DeleteModel(
            name='EventPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='EventPageSpeaker',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
