# Generated by Django 3.0.4 on 2020-12-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='display_on_tutor_page',
            field=models.BooleanField(default=False),
        ),
    ]
