# Generated by Django 4.0.8 on 2023-01-11 21:58

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_webinar_webinar_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='webinar_subjects',
            field=wagtail.fields.StreamField([('subject', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('subject', news.models.BlogCollectionChooserBlock(label='Blog Subject', required=True, target_model='snippets.Subject')), ('featured', wagtail.blocks.BooleanBlock(label='Featured', required=False))])))], blank=True, null=True, use_json_field=True),
        ),
    ]
