# Generated by Django 4.0.8 on 2023-07-26 19:47

from django.db import migrations
import news.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_alter_webinar_webinar_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='webinar_collections',
            field=wagtail.fields.StreamField([('collection', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('collection', news.models.BlogCollectionChooserBlock(label='Webinar Collection', required=True, target_model='snippets.WebinarCollection')), ('featured', wagtail.blocks.BooleanBlock(label='Featured', required=False)), ('popular', wagtail.blocks.BooleanBlock(label='Popular', required=False))])))], blank=True, null=True, use_json_field=True),
        ),
    ]
