# Generated by Django 5.1.1 on 2025-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinars", "0005_webinar_webinar_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinar",
            name="spaces_remaining",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
