# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0030_auto_20161026_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('R', 'Editorial Review'), ('A', 'Approved For Publish'), ('C', 'Completed')], default='N', max_length=1)),
                ('resolution', models.CharField(blank=True, choices=[('D', 'Duplicate'), ('N', 'Not An Error'), ('W', 'Will Not Fix'), ('P', 'Published'), ('M', 'Major Book Revision')], max_length=1, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('detail', models.TextField()),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('submitter_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='errata',
            name='error_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='errata.ErrorType'),
        ),
        migrations.AddField(
            model_name='errata',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='errata.Resource'),
        ),
    ]
