# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errata',
            name='resource',
        ),
        migrations.AddField(
            model_name='errata',
            name='resource',
            field=models.ManyToManyField(to='errata.Resource'),
        ),
    ]
