# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0003_errata_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='resolution',
            field=models.CharField(blank=True, choices=[('Duplicate', 'Duplicate'), ('Not An Error', 'Not An Error'), ('Will Not Fix', 'Will Not Fix'), ('Published', 'Published'), ('Major Book Revision', 'Major Book Revision')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Editorial Review', 'Editorial Review'), ('Reviewed', 'Reviewed'), ('Completed', 'Completed')], default='New', max_length=100),
        ),
    ]
