# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errata', '0008_auto_20161212_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errata',
            options={'verbose_name': 'erratum', 'verbose_name_plural': 'erratum'},
        ),
        migrations.AddField(
            model_name='errata',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
