# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0011_auto_20170131_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='error_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errata',
            name='resource_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='error_type',
            field=models.CharField(blank=True, choices=[('Other Factual Inaccuracy in Content', 'Other Factual Inaccuracy in Content'), ('General/Pedagogical Suggestion or Question', 'General/Pedagogical Suggestion or Question'), ('Incorrect Calculation or Solution', 'Incorrect Calculation or Solution'), ('Broken Link', 'Incorrect Calculation or Solution'), ('Typo', 'Typo'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='errata',
            name='resource',
        ),
        migrations.AddField(
            model_name='errata',
            name='resource',
            field=models.CharField(blank=True, choices=[('Textbook', 'Textbook'), ('iBooks version', 'iBooks version'), ('Instructor solution manual', 'Instructor solution manual'), ('Student solution manual', 'Student solution manual'), ('Openstax Tutor', 'Openstax Tutor'), ('Openstax Concept Coach', 'Openstax Concept Coach'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ErrorType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
