# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0014_auto_20170203_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaldocumentation',
            name='errata',
        ),
        migrations.DeleteModel(
            name='ExternalDocumentation',
        ),
    ]
