# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0018_auto_20170919_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='reviewed_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
