# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0019_auto_20171019_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='duplicate_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_report', to='errata.Errata'),
        ),
    ]
