# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0022_auto_20180205_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='duplicate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_report', to='errata.Errata'),
        ),
    ]
