# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0023_auto_20180222_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='assessment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
