# Generated by Django 2.0.2 on 2018-03-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0024_errata_assessment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='errata',
            name='duplicate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_report', to='errata.Errata'),
        ),
        migrations.AlterField(
            model_name='errata',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internaldocumentation',
            name='errata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='errata.Errata'),
        ),
    ]
