# Generated by Django 2.0.2 on 2018-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0025_auto_20180301_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='resolution',
            field=models.CharField(blank=True, choices=[('Duplicate', 'Duplicate'), ('Not An Error', 'Not An Error'), ('Will Not Fix', 'Will Not Fix'), ('Approved', 'Approved'), ('Major Book Revision', 'Major Book Revision'), ('Technical Error', 'Technical Error'), ('Sent to Customer Support', 'Sent to Customer Support')], max_length=100, null=True),
        ),
    ]
