# Generated by Django 2.0.2 on 2018-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0026_auto_20180308_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='number_of_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
