# Generated by Django 2.0.2 on 2018-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0028_auto_20180830_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='openstax_book',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
