# Generated by Django 2.0.13 on 2019-07-01 16:54

import django.core.validators
from django.db import migrations, models
import errata.models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0032_auto_20190627_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='type',
            field=models.CharField(blank=True, choices=[('Shadown Ban', 'Shadow Ban'), ('Force Block', 'Force Block')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='submitted_by_account_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), errata.models.is_user_blocked]),
        ),
    ]
