# Generated by Django 2.2.5 on 2019-11-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0035_emailtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='junk',
            field=models.BooleanField(default=False),
        ),
    ]
