# Generated by Django 2.2.5 on 2019-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0036_errata_junk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='number_of_errors',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
