# Generated by Django 2.2.8 on 2020-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0037_auto_20191210_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='accounts_user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errata',
            name='accounts_user_faculty_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errata',
            name='accounts_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Only users with errata admin access can view and edit the contents of this field.', null=True),
        ),
        migrations.AlterField(
            model_name='errata',
            name='junk',
            field=models.BooleanField(default=False, help_text='Flagging the erratum as junk will automatically flag it for archive as well.'),
        ),
        migrations.AlterField(
            model_name='errata',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Leaving the resolution notes blank will allow the field to auto-fill with the appropriate text based on status/resolution selections.', null=True),
        ),
    ]
