# Generated by Django 2.2.8 on 2020-02-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0039_auto_20200213_1248'),
        ('errata', '0039_auto_20200213_1418'),
    ]

    operations = [
    ]
