# Generated by Django 2.2.10 on 2020-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0040_merge_20200214_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='additional_location_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtext',
            name='email_case',
            field=models.CharField(blank=True, choices=[('Created in fall', 'Created in fall'), ('Created in spring', 'Created in spring'), ('Reviewed and (will not fix, or duplicate, or not an error, or major book revision)', 'Reviewed and (will not fix, or duplicate, or not an error, or major book revision)'), ('Reviewed and Approved', 'Reviewed and Approved'), ('Completed and Sent to Customer Support', 'Completed and Sent to Customer Support'), ('More Information Requested', 'More Information Requested'), ('Getting new edition', 'Getting new edition'), ('Partner product', 'Partner product')], max_length=100, null=True),
        ),
    ]
