# Generated by Django 3.0.4 on 2020-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0044_auto_20200714_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='resource',
            field=models.CharField(blank=True, choices=[('Textbook', 'Textbook'), ('iBooks version', 'iBooks version'), ('Instructor solution manual', 'Instructor solution manual'), ('Student solution manual', 'Student solution manual'), ('OpenStax Tutor', 'OpenStax Tutor'), ('OpenStax Concept Coach', 'OpenStax Concept Coach'), ('Rover by OpenStax', 'Rover by OpenStax'), ('OpenStax + SE', 'OpenStax + SE'), ('Kindle', 'Kindle'), ('Study guide on openstax.org', 'Study guide on openstax.org'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
