# Generated by Django 4.0.8 on 2023-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0052_alter_errata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='resource',
            field=models.CharField(blank=True, choices=[('Textbook', 'Textbook'), ('iBooks version', 'iBooks version'), ('Instructor solution manual', 'Instructor solution manual'), ('Student solution manual', 'Student solution manual'), ('OpenStax Tutor', 'OpenStax Tutor'), ('OpenStax Concept Coach', 'OpenStax Concept Coach'), ('Rover by OpenStax', 'Rover by OpenStax'), ('OpenStax + SE', 'OpenStax + SE'), ('Kindle', 'Kindle'), ('Study guide in online view', 'Study guide in online view'), ('Assignable', 'Assignable'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
