# Generated by Django 4.1.7 on 2023-09-25 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("errata", "0054_alter_errata_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errata",
            name="accounts_user_email",
        ),
        migrations.RemoveField(
            model_name="errata",
            name="accounts_user_faculty_status",
        ),
        migrations.RemoveField(
            model_name="errata",
            name="accounts_user_name",
        ),
    ]
