# Generated by Django 5.2.15 on 2026-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0172_book_banner_image_book_cover_image_alter_book_cover_and_more"),
        ("errata", "0057_create_errata_permission_groups"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="errata",
            index=models.Index(fields=["status"], name="errata_erra_status_01037b_idx"),
        ),
        migrations.AddIndex(
            model_name="errata",
            index=models.Index(fields=["archived", "junk"], name="errata_erra_archive_effe38_idx"),
        ),
        migrations.AddIndex(
            model_name="errata",
            index=models.Index(fields=["created"], name="errata_erra_created_38c391_idx"),
        ),
    ]
