# Generated by Django 2.0.2 on 2018-05-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0006_auto_20180522_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='achieving_the_dream_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='hbcu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='key_institutional_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='texas_higher_ed',
            field=models.BooleanField(default=False),
        ),
    ]
