# Generated by Django 2.0.2 on 2018-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0007_auto_20180522_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBoxDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dataset_id', models.CharField(max_length=255)),
            ],
        ),
    ]
