# Generated by Django 2.0.2 on 2018-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0009_salesforcesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='testimonial_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
