# Generated by Django 2.0.13 on 2019-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0011_auto_20190531_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapboxdataset',
            name='style_url',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
