# Generated by Django 2.0.13 on 2019-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0018_remove_adoptionopportunityrecord_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionopportunityrecord',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
