# Generated by Django 2.2.5 on 2019-11-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0023_auto_20191111_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='affordability_cost',
            field=models.BooleanField(default=False),
        ),
    ]
