# Generated by Django 2.2.5 on 2020-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0031_auto_20200109_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
