# Generated by Django 2.2.10 on 2020-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0038_remove_partnertypemapping_salesforce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='visible_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
