# Generated by Django 2.2.10 on 2020-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0039_partner_lead_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfieldnamemapping',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
