# Generated by Django 2.2.10 on 2020-03-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0039_auto_20200304_0919'),
        ('salesforce', '0040_partnerfieldnamemapping_hidden'),
    ]

    operations = [
    ]
