# Generated by Django 3.0.4 on 2020-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0041_merge_20200311_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(help_text='OID value to use for FE forms', max_length=255)),
            ],
        ),
    ]
