# Generated by Django 3.0.4 on 2020-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0043_salesforceforms_debug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforceforms',
            options={'verbose_name_plural': 'Salesforce Forms'},
        ),
        migrations.AddField(
            model_name='salesforceforms',
            name='posting_url',
            field=models.URLField(default='https://test.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8'),
            preserve_default=False,
        ),
    ]
