# Generated by Django 3.0.4 on 2020-07-07 15:42

from django.db import migrations, models
from salesforce.models import AdoptionOpportunityRecord

def remove_all_adoptions(apps, schema_editor):
    AdoptionOpportunityRecord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0044_auto_20200615_1402'),
    ]

    operations = [
        migrations.RunPython(remove_all_adoptions),
        migrations.AlterField(
            model_name='adoptionopportunityrecord',
            name='opportunity_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
