# Generated by Django 3.0.4 on 2020-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0049_resourcedownload_salesforce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedownload',
            name='resource_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
