# Generated by Django 3.0.4 on 2020-07-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0052_auto_20200728_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='updated',
        ),
    ]
