# Generated by Django 3.0.4 on 2020-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0056_auto_20200730_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='instructional_level_k12',
            field=models.BooleanField(default=False),
        ),
    ]
