# Generated by Django 3.0.4 on 2020-10-05 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0057_partner_instructional_level_k12'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('review', models.TextField(blank=True, null=True)),
                ('partner_response', models.TextField(blank=True, null=True)),
                ('submitted_by_name', models.CharField(max_length=255)),
                ('submitted_by_account_id', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=255)),
                ('rejection_reason', models.CharField(blank=True, choices=[('Content violates review standards', 'Content violates review standards'), ('Content contains personally identifiable information', 'Content contains personally identifiable information'), ('Content contains inappropriate language', 'Content contains inappropriate language'), ('Review is not based on personal experience', 'Review is not based on personal experience'), ('Content is not relevant to the product at hand', 'Content is not relevant to the product at hand')], max_length=255, null=True)),
            ],
        ),
    ]
