# Generated by Django 3.0.4 on 2020-10-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0058_auto_20201012_0946'),
        ('salesforce', '0060_partnerreview_partner'),
    ]

    operations = [
    ]
