# Generated by Django 3.0.4 on 2020-10-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0063_auto_20201014_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerreview',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='partnerreview',
            name='review_salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
