# Generated by Django 3.0.4 on 2020-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0064_auto_20201015_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='review_salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
