# Generated by Django 3.0.4 on 2020-10-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0065_auto_20201016_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Edited', 'Edited'), ('Rejected', 'Rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='savingsnumber',
            name='savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
