# Generated by Django 3.0.4 on 2020-10-23 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0066_auto_20201021_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreview',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerreview',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
