# Generated by Django 3.0.4 on 2020-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0068_auto_20201028_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Edited', 'Edited'), ('Approved', 'Approved'), ('Responded', 'Responded')], default='New', max_length=255),
        ),
    ]
