# Generated by Django 3.0.4 on 2020-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0069_auto_20201028_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreview',
            name='approved_review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
