# Generated by Django 3.0.4 on 2020-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0070_partnerreview_approved_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Edited', 'Edited'), ('Awaiting Approval', 'Awaiting Approval'), ('Approved', 'Approved'), ('Responded', 'Responded')], default='New', max_length=255),
        ),
    ]
