# Generated by Django 3.0.4 on 2020-10-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0072_auto_20201028_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerreview',
            name='approved_review_text',
        ),
    ]
