# Generated by Django 3.0.4 on 2020-11-17 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0073_remove_partnerreview_approved_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreview',
            name='partner_response_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
