# Generated by Django 3.0.4 on 2020-11-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0075_auto_20201117_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedownload',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcedownload',
            name='last_access',
            field=models.DateTimeField(),
        ),
    ]
