# Generated by Django 3.0.4 on 2021-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0079_auto_20201130_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedownload',
            name='contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
