# Generated by Django 3.0.4 on 2021-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0081_auto_20210510_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnership_level',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
