# Generated by Django 3.2.4 on 2021-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0083_alter_resourcedownload_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedownload',
            name='contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
