# Generated by Django 3.2.4 on 2021-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0085_partnerreview_user_faculty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='user_faculty_status',
            field=models.CharField(choices=[('no_faculty_info', 'No Faculty Info'), ('confirmed_faculty', 'Confirmed Faculty'), ('rejected_faculty', 'Rejected Faculty'), ('pending_faculty', 'Pending Faculty')], default='No Faculty Info', max_length=255),
        ),
    ]
