# Generated by Django 3.2.4 on 2021-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0086_alter_partnerreview_user_faculty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
