# Generated by Django 3.2.4 on 2021-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0087_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='total_school_enrollment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
