# Generated by Django 3.2.4 on 2021-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0089_auto_20211014_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceforms',
            name='tech_scout_form_posting_url',
            field=models.URLField(blank=True, help_text='Used for posting tech scout form. Can be different in each environment', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceforms',
            name='adoption_form_posting_url',
            field=models.URLField(blank=True, help_text='Used for posting adoption form. Can be different in each environment', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceforms',
            name='interest_form_posting_url',
            field=models.URLField(blank=True, help_text='Used for posting interest form. Can be different in each environment', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceforms',
            name='posting_url',
            field=models.URLField(help_text='Used for posting testamonials'),
        ),
    ]
