# Generated by Django 3.2.4 on 2021-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0091_auto_20211018_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcedownload',
            old_name='accounts_uuid',
            new_name='account_uuid',
        ),
        migrations.AddIndex(
            model_name='resourcedownload',
            index=models.Index(fields=['account_uuid'], name='salesforce__account_9af0c7_idx'),
        ),
    ]
