# Generated by Django 3.2.4 on 2021-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0092_auto_20211018_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreview',
            name='submitted_by_account_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
