# Generated by Django 3.2.4 on 2021-11-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0093_partnerreview_submitted_by_account_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreview',
            name='submitted_by_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
