# Generated by Django 3.2.9 on 2022-04-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0097_auto_20220328_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedownload',
            name='salesforce_id',
        ),
    ]
