# Generated by Django 3.2.9 on 2022-04-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0098_remove_resourcedownload_salesforce_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedownload',
            name='number_of_times_accessed',
        ),
    ]
