# Generated by Django 3.2.9 on 2022-04-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0098_partner_equity_rating'),
        ('salesforce', '0099_remove_resourcedownload_number_of_times_accessed'),
    ]

    operations = [
    ]
