# Generated by Django 3.2.5 on 2022-05-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0100_merge_20220426_0826'),
        ('salesforce', '0100_partner_partner_sf_account_id'),
    ]

    operations = [
    ]
