# Generated by Django 3.2.5 on 2022-05-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0102_auto_20220512_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='confirmed_yearly_students',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='school',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='adoptionopportunityrecord',
            name='yearly_students',
        ),
    ]
