# Generated by Django 3.2.16 on 2022-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0103_auto_20220516_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='visible_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
