# Generated by Django 5.1.1 on 2024-10-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0108_partner_partner_anniversary_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="salesforce_created_date",
        ),
    ]
