# Generated by Django 5.1.1 on 2024-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0109_remove_partner_salesforce_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="account_id",
            field=models.CharField(
                default="", help_text="The Account record for this partner solution", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="partner_status",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
