# Generated by Django 5.1.1 on 2024-10-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0110_partner_account_id_partner_partner_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_sf_account_id",
            field=models.CharField(blank=True, help_text="Deprecated. Use Account Id.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_status",
            field=models.CharField(
                default="",
                help_text="The current status of the partner Account in Salesforce.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partnership_level",
            field=models.CharField(
                default="",
                help_text="Deprecated. Use Partner Status on the Salesforce Partner Account.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="salesforce_id",
            field=models.CharField(
                blank=True, help_text="The partner solution ID from Salesforce", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="visible_on_website",
            field=models.BooleanField(default=True, help_text="If unchecked, partner will not display on openstax.org"),
        ),
    ]
