# Generated by Django 5.1.1 on 2025-01-08 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0112_remove_adoptionopportunityrecord_fall_student_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
