# Generated by Django 5.1.12 on 2026-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0114_school_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="research_agreement_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="research_agreement_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
