# Generated by Django 5.2.12 on 2026-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0115_school_research_agreement_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesforceBookName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("official_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["official_name"],
            },
        ),
    ]
