# Generated by Django 6.0.6 on 2026-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0116_salesforcebookname"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcedownload",
            name="source",
            field=models.CharField(
                blank=True, help_text="Path of the page the reader downloaded from", max_length=255, null=True
            ),
        ),
    ]
