# Generated by Django 6.0.6 on 2026-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0116_salesforcebookname"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcedownload",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("Book detail", "Book detail"), ("K12 subject", "K12 subject"), ("Flex page", "Flex page")],
                help_text="Which page the reader downloaded from",
                max_length=100,
                null=True,
            ),
        ),
    ]
