# Generated by Django 5.2.15 on 2026-07-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0116_salesforcebookname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartnerCategoryMapping",
        ),
        migrations.DeleteModel(
            name="PartnerFieldNameMapping",
        ),
        migrations.DeleteModel(
            name="PartnerTypeMapping",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="address_Longitude",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="affordability_institutional",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="assigment_outside_resources",
            new_name="assignment_outside_resources",
        ),
    ]
