# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_auto_20160906_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='show_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
