# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0009_auto_20170912_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.TextField(),
        ),
    ]
