# Generated by Django 2.0.9 on 2019-01-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('global_settings', '0015_auto_20180816_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudfrontDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'CloudFront Distribution',
            },
        ),
    ]
