# Generated by Django 2.2.10 on 2020-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0016_cloudfrontdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfrontdistribution',
            name='distribution_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
