# Generated by Django 5.1.15 on 2026-05-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0021_auto_20201002_1012'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMessaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_expires', models.DateTimeField(blank=True, help_text='When active, displays emergency banner instead of regular banners', null=True)),
                ('emergency_content', models.CharField(blank=True, help_text='Emergency message to display', max_length=500)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Emergency Messaging',
            },
        ),
        migrations.DeleteModel(
            name='StickyNote',
        ),
    ]
