# Generated by Django 6.0.6 on 2026-08-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_settings", "0022_emergencymessaging_delete_stickynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfrontdistribution",
            name="invalidation_pending",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cloudfrontdistribution",
            name="last_invalidated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
