# Generated by Django 6.0.7 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_settings", "0023_cloudfrontdistribution_invalidation_pending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="givetoday",
            name="default_give_link",
            field=models.URLField(
                blank=True,
                help_text="Used by the header Give button outside the Give Today campaign window. The campaign link above takes over between the menu start and menu expiry dates.",
                verbose_name="Default give link",
            ),
        ),
    ]
