# Generated by Django 6.0.7 on 2026-09-15
#
# Seeds Footer.social_links from the three legacy URL fields plus the two platforms
# the frontend has hardcoded with no CMS field at all (Instagram, YouTube). The
# legacy facebook_link/twitter_link/linkedin_link fields are left untouched so an
# old, currently-deployed frontend keeps working.

import json
import uuid

from django.db import migrations

INSTAGRAM_URL = 'https://www.instagram.com/openstax/'
YOUTUBE_URL = 'https://www.youtube.com/openstax/'


def _social_link_stream(platform, url):
    return {'id': str(uuid.uuid4()), 'type': 'social_link', 'value': {'platform': platform, 'url': url}}


def _seeded_value(footer):
    links = []
    if footer.facebook_link:
        links.append(_social_link_stream('facebook', footer.facebook_link))
    if footer.twitter_link:
        links.append(_social_link_stream('twitter', footer.twitter_link))
    if footer.linkedin_link:
        links.append(_social_link_stream('linkedin', footer.linkedin_link))
    links.append(_social_link_stream('instagram', INSTAGRAM_URL))
    links.append(_social_link_stream('youtube', YOUTUBE_URL))
    return links


def _platforms_and_urls(raw_items):
    return [(item.get('value', {}).get('platform'), item.get('value', {}).get('url')) for item in raw_items]


def seed_social_links(apps, schema_editor):
    Footer = apps.get_model('global_settings', 'Footer')
    for footer in Footer.objects.all():
        footer.social_links = json.dumps(_seeded_value(footer))
        footer.save(update_fields=['social_links'])


def unseed_social_links(apps, schema_editor):
    Footer = apps.get_model('global_settings', 'Footer')
    for footer in Footer.objects.all():
        seeded = _platforms_and_urls(_seeded_value(footer))
        # .raw_data is the plain list-of-dicts the StreamField stores.
        current = _platforms_and_urls(list(footer.social_links.raw_data))
        # Only clear it back out if nobody has edited it since seeding.
        if current == seeded:
            footer.social_links = '[]'
            footer.save(update_fields=['social_links'])


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0024_footer_social_links'),
    ]

    operations = [
        migrations.RunPython(seed_social_links, unseed_social_links),
    ]
