# Generated by Django 6.0.7 on 2026-09-15 00:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("global_settings", "0025_seed_give_today_default_give_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [("social_link", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("facebook", "Facebook"),
                                ("twitter", "Twitter/X"),
                                ("linkedin", "LinkedIn"),
                                ("instagram", "Instagram"),
                                ("youtube", "YouTube"),
                                ("tiktok", "TikTok"),
                                ("threads", "Threads"),
                                ("bluesky", "Bluesky"),
                                ("mastodon", "Mastodon"),
                            ],
                            "help_text": "Which platform this link is for. The frontend maps this to an icon.",
                        },
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Full URL to the OpenStax profile/page on this platform."},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("platform", 0), ("url", 1)]], {}),
                },
                default="[]",
                help_text="Social links shown in the footer, in order. facebook_link/twitter_link/linkedin_link above are kept for backward compatibility with older frontends and are not read once a frontend uses this field.",
            ),
        ),
    ]
